### ISSUE TITLE
Can't merge in system RAM

### ISSUE THREAD

**Issue by Nero10578** [axolotl-ai-cloud/axolotl#1002]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected to use the command:
`CUDA_VISIBLE_DEVICES="" python3 -m axolotl.cli.merge_lora examples/your_config.yml --lora_model_dir="./completed-model" --load_in_8bit=False --load_in_4bit=False`

To be able to merge in system RAM as suggested.

### Current behaviour

Running in Windows WSL2 Ubuntu. After successfully creating a lora checkpoint, now it gets a No CUDA GPUs are available error when running said command:

```
CUDA_VISIBLE_DEVICES="" python3 -m axolotl.cli.merge_lora qlora-70b-sunda.yml --lora_model_dir="qlora-out/checkpoint-2049" --load_in_8bit=False --load_in_4bit=False
/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2023-12-26 17:43:22,155] [INFO] [datasets.<module>:58] [PID:11653] PyTorch version 2.1.1+cu121 available.
                                 dP            dP   dP
                                 88            88   88
      .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88
      88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88
      88.  .88  .d88b.  88.  .88 88 88.  .88   88   88
      `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP



[2023-12-26 17:43:23,243] [WARNING] [axolotl.validate_config:228] [PID:11653] [RANK:0] We recommend setting `load_in_8bit: true` for LORA finetuning
[2023-12-26 17:43:23,245] [INFO] [axolotl.normalize_config:150] [PID:11653] [RANK:0] GPU memory usage baseline: 0.000GB ()
[2023-12-26 17:43:23,245] [INFO] [axolotl.common.cli.load_model_and_tokenizer:49] [PID:11653] [RANK:0] loading tokenizer... /home/owen/models/NousResearch_Llama-2-70b-hf
[2023-12-26 17:43:23,445] [DEBUG] [axolotl.load_tokenizer:184] [PID:11653] [RANK:0] EOS: 2 / </s>
[2023-12-26 17:43:23,445] [DEBUG] [axolotl.load_tokenizer:185] [PID:11653] [RANK:0] BOS: 1 / <s>
[2023-12-26 17:43:23,445] [DEBUG] [axolotl.load_tokenizer:186] [PID:11653] [RANK:0] PAD: 0 / <unk>
[2023-12-26 17:43:23,445] [DEBUG] [axolotl.load_tokenizer:187] [PID:11653] [RANK:0] UNK: 0 / <unk>
[2023-12-26 17:43:23,445] [INFO] [axolotl.common.cli.load_model_and_tokenizer:51] [PID:11653] [RANK:0] loading model and (optionally) peft_config...
[2023-12-26 17:43:23,447] [INFO] [axolotl.load_model:297] [PID:11653] [RANK:0] patching _expand_mask
Loading checkpoint shards:   0%|                                                                 | 0/15 [00:00<?, ?it/s]
[2023-12-26 17:43:24,181] [ERROR] [axolotl.load_model:478] [PID:11653] [RANK:0] No CUDA GPUs are available
Traceback (most recent call last):
  File "/home/owen/axolotl/src/axolotl/utils/models.py", line 357, in load_model
    model = LlamaForCausalLM.from_pretrained(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4116, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 778, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 317, in set_module_tensor_to_device
    new_value = value.to(device)
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Traceback (most recent call last):
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/owen/axolotl/src/axolotl/cli/merge_lora.py", line 27, in <module>
    fire.Fire(do_cli)
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/owen/axolotl/src/axolotl/cli/merge_lora.py", line 23, in do_cli
    do_merge_lora(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/home/owen/axolotl/src/axolotl/cli/__init__.py", line 70, in do_merge_lora
    model, tokenizer = load_model_and_tokenizer(cfg=cfg, cli_args=cli_args)
  File "/home/owen/axolotl/src/axolotl/common/cli.py", line 52, in load_model_and_tokenizer
    model, _ = load_model(cfg, tokenizer, inference=cli_args.inference)
  File "/home/owen/axolotl/src/axolotl/utils/models.py", line 479, in load_model
    raise err
  File "/home/owen/axolotl/src/axolotl/utils/models.py", line 357, in load_model
    model = LlamaForCausalLM.from_pretrained(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4116, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 778, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 317, in set_module_tensor_to_device
    new_value = value.to(device)
  File "/home/owen/miniconda3/envs/axolotl/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

### Steps to reproduce

1. Create a lora checkpoint
2. Try to merge it without enough GPU memory, needing system RAM instead.
3. Result in the following error.

### Config yaml

base_model: 
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false
device_map: sequential
max_memory: {0: "18GIB", 1: "24GIB"}

datasets:

dataset_prepared_path: 
val_set_size: 0.05
output_dir: ./qlora-out

save_safetensors: true

adapter: lora
lora_model_dir: 

sequence_len: 512
sample_packing: true
pad_to_sequence_len: true

lora_r: 8
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint: false
local_rank:
logging_steps: 1
xformers_attention: false
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_table_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [X] Windows

### Python Version

3.10

### axolotl branch-commit

main/628b754824008f2d7c1aad079925a1d8e8cf9f48

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by kallewoof** [comment]
#918 might address this issue.

@Nero10578 you can check it out and install it using the below (from the axolotl directory)
```
git fetch origin pull/918/head:pr-918
git checkout pr-918
pip3 install -e '.[flash-attn,deepspeed]' --no-deps
```

Then you can add
```
gpu_memory_limit: 20GiB
lora_on_cpu: true
```
to your axolotl.yml file before running the merge. (change 20GiB to whatever (edit: GPU VRAM) you have minus a few GB since it tends to overshoot a bit).

**Comment by Nero10578** [comment]
Awesome! This seems to work great! Just to be sure I should be launching the merge command with python and not accelerate right? Also it does not seem to work with the regular max_memory: {0: "18GIB", 1: "23GIB"} option in the yaml.

**Comment by kallewoof** [comment]
It doesn't? That's odd! It definitely should work with both max_memory and gpu_memory_limit (but don't use both at the same time).

Edit: yes, python to do merging as always.

**Comment by kallewoof** [comment]
As a side note that may be more relevant to your actual issue, in order to do CPU merging, you sometimes need to disable certain flags, such as flash attention, which depend on there being a GPU. My merge script explicitly does `--flash_attention=False`, for example.

Edit: as a further sidenote, if you use the code in that pull request, you don't have to turn these things off as you no longer do CPU-only merging.

**Comment by kallewoof** [comment]
OK, I see why `max_memory` is not working unless you use `gpu_memory_limit` -- the latter will add an entry `"cpu": "256GiB"` to the max memory dictionary before deriving the device map.

So to do your own max_memory thing, add the cpu entry and it should work. E.g.
```
max_memory: {0: "18GIB", 1: "23GIB", "cpu": "256GiB"}
```

You probably still need `lora_on_cpu: true` or it might OOM at the LoRA loading part.

**Comment by NanoCode012** [comment]
> As a side note that may be more relevant to your actual issue, in order to do CPU merging, you sometimes need to disable certain flags, such as flash attention, which depend on there being a GPU. My merge script explicitly does `--flash_attention=False`, for example.

I am making a PR to make these false by default to remove confusion. Thank you for pointing it out.

**Comment by NanoCode012** [comment]
Hey @Nero10578 , may I ask if the PR linked by @kallewoof fix it for you?

**Comment by Nero10578** [comment]
> Hey @Nero10578 , may I ask if the PR linked by @kallewoof fix it for you?

Hi, sorry for the late reply. Have been away since around Christmas. Will get to try this soon and report back.

**Comment by NanoCode012** [comment]
@Nero10578 , it's merged to main, so you can just pull.
