### ISSUE TITLE
formatting.py - line 270 - key error propagates to prompt_tokenizers.py and cascade of errors

### ISSUE THREAD

**Issue by Speedway1** [axolotl-ai-cloud/axolotl#1028]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The code should parse the input JSON, however it keeps failing with a "KeyError".

### Current behaviour

Have tied two file formats: alpaca and sharegpt.

For both formats, the run barfs with this error:

  File "/home/axoloti/axolotl/src/axolotl/prompt_tokenizers.py", line 111, in tokenize_prompt
    ) = self.parse_instruction_fields(prompt)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/axoloti/axolotl/src/axolotl/prompt_tokenizers.py", line 155, in parse_instruction_fields
    prompt["instruction"],
    ~~~~~~^^^^^^^^^^^^^^^
  File "/home/axoloti/axolotl_env/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 270, in __getitem__
    value = self.data[key]
            ~~~~~~~~~^^^^^
KeyError: 'instruction'
Traceback (most recent call last):
  File "/home/axoloti/axolotl_env/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^



### Steps to reproduce

1) git clone repo / get latest main branch copy of the code.
2) [ follow setup instructions at https://github.com/OpenAccess-AI-Collective/axolotl ]
3) Create test training dataset  on local drive. (in our case "peft_output.txt"). See attached.
4) Ensure that base model is accessible on local drive
5) configure the config yml (in our case "config_lora.yml"). See attached.
6) Run with this command:
     accelerate launch -m axolotl.cli.train config_lora.yml
7) Errors with the output seen in the attached "error_alpaca.txt" file.
8) Also tried various combinations with sharegpt. For this, the config_lora.yml file has the "datasets" part changed to:
     datasets:
       - path: /home/axoloti/training_data/support_bot/
         type: sharegpt
         conversation: chatml
         data_files: peft_output.txt
9) The file "peft_output_sharegpt.txt" is a copy of the input file, just given it a different name for purposes of uploading here.
10) The system barfs again on the key propagation, but a slightly different error message (see the "sharegpt_error.txt" file)


[peft_output_sharegpt.txt](https://github.com/OpenAccess-AI-Collective/axolotl/files/13806359/peft_output_sharegpt.txt)
[error_alpaca.txt](https://github.com/OpenAccess-AI-Collective/axolotl/files/13806340/error_alpaca.txt)
[config_lora.yml.txt](https://github.com/OpenAccess-AI-Collective/axolotl/files/13806332/config_lora.yml.txt)
[peft_output.txt](https://github.com/OpenAccess-AI-Collective/axolotl/files/13806336/peft_output.txt)
[sharegpt_error.txt](https://github.com/OpenAccess-AI-Collective/axolotl/files/13806363/sharegpt_error.txt)


### Config yaml

base_model: /data/openllm/SOLAR-10.7B-Instruct-v1.0
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: /home/axoloti/training_data/support_bot/
    type: sharegpt
    conversation: chatml
    data_files: peft_output.txt

dataset_prepared_path:
val_set_size: 0.05
output_dir: ./lora_out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_table_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"


### Possible solution

The failure is too consistent to have slipped into the code. This is probably something missing from the help text and the examples given. Could well be some important bit of config missing.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

Python 3.11.4

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Speedway1** [comment]
I solved it. The solution was simple:
    If you are using a local dataset, then "path" must be set to "json".

E.g.:
datasets:
  - path: json
    type: alpaca_chat.load_qa
    data_files: /home/axoloti/training_data/support_bot/peft_output.txt

**Comment by Speedway1** [comment]
The documentation is a bit misleading and this issue should be highlighted in the main section, preferably the quick start, rather than hidden away in the detail.
