### ISSUE TITLE
Is there a maximum GPU number this library supports?

### ISSUE THREAD

**Issue by l3utterfly** [axolotl-ai-cloud/axolotl#1094]
I have a setup with 7 GPUs. When I start the training, I get an error saying "SIGTERM" is sent to each process. There are no errors in the stacktrace.

However, if I limit the number of GPUs to 2 (e.g. CUDA_VISIBLE_DEVICES="0,1", the training works with the exact same config.

Stacktrace:
````
[2024-01-11 13:26:13,908] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 1 (pid: 55601) of binary: /home/layla/miniconda3/envs/axolotl/bin/python
Traceback (most recent call last):
  File "/home/layla/miniconda3/envs/axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/layla/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
======================================================
axolotl.cli.train FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-11_13:26:12
  host      : evelynenterprise
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 55601)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 55601
======================================================
````

**Comment by winglian** [comment]
exitcode -9 is usually an out of memory issue. this can happen when you are offloading parameters or the optimizer and you have multiple gpus. it's more likely to happen with more gpus since it is offloading the memory needed from multiple gpus into system RAM. the solution is to increase your system RAM.

**Comment by l3utterfly** [comment]
Ah ok, thank you.
