### ISSUE TITLE
RedPajama Finetune - Does Not Work with text-generation-inference (TGI)

### ISSUE THREAD

**Issue by ZQ-Dev8** [axolotl-ai-cloud/axolotl#1165]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I am attempting to finetune togethercomputer/RedPajama-INCITE-Base-3B-v1 using axolotl. After completing the finetune and saving the resulting model, I am seeking to serve the model locally using HuggingFace's [text-generation-inference](https://github.com/huggingface/text-generation-inference) (TGI) using default settings.

However, spinning up the server fails each time. See below for the full stack trace, but the primary error is:
`RuntimeError: weight gpt_neox.layers.0.attention.rotary_emb.inv_freq does not exist`

### Current behaviour

Here is the full trace:
```
docker run --rm   --entrypoint /bin/bash   -itd   --name "temp"   -v "path/to/model":/data   --gpus '"device=0"'   -p 0.0.0.0:8080:80   ghcr.io/huggingface/text-generation-inference:latest
1fa88de4e9b3e5433140a8c7d8b27f610ee766ba5409e86c46fc96e40bc6c81b
Container started successfully!
Running the text-generation-launcher command from /data directory inside the container...only local files will be used
2024-01-22T21:31:37.261605Z  INFO text_generation_launcher: Args { model_id: "/data/temp", revision: None, validation_workers: 2, sharded: None, num_shard: Some(1), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 2048, max_total_tokens: 8192, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "1fa88de4e9b3", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2024-01-22T21:31:37.261750Z  INFO download: text_generation_launcher: Starting download process.
2024-01-22T21:31:39.445374Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2024-01-22T21:31:39.865541Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2024-01-22T21:31:39.866109Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2024-01-22T21:31:44.142568Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 175, in get_model
    return FlashNeoXSharded(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_neox.py", line 58, in __init__
    model = FlashGPTNeoXForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 366, in __init__
    self.gpt_neox = FlashGPTNeoXModel(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 308, in __init__
    [
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 309, in <listcomp>
    FlashNeoXLayer(layer_id, config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 223, in __init__
    self.attention = FlashNeoxAttention(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 101, in __init__
    self.rotary_emb = PositionRotaryEmbedding.load(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 625, in load
    inv_freq = weights.get_tensor(f"{prefix}.inv_freq")
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 75, in get_tensor
    filename, tensor_name = self.get_filename(tensor_name)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 63, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight gpt_neox.layers.0.attention.rotary_emb.inv_freq does not exist

2024-01-22T21:31:44.773817Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 175, in get_model
    return FlashNeoXSharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_neox.py", line 58, in __init__
    model = FlashGPTNeoXForCausalLM(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 366, in __init__
    self.gpt_neox = FlashGPTNeoXModel(config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 308, in __init__
    [

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 309, in <listcomp>
    FlashNeoXLayer(layer_id, config, weights)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 223, in __init__
    self.attention = FlashNeoxAttention(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_neox_modeling.py", line 101, in __init__
    self.rotary_emb = PositionRotaryEmbedding.load(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 625, in load
    inv_freq = weights.get_tensor(f"{prefix}.inv_freq")

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 75, in get_tensor
    filename, tensor_name = self.get_filename(tensor_name)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 63, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")

RuntimeError: weight gpt_neox.layers.0.attention.rotary_emb.inv_freq does not exist
 rank=0
2024-01-22T21:31:44.870188Z ERROR text_generation_launcher: Shard 0 failed to start
2024-01-22T21:31:44.870226Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
Failed to run text-generation-launcher.
```

### Steps to reproduce

See config YAML below

### Config yaml

```
base_model: togethercomputer/RedPajama-INCITE-Base-3B-v1
base_model_config: togethercomputer/RedPajama-INCITE-Base-3B-v1
model_type: GPTNeoXForCausalLM
tokenizer_type: AutoTokenizer
load_in_8bit: false
load_in_4bit: false
datasets:
  - path: teknium/GPT4-LLM-Cleaned
    type: alpaca
dataset_prepared_path: ./axolotl_files/last_run_prepared
val_set_size: 0.01
output_dir: ./axolotl_out/temp
seed: 8
sequence_len: 2048
pad_to_sequence_len: true
sample_packing: true
save_safetensors: false
gradient_accumulation_steps: 1
micro_batch_size: 4
eval_batch_size: 4
num_epochs: 1
save_strategy: no
evals_per_epoch: 0
saves_per_epoch: 1
optimizer: adamw_torch
lr_scheduler: one_cycle
learning_rate: .000005
train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false
gradient_checkpointing: true
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
warmup_steps: 
debug:
deepspeed: path/to/zero1.json
weight_decay: 0.0
tokens:
  pad_token: "<|padding|>"
  bos_token: "<|endoftext|>"
  eos_token: "<|endoftext|>"
  unk_token: "<|endoftext|>"
```

### Possible solution

I suspected training with flash attention was the issue. However, the error persists whether the config YAML enables or disables flash attention. At this point it's unclear what the issue may be, but given the error, training with axolotl seems to introduce some architectural problem into the base model.

However, this issue *does* seem related to a [recent closed issue](https://github.com/OpenAccess-AI-Collective/axolotl/issues/731). This issue was closed due to lack of feedback from the creators, but it does seem they were also unable to load an axolotl finetune in TGI (with a different error related to tokenization).

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11.5

### axolotl branch-commit

Branch: main Commit: 1e56b88cde14826712dab1d42bffa4ff201969d9

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, could you confirm that loading the base model (without finetune worked) with TGI?

Secondly, could you try another tool for loading, just using axolotl cli inference or vllm?

**Comment by ZQ-Dev8** [comment]
Hey @NanoCode012, thanks for the quick reply.

I can confirm that loading the base model (togethercomputer/RedPajama-INCITE-Base-3B-v1) works with TGI. Here's the launch output:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/f036c6d0-7631-4001-bca2-6f76d900c29f)

And here's a quick test:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/59bf69c8-7c3d-4798-b080-9d5cd26f0fd9)

Lastly, running inference on the finetune via axolotl's inference playground _does_ seem to work (there is some wierdness, like having to press CTRL+D several times and the model not knowing when to shut up, but overall it seems OK):
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/6a3bb502-7e3b-4fe9-b0bd-f9d68a7c6227)

Let me know what else I can do to help troubleshoot.

**Comment by NanoCode012** [comment]
Could you try the fine-tuned model with another tool such as vllm? We want to make sure it's not TGI.

**Comment by ZQ-Dev8** [comment]
@NanoCode012 apologies for the delay. Running inference on the model with vllm _does_ seem to work:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/b606d95d-46e3-4edf-9674-3614ba57c20a)

Your thoughts? Definitely seems like the issue is with TGI, but I'm not fully convinced because running the base model with TGI works just fine. Something about the training process with axolotl is introducing a change that breaks model loading in TGI.

**Comment by NanoCode012** [comment]
Would it be possible to load the model and print out the layers? Check if that missing layer is there between the base and fine-tuned model.

**Comment by ZQ-Dev8** [comment]
Here's a comparison.

base model:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/d52f8353-17ef-458f-8c85-7e3c389ecd04)

finetune:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/8ae4e317-a48e-4a6a-8a0d-2ab8f859e868)

As far as I can tell, they are identical. What strikes me as odd are the multiple references to "FlashGPTNeoX", e.g. `FlashGPTNeoXModel(config, weights)`, `flash_neox_modeling.py`, etc. I suspect TGI attempts to convert the architecture to some sort of flash-attention compatible version, and in the process, something breaks:
![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/6372983/fc44172f-07a0-4360-9517-a2deca92a11d)

**Comment by ZQ-Dev8** [comment]
Unfortunately, no response so far on the issue I opened with them: https://github.com/huggingface/text-generation-inference/issues/1460

**Comment by winglian** [comment]
<img width="1063" alt="Screenshot 2024-01-24 at 6 44 13 PM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/381258/0bb85273-4f46-4dd7-859f-7c1e8eb28a41">
Here's the transformers implementation of the `GPTNeoXRotaryEmbedding` module. My guess is it has something to do with how `inv_freq` is set with `register_buffer(...)` rather than a self.inf_freq attribute, or perhaps that it is set to `persistent=False`

**Comment by winglian** [comment]
yeah, I think it's a transformers bug. 
```
            persistent (bool): whether the buffer is part of this module's
                :attr:`state_dict`.
```

**Comment by ZQ-Dev8** [comment]
Apologies for the delayed response @winglian @NanoCode012. What do you recommend I do? Should I retrain + export model with an earlier version of transformers, presumably before this bug was introduced?

**Comment by NanoCode012** [comment]
Found an interesting comment mentioning about this: https://huggingface.co/alpindale/miqu-1-70b-fp16/discussions/1#65b7d5b8d421fb7f6ae7a862


Seems like change was intentional?

I'm not sure why TGI has issues and not others. Maybe your transformer version with TGI is not up to date?

**Comment by ZQ-Dev8** [comment]
Closing this issue, as the TGI team found a fix that was included in the latest release. Thanks for the time and attention!
