### ISSUE TITLE
DPO QLoRA training on dual gpu fails with "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!"

### ISSUE THREAD

**Issue by kallewoof** [axolotl-ai-cloud/axolotl#1302]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

QLoRA adapter should work without causing issues when doing DPO training on a multi-GPU setup (2x3090 in this case).

Using `accelerate launch -m` does seem to work, but it loads the entire model on both devices, ~and it ends up running out of VRAM, despite the model being a 7B model and we have 48 GB of VRAM available.~ (retried, and it works now, but it is using more VRAM than LoRA using python -m, so while it is faster, it still doesn't let me load bigger models)

### Current behaviour

Axolotl crashes when using QLoRA adapter:
```
python -m axolotl.cli.train ./axolotl-mistral-7b-dpo.yml
[2024-02-20 15:11:16,314] [INFO] [datasets.<module>:58] [PID:623970] PyTorch version 2.0.1 available.
[2024-02-20 15:11:16,682] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 15:11:18,309] [INFO] [torch.distributed.nn.jit.instantiator.<module>:21] [PID:623970] Created a temporary directory at /tmp/tmp7xmjx98s
[2024-02-20 15:11:18,309] [INFO] [torch.distributed.nn.jit.instantiator._write:76] [PID:623970] Writing /tmp/tmp7xmjx98s/_remote_module_non_scriptable.py
[2024-02-20 15:11:18,493] [INFO] [axolotl.normalize_config:176] [PID:623970] [RANK:0] GPU memory usage baseline: 0.000GB (+0.321GB misc)
                                 dP            dP   dP 
                                 88            88   88 
      .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88 
      88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88 
      88.  .88  .d88b.  88.  .88 88 88.  .88   88   88 
      `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP 
                                                       
                                                       

[2024-02-20 15:11:18,494] [WARNING] [axolotl.scripts.check_user_token:433] [PID:623970] [RANK:0] Error verifying HuggingFace token. Remember to log in using `huggingface-cli login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
Generating train split: 30 examples [00:00, 20894.91 examples/s]
Mapping RL Dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 9045.30 examples/s]
[2024-02-20 15:11:19,262] [DEBUG] [axolotl.train.log:61] [PID:623970] [RANK:0] loading tokenizer... ./curr-model
[2024-02-20 15:11:19,320] [DEBUG] [axolotl.load_tokenizer:245] [PID:623970] [RANK:0] EOS: 2 / </s>
[2024-02-20 15:11:19,320] [DEBUG] [axolotl.load_tokenizer:246] [PID:623970] [RANK:0] BOS: 1 / <s>
[2024-02-20 15:11:19,320] [DEBUG] [axolotl.load_tokenizer:247] [PID:623970] [RANK:0] PAD: 2 / </s>
[2024-02-20 15:11:19,320] [DEBUG] [axolotl.load_tokenizer:248] [PID:623970] [RANK:0] UNK: 0 / <unk>
[2024-02-20 15:11:19,320] [INFO] [axolotl.load_tokenizer:259] [PID:623970] [RANK:0] No Chat template selected. Consider adding a chat template for easier inference.
[2024-02-20 15:11:19,320] [DEBUG] [axolotl.train.log:61] [PID:623970] [RANK:0] loading model and peft_config...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:05<00:00,  1.75s/it]
[2024-02-20 15:11:25,812] [INFO] [axolotl.load_model:659] [PID:623970] [RANK:0] GPU memory usage after model load: 1.709GB (+0.018GB cache, +0.678GB misc)
[2024-02-20 15:11:25,817] [INFO] [axolotl.load_model:700] [PID:623970] [RANK:0] converting PEFT model w/ prepare_model_for_kbit_training
[2024-02-20 15:11:25,818] [INFO] [axolotl.load_model:709] [PID:623970] [RANK:0] converting modules to torch.bfloat16 for flash attention
[2024-02-20 15:11:25,820] [INFO] [axolotl.load_lora:824] [PID:623970] [RANK:0] found linear modules: ['o_proj', 'v_proj', 'k_proj', 'up_proj', 'gate_proj', 'down_proj', 'q_proj']
[2024-02-20 15:11:25,820] [WARNING] [axolotl.load_model:739] [PID:623970] [RANK:0] there are no parameters that require gradient updates
[2024-02-20 15:11:25,820] [INFO] [axolotl.load_model:749] [PID:623970] [RANK:0] GPU memory usage after adapters: 1.709GB (+0.506GB cache, +0.678GB misc)
[2024-02-20 15:11:25,820] [DEBUG] [axolotl.train.log:61] [PID:623970] [RANK:0] Passing model_ref: None to RL trainer
Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 543.30 examples/s]
[2024-02-20 15:11:26,758] [INFO] [axolotl.train.log:61] [PID:623970] [RANK:0] Pre-saving adapter config to ./lora-out
[2024-02-20 15:11:26,760] [INFO] [axolotl.train.log:61] [PID:623970] [RANK:0] Starting trainer...
  0%|                                                                                                                                                             | 0/90 [00:00<?, ?it/s]The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torch.bfloat16.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/train.py", line 163, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 1561, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/trainer.py", line 1903, in _inner_training_loop
    tr_loss += tr_loss_step
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
  0%|                                                                                                                                                             | 0/90 [00:02<?, ?it/s]
```

### Steps to reproduce

Enable qlora adapter on a DPO training run.

### Config yaml

```yaml
base_model: /llm/mistral-7b
base_model_config: /llm/mistral-7b
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true   # load_in_4bit: false + adapter: lora works
strict: false

rl: dpo
dpo_beta: 0.01
datasets:
  - ds_type: json
    data_files:
      - dpo-intel.jsonl
    type: chatml.intel
    split: train
dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./lora-out

adapter: qlora # load_in_4bit: false + adapter: lora works

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: false

lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_8bit
adam_beta2: 0.95
adam_epsilion: 0.00001
lr_scheduler: cosine
learning_rate: 5.0e-6

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
logging_steps: 1
flash_attention: true
save_safetensors: true

warmup_steps: 10
save_steps: 89
weight_decay: 0.05
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11.5

### axolotl branch-commit

main/5a5d47458d9aaf7ead798d15291ba3d9bef785c5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by kallewoof** [comment]
Potential fix upstream in Transformers, assuming the fix is acceptable (please review? :) -- https://github.com/huggingface/transformers/pull/29144

**Comment by kallewoof** [comment]
Probably addressed in https://github.com/huggingface/trl/pull/1439
