### ISSUE TITLE
DPO QLoRA training crashes after training during model save

### ISSUE THREAD

**Issue by kallewoof** [axolotl-ai-cloud/axolotl#1304]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

It should save the model successfully.

### Current behaviour

```
accelerate launch -m axolotl.cli.train ./axolotl-mistral-7b-dpo.yml
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `2`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Using RTX 3090 or 4000 series which doesn't support faster communication speedups. Ensuring P2P and IB communications are disabled.
[2024-02-20 15:27:00,709] [INFO] [datasets.<module>:58] [PID:648453] PyTorch version 2.0.1 available.
[2024-02-20 15:27:00,712] [INFO] [datasets.<module>:58] [PID:648454] PyTorch version 2.0.1 available.
[2024-02-20 15:27:01,195] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 15:27:01,196] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-20 15:27:02,749] [INFO] [torch.distributed.nn.jit.instantiator.<module>:21] [PID:648453] Created a temporary directory at /tmp/tmpec0pvovh
[2024-02-20 15:27:02,749] [INFO] [torch.distributed.nn.jit.instantiator._write:76] [PID:648453] Writing /tmp/tmpec0pvovh/_remote_module_non_scriptable.py
[2024-02-20 15:27:02,749] [INFO] [torch.distributed.nn.jit.instantiator.<module>:21] [PID:648454] Created a temporary directory at /tmp/tmp4vzmt9g5
[2024-02-20 15:27:02,749] [INFO] [torch.distributed.nn.jit.instantiator._write:76] [PID:648454] Writing /tmp/tmp4vzmt9g5/_remote_module_non_scriptable.py
[2024-02-20 15:27:02,938] [INFO] [axolotl.normalize_config:176] [PID:648453] [RANK:0] GPU memory usage baseline: 0.000GB (+0.321GB misc)
[2024-02-20 15:27:02,940] [INFO] [axolotl.normalize_config:176] [PID:648454] [RANK:1] GPU memory usage baseline: 0.000GB (+0.321GB misc)
                                 dP            dP   dP 
                                 88            88   88 
      .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88 
      88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88 
      88.  .88  .d88b.  88.  .88 88 88.  .88   88   88 
      `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP 
                                                       
                                                       

[2024-02-20 15:27:02,974] [WARNING] [axolotl.scripts.check_user_token:433] [PID:648453] [RANK:0] Error verifying HuggingFace token. Remember to log in using `huggingface-cli login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
[2024-02-20 15:27:02,974] [WARNING] [axolotl.scripts.check_user_token:433] [PID:648454] [RANK:1] Error verifying HuggingFace token. Remember to log in using `huggingface-cli login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
Generating train split: 30 examples [00:00, 18110.12 examples/s]
Mapping RL Dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 8061.32 examples/s]
[2024-02-20 15:27:04,381] [DEBUG] [axolotl.train.log:61] [PID:648453] [RANK:0] loading tokenizer... ./curr-model
[2024-02-20 15:27:04,438] [DEBUG] [axolotl.load_tokenizer:245] [PID:648453] [RANK:0] EOS: 2 / </s>
[2024-02-20 15:27:04,438] [DEBUG] [axolotl.load_tokenizer:246] [PID:648453] [RANK:0] BOS: 1 / <s>
[2024-02-20 15:27:04,438] [DEBUG] [axolotl.load_tokenizer:247] [PID:648453] [RANK:0] PAD: 2 / </s>
[2024-02-20 15:27:04,438] [DEBUG] [axolotl.load_tokenizer:248] [PID:648453] [RANK:0] UNK: 0 / <unk>
[2024-02-20 15:27:04,438] [INFO] [axolotl.load_tokenizer:259] [PID:648453] [RANK:0] No Chat template selected. Consider adding a chat template for easier inference.
[2024-02-20 15:27:04,438] [DEBUG] [axolotl.train.log:61] [PID:648453] [RANK:0] loading model and peft_config...
Loading checkpoint shards:   0%|                                                                                                                                   | 0/3 [00:00<?, ?it/s][2024-02-20 15:27:05,180] [DEBUG] [axolotl.load_tokenizer:245] [PID:648454] [RANK:1] EOS: 2 / </s>
[2024-02-20 15:27:05,180] [DEBUG] [axolotl.load_tokenizer:246] [PID:648454] [RANK:1] BOS: 1 / <s>
[2024-02-20 15:27:05,180] [DEBUG] [axolotl.load_tokenizer:247] [PID:648454] [RANK:1] PAD: 2 / </s>
[2024-02-20 15:27:05,180] [DEBUG] [axolotl.load_tokenizer:248] [PID:648454] [RANK:1] UNK: 0 / <unk>
[2024-02-20 15:27:05,180] [INFO] [axolotl.load_tokenizer:259] [PID:648454] [RANK:1] No Chat template selected. Consider adding a chat template for easier inference.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.52s/it]
[2024-02-20 15:27:15,584] [INFO] [axolotl.load_model:659] [PID:648453] [RANK:0] GPU memory usage after model load: 4.093GB (+0.005GB cache, +0.695GB misc)
[2024-02-20 15:27:15,588] [INFO] [axolotl.load_model:700] [PID:648453] [RANK:0] converting PEFT model w/ prepare_model_for_kbit_training
[2024-02-20 15:27:15,589] [INFO] [axolotl.load_model:709] [PID:648453] [RANK:0] converting modules to torch.bfloat16 for flash attention
[2024-02-20 15:27:15,591] [INFO] [axolotl.load_lora:824] [PID:648453] [RANK:0] found linear modules: ['down_proj', 'k_proj', 'q_proj', 'v_proj', 'gate_proj', 'o_proj', 'up_proj']
[2024-02-20 15:27:15,591] [WARNING] [axolotl.load_model:739] [PID:648453] [RANK:0] there are no parameters that require gradient updates
[2024-02-20 15:27:15,592] [INFO] [axolotl.load_model:749] [PID:648453] [RANK:0] GPU memory usage after adapters: 4.093GB (+0.982GB cache, +0.695GB misc)
[2024-02-20 15:27:15,592] [DEBUG] [axolotl.train.log:61] [PID:648453] [RANK:0] Passing model_ref: None to RL trainer
Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 535.44 examples/s]
[2024-02-20 15:27:16,632] [INFO] [axolotl.train.log:61] [PID:648453] [RANK:0] Pre-saving adapter config to ./lora-out
[2024-02-20 15:27:16,633] [INFO] [axolotl.train.log:61] [PID:648453] [RANK:0] Starting trainer...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.64s/it]
[2024-02-20 15:27:16,783] [INFO] [axolotl.load_model:659] [PID:648454] [RANK:1] GPU memory usage after model load: 4.093GB (+0.005GB cache, +0.695GB misc)
[2024-02-20 15:27:16,787] [INFO] [axolotl.load_model:700] [PID:648454] [RANK:1] converting PEFT model w/ prepare_model_for_kbit_training
[2024-02-20 15:27:16,788] [INFO] [axolotl.load_model:709] [PID:648454] [RANK:1] converting modules to torch.bfloat16 for flash attention
[2024-02-20 15:27:16,790] [INFO] [axolotl.load_lora:824] [PID:648454] [RANK:1] found linear modules: ['v_proj', 'up_proj', 'gate_proj', 'down_proj', 'o_proj', 'k_proj', 'q_proj']
[2024-02-20 15:27:16,790] [WARNING] [axolotl.load_model:739] [PID:648454] [RANK:1] there are no parameters that require gradient updates
[2024-02-20 15:27:16,791] [INFO] [axolotl.load_model:749] [PID:648454] [RANK:1] GPU memory usage after adapters: 4.093GB (+0.982GB cache, +0.695GB misc)
  0%|                                                                                                                                                             | 0/45 [00:00<?, ?it/s]The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torch.bfloat16.
The input hidden states seems to be silently casted in float32, this might be related to the fact you have upcasted embedding or layer norm layers in float32. We will cast back the input in torch.bfloat16.
[W reducer.cpp:1300] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1300] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
{'loss': 0.6931, 'learning_rate': 5.000000000000001e-07, 'rewards/chosen': 0.0, 'rewards/rejected': 0.0, 'rewards/accuracies': 0.0, 'rewards/margins': 0.0, 'logps/rejected': -569.8738403320312, 'logps/chosen': -737.1883544921875, 'logits/rejected': -2.897996425628662, 'logits/chosen': -2.808105230331421, 'epoch': 0.07}
{'loss': 0.6931, 'learning_rate': 1.0000000000000002e-06, 'rewards/chosen': 0.0, 'rewards/rejected': 0.0, 'rewards/accuracies': 0.0, 'rewards/margins': 0.0, 'logps/rejected': -550.015625, 'logps/chosen': -548.7717895507812, 'logits/rejected': -2.4879791736602783, 'logits/chosen': -2.487278699874878, 'epoch': 0.13}
{'loss': 0.6896, 'learning_rate': 1.5e-06, 'rewards/chosen': 0.013222656212747097, 'rewards/rejected': 0.0014051818288862705, 'rewards/accuracies': 1.0, 'rewards/margins': 0.01181747391819954, 'logps/rejected': -167.9805450439453, 'logps/chosen': -843.4319458007812, 'logits/rejected': -2.7418465614318848, 'logits/chosen': -2.823695659637451, 'epoch': 0.2}
{'loss': 0.679, 'learning_rate': 2.0000000000000003e-06, 'rewards/chosen': 0.03127868473529816, 'rewards/rejected': 0.011083679273724556, 'rewards/accuracies': 1.0, 'rewards/margins': 0.0201950054615736, 'logps/rejected': -480.74560546875, 'logps/chosen': -971.9520874023438, 'logits/rejected': -2.886260509490967, 'logits/chosen': -2.8735616207122803, 'epoch': 0.27}
 11%|████████████████▌                                                                                                                                    | 5/45 [00:09<01:11,  1.79s/it]{'loss': 0.6778, 'learning_rate': 2.5e-06, 'rewards/chosen': 0.049046628177165985, 'rewards/rejected': -0.001984558068215847, 'rewards/accuracies': 1.0, 'rewards/margins': 0.05103118717670441, 'logps/rejected': -216.49749755859375, 'logps/chosen': -237.40235900878906, 'logits/rejected': -2.364060401916504, 'logits/chosen': -2.4480926990509033, 'epoch': 0.33}
{'loss': 0.6625, 'learning_rate': 3e-06, 'rewards/chosen': 0.060001831501722336, 'rewards/rejected': 0.00013488769764080644, 'rewards/accuracies': 1.0, 'rewards/margins': 0.05986694246530533, 'logps/rejected': -514.0116577148438, 'logps/chosen': -792.5287475585938, 'logits/rejected': -2.857351779937744, 'logits/chosen': -2.8211216926574707, 'epoch': 0.4}
[...]
{'loss': 0.0352, 'learning_rate': 0.0, 'rewards/chosen': 2.158928155899048, 'rewards/rejected': -0.734637439250946, 'rewards/accuracies': 1.0, 'rewards/margins': 2.8935656547546387, 'logps/rejected': -612.1011962890625, 'logps/chosen': -778.5737915039062, 'logits/rejected': -2.8826541900634766, 'logits/chosen': -2.8630945682525635, 'epoch': 3.0}
{'train_runtime': 76.271, 'train_samples_per_second': 1.18, 'train_steps_per_second': 0.59, 'train_loss': 0.3164103556424379, 'epoch': 3.0}                                              
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [01:15<00:00,  1.68s/it]
[2024-02-20 15:28:34,251] [INFO] [axolotl.train.log:61] [PID:648453] [RANK:0] Training Completed!!! Saving pre-trained model to ./lora-out
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
(MistralForCausalLM(   (model): MistralModel(     (embed_tokens): Embedding(32000, 4096)     (layers): ModuleList(       (0-31): 32 x MistralDecoderLayer(         (self_attn): MistralFlashAttention2(           (q_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=4096, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=4096, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (k_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=4096, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=1024, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (v_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=4096, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=1024, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (o_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=4096, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=4096, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (rotary_emb): MistralRotaryEmbedding()         )         (mlp): MistralMLP(           (gate_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=4096, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=14336, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (up_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=4096, out_features=14336, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=4096, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=14336, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (down_proj): lora.Linear4bit(             (base_layer): Linear4bit(in_features=14336, out_features=4096, bias=False)             (lora_dropout): ModuleDict(               (default): Dropout(p=0, inplace=False)             )             (lora_A): ModuleDict(               (default): Linear(in_features=14336, out_features=64, bias=False)             )             (lora_B): ModuleDict(               (default): Linear(in_features=64, out_features=4096, bias=False)             )             (lora_embedding_A): ParameterDict()             (lora_embedding_B): ParameterDict()           )           (act_fn): SiLU()         )         (input_layernorm): MistralRMSNorm()         (post_attention_layernorm): MistralRMSNorm()       )     )     (norm): MistralRMSNorm()   )   (lm_head): Linear(in_features=4096, out_features=32000, bias=False) ), LlamaTokenizer(name_or_path='./curr-model', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '</s>'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={ 	0: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True), 	1: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True), 	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True), })
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/axolotl/src/axolotl/train.py", line 208, in train
    model.save_pretrained(cfg.output_dir, safe_serialization=safe_serialization)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2262, in save_pretrained
    raise ValueError(
ValueError: The model is quantized with QuantizationMethod.BITS_AND_BYTES and is not serializable - check out the warnings from the logger on the traceback to understand the reason why the quantized model is not serializable.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 648453) of binary: /home/user/workspace/miniconda3/envs/axolotl/bin/python
Traceback (most recent call last):
  File "/home/user/workspace/miniconda3/envs/axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/workspace/miniconda3/envs/axolotl/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-20_15:28:38
  host      : i9-2020
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 648453)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Steps to reproduce

Do a QLoRA DPO training session with dual GPUs using `accelerate launch`, without any deepspeed etc. configurations.

### Config yaml

```yaml
base_model: /llm/mistral-7b
base_model_config: /llm/mistral-7b
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

rl: dpo
dpo_beta: 0.01
datasets:
  - ds_type: json
    data_files:
      - dpo-intel.jsonl
    type: chatml.intel
    split: train
dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: ./lora-out

adapter: qlora

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: false

lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_8bit
adam_beta2: 0.95
adam_epsilion: 0.00001
lr_scheduler: cosine
learning_rate: 5.0e-6

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
logging_steps: 1
flash_attention: true
save_safetensors: true

warmup_steps: 10
save_steps: 89
weight_decay: 0.05
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11.5

### axolotl branch-commit

main/5a5d47458d9aaf7ead798d15291ba3d9bef785c5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by kallewoof** [comment]
This does not seem to be an issue anymore.
