### ISSUE TITLE
Mistral QLoRA example raises type error on Bnb quantization

### ISSUE THREAD

**Issue by seungwoos** [axolotl-ai-cloud/axolotl#1309]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I expect the code should run correctly as `examples/mistral/config.yaml` do.

### Current behaviour

```
CUDA_VISIBLE_DEVICES="2,3" accelerate launch -m axolotl.cli.train examples/mistral/qlora.yml --deepspeed deepspeed_configs/zero2.json 
[2024-02-21 08:14:53,979] [INFO] [datasets.<module>:58] [PID:99612] PyTorch version 2.2.0 available.
[2024-02-21 08:14:53,979] [INFO] [datasets.<module>:58] [PID:99613] PyTorch version 2.2.0 available.
[2024-02-21 08:14:55,045] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-21 08:14:55,049] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-21 08:14:56,239] [DEBUG] [axolotl.normalize_config:74] [PID:99612] [RANK:0] bf16 support detected, enabling for this configuration.
[2024-02-21 08:14:56,296] [DEBUG] [axolotl.normalize_config:74] [PID:99613] [RANK:1] bf16 support detected, enabling for this configuration.
[2024-02-21 08:14:56,521] [INFO] [axolotl.normalize_config:176] [PID:99612] [RANK:0] GPU memory usage baseline: 0.000GB (+29.791GB misc)
[2024-02-21 08:14:56,546] [INFO] [axolotl.normalize_config:176] [PID:99613] [RANK:1] GPU memory usage baseline: 0.000GB (+9.170GB misc)
                                 dP            dP   dP 
                                 88            88   88 
      .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88 
      88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88 
      88.  .88  .d88b.  88.  .88 88 88.  .88   88   88 
      `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP 
                                                       
                                                       

[2024-02-21 08:14:56,602] [WARNING] [axolotl.scripts.check_accelerate_default_config:414] [PID:99612] [RANK:0] accelerate config file found at /home/elon/.cache/huggingface/accelerate/default_config.yaml. This can lead to unexpected errors
[2024-02-21 08:14:56,709] [WARNING] [axolotl.scripts.check_accelerate_default_config:414] [PID:99613] [RANK:1] accelerate config file found at /home/elon/.cache/huggingface/accelerate/default_config.yaml. This can lead to unexpected errors
[2024-02-21 08:14:57,476] [DEBUG] [axolotl.load_tokenizer:245] [PID:99612] [RANK:0] EOS: 2 / </s>
[2024-02-21 08:14:57,477] [DEBUG] [axolotl.load_tokenizer:246] [PID:99612] [RANK:0] BOS: 1 / <s>
[2024-02-21 08:14:57,477] [DEBUG] [axolotl.load_tokenizer:247] [PID:99612] [RANK:0] PAD: 2 / </s>
[2024-02-21 08:14:57,477] [DEBUG] [axolotl.load_tokenizer:248] [PID:99612] [RANK:0] UNK: 0 / <unk>
[2024-02-21 08:14:57,477] [INFO] [axolotl.load_tokenizer:259] [PID:99612] [RANK:0] No Chat template selected. Consider adding a chat template for easier inference.
[2024-02-21 08:14:57,478] [INFO] [axolotl.load_tokenized_prepared_datasets:187] [PID:99612] [RANK:0] Loading prepared dataset from disk at last_run_prepared/44276ea68145f9d098820248ece0971a...
[2024-02-21 08:14:57,485] [INFO] [axolotl.load_tokenized_prepared_datasets:189] [PID:99612] [RANK:0] Prepared dataset loaded from disk...
[2024-02-21 08:14:58,001] [DEBUG] [axolotl.load_tokenizer:245] [PID:99613] [RANK:1] EOS: 2 / </s>
[2024-02-21 08:14:58,001] [DEBUG] [axolotl.load_tokenizer:246] [PID:99613] [RANK:1] BOS: 1 / <s>
[2024-02-21 08:14:58,001] [DEBUG] [axolotl.load_tokenizer:247] [PID:99613] [RANK:1] PAD: 2 / </s>
[2024-02-21 08:14:58,001] [DEBUG] [axolotl.load_tokenizer:248] [PID:99613] [RANK:1] UNK: 0 / <unk>
[2024-02-21 08:14:58,001] [INFO] [axolotl.load_tokenizer:259] [PID:99613] [RANK:1] No Chat template selected. Consider adding a chat template for easier inference.
[2024-02-21 08:14:58,733] [INFO] [axolotl.load_tokenized_prepared_datasets:187] [PID:99613] [RANK:1] Loading prepared dataset from disk at last_run_prepared/44276ea68145f9d098820248ece0971a...
[2024-02-21 08:14:58,741] [DEBUG] [axolotl.log:61] [PID:99612] [RANK:0] total_num_tokens: 376210
[2024-02-21 08:14:58,746] [INFO] [axolotl.load_tokenized_prepared_datasets:189] [PID:99613] [RANK:1] Prepared dataset loaded from disk...
[2024-02-21 08:14:58,766] [DEBUG] [axolotl.log:61] [PID:99612] [RANK:0] `total_supervised_tokens: 268140`
[2024-02-21 08:15:04,794] [INFO] [axolotl.utils.samplers.multipack._len_est:184] [PID:99613] [RANK:1] packing_efficiency_estimate: 1.0 total_num_tokens per device: 188105
[2024-02-21 08:15:05,098] [INFO] [axolotl.utils.samplers.multipack._len_est:184] [PID:99612] [RANK:0] packing_efficiency_estimate: 1.0 total_num_tokens per device: 188105
[2024-02-21 08:15:05,098] [DEBUG] [axolotl.log:61] [PID:99612] [RANK:0] data_loader_len: 21
[2024-02-21 08:15:05,151] [INFO] [axolotl.log:61] [PID:99612] [RANK:0] sample_packing_eff_est across ranks: [0.9567515254020691, 0.9567515254020691]
[2024-02-21 08:15:05,153] [DEBUG] [axolotl.log:61] [PID:99612] [RANK:0] sample_packing_eff_est: 0.96
[2024-02-21 08:15:05,153] [DEBUG] [axolotl.log:61] [PID:99612] [RANK:0] total_num_steps: 10
[2024-02-21 08:15:05,162] [DEBUG] [axolotl.train.log:61] [PID:99612] [RANK:0] loading tokenizer... mistralai/Mistral-7B-v0.1
[2024-02-21 08:15:05,933] [DEBUG] [axolotl.load_tokenizer:245] [PID:99613] [RANK:1] EOS: 2 / </s>
[2024-02-21 08:15:05,933] [DEBUG] [axolotl.load_tokenizer:246] [PID:99613] [RANK:1] BOS: 1 / <s>
[2024-02-21 08:15:05,933] [DEBUG] [axolotl.load_tokenizer:247] [PID:99613] [RANK:1] PAD: 2 / </s>
[2024-02-21 08:15:05,933] [DEBUG] [axolotl.load_tokenizer:248] [PID:99613] [RANK:1] UNK: 0 / <unk>
[2024-02-21 08:15:05,933] [INFO] [axolotl.load_tokenizer:259] [PID:99613] [RANK:1] No Chat template selected. Consider adding a chat template for easier inference.
[2024-02-21 08:15:06,112] [DEBUG] [axolotl.load_tokenizer:245] [PID:99612] [RANK:0] EOS: 2 / </s>
[2024-02-21 08:15:06,112] [DEBUG] [axolotl.load_tokenizer:246] [PID:99612] [RANK:0] BOS: 1 / <s>
[2024-02-21 08:15:06,112] [DEBUG] [axolotl.load_tokenizer:247] [PID:99612] [RANK:0] PAD: 2 / </s>
[2024-02-21 08:15:06,112] [DEBUG] [axolotl.load_tokenizer:248] [PID:99612] [RANK:0] UNK: 0 / <unk>
[2024-02-21 08:15:06,112] [INFO] [axolotl.load_tokenizer:259] [PID:99612] [RANK:0] No Chat template selected. Consider adding a chat template for easier inference.
[2024-02-21 08:15:06,112] [DEBUG] [axolotl.train.log:61] [PID:99612] [RANK:0] loading model and peft_config...
[2024-02-21 08:15:06,165] [INFO] [axolotl.load_model:365] [PID:99613] [RANK:1] patching mistral with flash attention
[2024-02-21 08:15:06,342] [INFO] [axolotl.load_model:365] [PID:99612] [RANK:0] patching mistral with flash attention
Loading checkpoint shards:   0%|                                                                                                                                                 | 0/2 [00:00<?, ?it/s]
[2024-02-21 08:15:09,272] [ERROR] [axolotl.load_model:612] [PID:99613] [RANK:1] Bnb4BitHfQuantizer.create_quantized_param() missing 1 required positional argument: 'unexpected_keys'
Traceback (most recent call last):
  File "/data/elon_dev/axolotl/src/axolotl/utils/models.py", line 574, in load_model
    model = getattr(transformers, model_type).from_pretrained(
  File "/home/elon/mambaforge/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3504, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/elon/mambaforge/envs/axolotl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3922, in _load_pretrained_model
    hf_quantizer.create_quantized_param(model, param, key, "cpu", state_dict)
TypeError: Bnb4BitHfQuantizer.create_quantized_param() missing 1 required positional argument: 'unexpected_keys'
```

### Steps to reproduce

CUDA version: 12.2
PyTorch version: 2.2.0

I just created a new mamba environment with python=3.10 version. On mamba, I installed PyTorch using pip `pip install torch` since there was a problem with deepspeed when installed using mamba. 

Then I just installed all the packages as mentioned in README. 
Not sure why but I additionally installed flash attention via `pip install flash-attn --no-build-isolation`, which might be the problem in my workspace.

### Config yaml

I used the same config file as provided in examples - https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/mistral/qlora.yml

### Possible solution

The problem arose when quantizing the model parameters 
`hf_quantizer.create_quantized_param(model, param, key, "cpu", state_dict)`.
 
`create_quantized_param()` in `transformers.quantizers.quantizer_bnb_{4,8}bit.py` takes extra argument `unexpected_keys` [permalink](https://github.com/huggingface/transformers/blob/1a77f07f6556b1482bd5e5f8399aa528727d1b47/src/transformers/quantizers/quantizer_bnb_8bit.py#L153) while there is no argument passed in transformer.modeling.utils.py [permalink](https://github.com/huggingface/transformers/blob/1a77f07f6556b1482bd5e5f8399aa528727d1b47/src/transformers/modeling_utils.py#L3924).

Is there anyone facing the same situation? I'm afraid there is no related issues and solely due to my workspace setting.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/5a5d47458d9aaf7ead798d15291ba3d9bef785c5

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, I think this may be better to be posted upstream. It seems that you're right that they didn't pass the proper params?

**Comment by seungwoos** [comment]
@NanoCode012 Thanks for your comment. Since there are no such issues on quantization, I was afraid this is only my problem. BTW, I'll make an issue on transformers github.

**Comment by seungwoos** [comment]
I guess the problem arose when I was working on multiple GPUs for QLoRA with mixed configs. 
- Single GPU works fine for me.
- My default accelerate config file is was set to `distributed_type: FSDP`. After change the accelerate config file to `distributed_type: Multi_GPU` it works well.
