### ISSUE TITLE
fine tune gemma model checkpoint save error

### ISSUE THREAD

**Issue by manishiitg** [axolotl-ai-cloud/axolotl#1320]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

should work

### Current behaviour

this error comes when saving model checkpoint to disk

```
en-hi-spot, pid=17057) [2024-02-23 04:53:34,661] [INFO] [axolotl.callbacks.on_train_begin:753] [PID:76] [RANK:0] The Axolotl config has been saved to the WandB run under files.
(en-hi-spot, pid=17057)   0%|          | 0/8812 [00:00<?, ?it/s][2024-02-23 04:53:35,910] [INFO] [axolotl.utils.samplers.multipack._len_est:184] [PID:76] [RANK:0] packing_efficiency_estimate: 0.95 total_num_tokens per device: 138570157
(en-hi-spot, pid=17057) [2024-02-23 04:53:37,151] [INFO] [axolotl.utils.samplers.multipack._len_est:184] [PID:76] [RANK:0] packing_efficiency_estimate: 0.95 total_num_tokens per device: 138570157
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py:1303: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(en-hi-spot, pid=17057)   total_norm_cuda = get_accelerator().FloatTensor([float(total_norm)])
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py:1303: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(en-hi-spot, pid=17057)   total_norm_cuda = get_accelerator().FloatTensor([float(total_norm)])
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py:1303: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(en-hi-spot, pid=17057)   total_norm_cuda = get_accelerator().FloatTensor([float(total_norm)])
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/deepspeed/runtime/zero/stage_1_and_2.py:1303: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(en-hi-spot, pid=17057)   total_norm_cuda = get_accelerator().FloatTensor([float(total_norm)])
{'loss': 4.1162, 'grad_norm': tensor(29.3848), 'learning_rate': 2e-05, 'epoch': 0.0}
(en-hi-spot, pid=17057)   0%|          | 1/8812 [00:26<65:49:52, 26.90s/it][2024-02-23 04:54:21,534] [INFO] [axolotl.callbacks.on_step_end:124] [PID:77] [RANK:1] GPU memory usage while training: 10.500GB (+26.225GB cache, +3.109GB misc)
(en-hi-spot, pid=17057) [2024-02-23 04:54:21,534] [INFO] [axolotl.callbacks.on_step_end:124] [PID:79] [RANK:3] GPU memory usage while training: 10.500GB (+25.504GB cache, +2.828GB misc)
(en-hi-spot, pid=17057) [2024-02-23 04:54:21,534] [INFO] [axolotl.callbacks.on_step_end:124] [PID:78] [RANK:2] GPU memory usage while training: 10.500GB (+26.225GB cache, +3.109GB misc)
(en-hi-spot, pid=17057) [2024-02-23 04:54:21,534] [INFO] [axolotl.callbacks.on_step_end:124] [PID:76] [RANK:0] GPU memory usage while training: 10.500GB (+25.504GB cache, +3.203GB misc)
{'loss': 2.2012, 'grad_norm': tensor(16.7695), 'learning_rate': 4e-05, 'epoch': 0.0}
{'loss': 2.1582, 'grad_norm': tensor(12.5129), 'learning_rate': 6e-05, 'epoch': 0.0}
{'loss': 2.0552, 'grad_norm': tensor(5.2081), 'learning_rate': 8e-05, 'epoch': 0.0}
{'loss': 1.9917, 'grad_norm': tensor(4.0804), 'learning_rate': 0.0001, 'epoch': 0.0}
{'loss': 1.8662, 'grad_norm': tensor(3.8389), 'learning_rate': 0.00012, 'epoch': 0.0}
{'loss': 1.8838, 'grad_norm': tensor(4.1035), 'learning_rate': 0.00014, 'epoch': 0.0}
{'loss': 2.8677, 'grad_norm': tensor(7.1103), 'learning_rate': 0.00016, 'epoch': 0.0}
{'loss': 1.8086, 'grad_norm': tensor(2.4890), 'learning_rate': 0.00018, 'epoch': 0.0}
{'loss': 1.7363, 'grad_norm': tensor(2.2320), 'learning_rate': 0.0002, 'epoch': 0.0}
{'loss': 1.7388, 'grad_norm': tensor(2.5520), 'learning_rate': 0.00019999999363047545, 'epoch': 0.0}
{'loss': 1.7305, 'grad_norm': tensor(2.6982), 'learning_rate': 0.00019999997452190257, 'epoch': 0.0}
{'loss': 1.7148, 'grad_norm': tensor(2.0268), 'learning_rate': 0.00019999994267428384, 'epoch': 0.0}
{'loss': 1.6772, 'grad_norm': tensor(1.6010), 'learning_rate': 0.00019999989808762325, 'epoch': 0.0}
{'loss': 1.7036, 'grad_norm': tensor(1.6965), 'learning_rate': 0.00019999984076192652, 'epoch': 0.0}
{'loss': 1.6841, 'grad_norm': tensor(1.7897), 'learning_rate': 0.00019999977069720098, 'epoch': 0.0}
{'loss': 1.6235, 'grad_norm': tensor(1.5797), 'learning_rate': 0.00019999968789345552, 'epoch': 0.0}
{'loss': 1.5625, 'grad_norm': tensor(1.4546), 'learning_rate': 0.00019999959235070068, 'epoch': 0.0}
{'loss': 1.5454, 'grad_norm': tensor(1.8180), 'learning_rate': 0.00019999948406894866, 'epoch': 0.0}
{'loss': 1.5137, 'grad_norm': tensor(1.6821), 'learning_rate': 0.00019999936304821323, 'epoch': 0.0}
(en-hi-spot, pid=17057)   0%|          | 20/8812 [06:48<49:02:18, 20.08s/it]/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
(en-hi-spot, pid=17057)   warnings.warn(
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
(en-hi-spot, pid=17057)   warnings.warn(
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
(en-hi-spot, pid=17057)   warnings.warn(
(en-hi-spot, pid=17057) /root/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
(en-hi-spot, pid=17057)   warnings.warn(


(en-hi-spot, pid=17057) Traceback (most recent call last):
(en-hi-spot, pid=17057)   File "<frozen runpy>", line 198, in _run_module_as_main
(en-hi-spot, pid=17057)   File "<frozen runpy>", line 88, in _run_code
(en-hi-spot, pid=17057)   File "/workspace/axolotl/src/axolotl/cli/train.py", line 59, in <module>
(en-hi-spot, pid=17057)     fire.Fire(do_cli)
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
(en-hi-spot, pid=17057)     component_trace = _Fire(component, args, parsed_flag_args, context, name)
(en-hi-spot, pid=17057)                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
(en-hi-spot, pid=17057)     component, remaining_args = _CallAndUpdateTrace(
(en-hi-spot, pid=17057)                                 ^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
(en-hi-spot, pid=17057)     component = fn(*varargs, **kwargs)
(en-hi-spot, pid=17057)                 ^^^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/workspace/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
(en-hi-spot, pid=17057)     return do_train(parsed_cfg, parsed_cli_args)
(en-hi-spot, pid=17057)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/workspace/axolotl/src/axolotl/cli/train.py", line 55, in do_train
(en-hi-spot, pid=17057)     return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
(en-hi-spot, pid=17057)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/workspace/axolotl/src/axolotl/train.py", line 163, in train
(en-hi-spot, pid=17057)     trainer.train(resume_from_checkpoint=resume_from_checkpoint)
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/transformers/trainer.py", line 1615, in train
(en-hi-spot, pid=17057)     return inner_training_loop(
(en-hi-spot, pid=17057)            ^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/transformers/trainer.py", line 2029, in _inner_training_loop
(en-hi-spot, pid=17057)     self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/transformers/trainer.py", line 2423, in _maybe_log_save_evaluate
(en-hi-spot, pid=17057)     self._save_checkpoint(model, trial, metrics=metrics)
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/transformers/trainer.py", line 2525, in _save_checkpoint
(en-hi-spot, pid=17057)     self.state.save_to_json(os.path.join(staging_output_dir, TRAINER_STATE_NAME))
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/site-packages/transformers/trainer_callback.py", line 113, in save_to_json
(en-hi-spot, pid=17057)     json_string = json.dumps(dataclasses.asdict(self), indent=2, sort_keys=True) + "\n"
(en-hi-spot, pid=17057)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/__init__.py", line 238, in dumps
(en-hi-spot, pid=17057)     **kw).encode(obj)
(en-hi-spot, pid=17057)           ^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 202, in encode
(en-hi-spot, pid=17057)     chunks = list(chunks)
(en-hi-spot, pid=17057)              ^^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 432, in _iterencode
(en-hi-spot, pid=17057)     yield from _iterencode_dict(o, _current_indent_level)
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
(en-hi-spot, pid=17057)     yield from chunks
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
(en-hi-spot, pid=17057)     yield from chunks
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
(en-hi-spot, pid=17057)     yield from chunks
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 439, in _iterencode
(en-hi-spot, pid=17057)     o = _default(o)
(en-hi-spot, pid=17057)         ^^^^^^^^^^^
(en-hi-spot, pid=17057)   File "/root/miniconda3/envs/py3.11/lib/python3.11/json/encoder.py", line 180, in default
(en-hi-spot, pid=17057)     raise TypeError(f'Object of type {o.__class__.__name__} '

```

### Steps to reproduce

```
docker run --gpus all \
    --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
    winglian/axolotl:main-py3.10-cu118-2.0.1 \
    accelerate launch -m axolotl.cli.train /sky_workdir/hi-qlora-hi-2.yaml
```

### Config yaml

```
base_model: teknium/OpenHermes-2.5-Mistral-7B
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

chat_template: chatml
datasets:
  - path: manishiitg/chat-instruct-hi-v9-dedupe
    type: completion
  
hub_model_id: manishiitg/open-aditi-chat-hi-1.9
hf_use_auth_token: true

wandb_project: open-aditi-chat-hi-1.9

dataset_prepared_path: manishiitg
push_dataset_to_hub: manishiitg
val_set_size: 0
output_dir: /sky-notebook/manishiitg/open-aditi-chat-hi-1.9

adapter: qlora
lora_model_dir:
save_safetensors: true

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

lora_modules_to_save:
 - embed_tokens
 - lm_head

wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false


gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints: true ## manage check point resume from here
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 20 ## increase based on your dataset
save_strategy: steps
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
# tokens: # these are delimiters
#   - "<|im_start|>"
#   - "<|im_end|>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hello @manishiitg , I just made a PR fixing this #1321 . Solution is to downgrade deepspeed.

**Comment by Nottlespike** [comment]
@NanoCode012 Downgrading did not fix  the issue for me for Gemma.

YML
```
# use google/gemma-7b if you have access
base_model: alpindale/gemma-2b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

# huggingface repo
datasets:
    - path: mhenrichsen/alpaca_2k_test
      type: alpaca
val_set_size: 0
output_dir: ./outtest
eval_sample_packing: false

adapter: qlora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true
eval_sample_packing: false

wandb_project: gemma2btest
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:


gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 5e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

lora_modules_to_save:
  - embed_tokens
  - lm_head


warmup_ratio: 0.1
evals_per_epoch: 0
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 0
debug:
deepspeed: deepspeed_configs/zero2.json
weight_decay: 0.01
fsdp:
fsdp_config:
```

Error:
```
TypeError: Object of type Tensor is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kearm/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/kearm/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/kearm/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/kearm/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/kearm/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/home/kearm/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/home/kearm/axolotl/src/axolotl/train.py", line 163, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/kearm/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/home/kearm/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2049, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/home/kearm/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2423, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/kearm/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2525, in _save_checkpoint
    self.state.save_to_json(os.path.join(staging_output_dir, TRAINER_STATE_NAME))
  File "/home/kearm/.local/lib/python3.10/site-packages/transformers/trainer_callback.py", line 113, in save_to_json
    json_string = json.dumps(dataclasses.asdict(self), indent=2, sort_keys=True) + "\n"
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

```

**Comment by abhinand5** [comment]
@Nottlespike Downgrading deepspeed worked for me.

```
pip install deepspeed==0.13.1
```

**Comment by ibndias** [comment]
Downgrading with `git checkout v0.4.0` works for me
