### ISSUE TITLE
finetune Qwen 1.5 issue

### ISSUE THREAD

**Issue by manishiitg** [axolotl-ai-cloud/axolotl#1324]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

should work

### Current behaviour

```
(en-hi-spot, pid=13461) You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
(en-hi-spot, pid=13461) Traceback (most recent call last):
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
(en-hi-spot, pid=13461)     return _run_code(code, main_globals, None,
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
(en-hi-spot, pid=13461)     exec(code, run_globals)
(en-hi-spot, pid=13461)   File "/workspace/axolotl/src/axolotl/cli/preprocess.py", line 70, in <module>
(en-hi-spot, pid=13461)     fire.Fire(do_cli)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
(en-hi-spot, pid=13461)     component_trace = _Fire(component, args, parsed_flag_args, context, name)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
(en-hi-spot, pid=13461)     component, remaining_args = _CallAndUpdateTrace(
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
(en-hi-spot, pid=13461)     component = fn(*varargs, **kwargs)
(en-hi-spot, pid=13461)   File "/workspace/axolotl/src/axolotl/cli/preprocess.py", line 60, in do_cli
(en-hi-spot, pid=13461)     load_datasets(cfg=parsed_cfg, cli_args=parsed_cli_args)
(en-hi-spot, pid=13461)   File "/workspace/axolotl/src/axolotl/cli/__init__.py", line 364, in load_datasets
(en-hi-spot, pid=13461)     tokenizer = load_tokenizer(cfg)
(en-hi-spot, pid=13461)   File "/workspace/axolotl/src/axolotl/utils/models.py", line 132, in load_tokenizer
(en-hi-spot, pid=13461)     tokenizer = tokenizer_cls.from_pretrained(
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2048, in from_pretrained
(en-hi-spot, pid=13461)     return cls._from_pretrained(
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2287, in _from_pretrained
(en-hi-spot, pid=13461)     tokenizer = cls(*init_inputs, **init_kwargs)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 182, in __init__
(en-hi-spot, pid=13461)     self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 209, in get_spm_processor
(en-hi-spot, pid=13461)     tokenizer.Load(self.vocab_file)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 961, in Load
(en-hi-spot, pid=13461)     return self.LoadFromFile(model_file)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
(en-hi-spot, pid=13461)     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
(en-hi-spot, pid=13461) TypeError: not a string
(en-hi-spot, pid=13461) Traceback (most recent call last):
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/bin/accelerate", line 8, in <module>
(en-hi-spot, pid=13461)     sys.exit(main())
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
(en-hi-spot, pid=13461)     args.func(args)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
(en-hi-spot, pid=13461)     simple_launcher(args)
(en-hi-spot, pid=13461)   File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
(en-hi-spot, pid=13461)     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
(en-hi-spot, pid=13461) subprocess.CalledProcessError: Command '['/root/miniconda3/envs/py3.10/bin/python3', '-m', 'axolotl.cli.preprocess', '/sky_workdir/hi-qwen.yaml']' returned non-zero exit status 1.
```

### Steps to reproduce

```
docker run --gpus all \
    --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
    winglian/axolotl:main-py3.10-cu121-2.1.2 \
    accelerate launch -m axolotl.cli.train /sky_workdir/hi-qwen.yaml
```

### Config yaml

```
base_model: Qwen/Qwen1.5-7B-Chat
model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

trust_remote_code: true


chat_template: chatml
datasets:
  - path: manishiitg/chat-instruct-hi-v8-dedupe
    type: completion
  
hub_model_id: manishiitg/open-aditi-chat-hi-1.8-qwen
hf_use_auth_token: true

wandb_project: open-aditi-chat-hi-1.8

dataset_prepared_path: manishiitg
push_dataset_to_hub: manishiitg
val_set_size: 0
output_dir: /sky-notebook/manishiitg/open-aditi-chat-hi-1.8-qwen

adapter: qlora
lora_model_dir:
save_safetensors: true

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

lora_modules_to_save:
 - embed_tokens
 - lm_head

wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 7
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false


gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints: true ## manage check point resume from here
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 20 ## increase based on your dataset
save_strategy: steps
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
# tokens: # these are delimiters
#   - "<|im_start|>"
#   - "<|im_end|>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
I believe with qwen, the model is gated, so you need to login with `huggingface-cli login`

also, change `tokenizer_type` to 
```yaml
tokenizer_type: AutoTokenizer
```
