### ISSUE TITLE
Mamba example config fails on latest docker

### ISSUE THREAD

**Issue by Layoric** [axolotl-ai-cloud/axolotl#1325]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Using the latest docker image and running `python -m axolotl.cli.train examples/mamba/config.yml` to successfully start training.

### Current behaviour

Creating a new instance on RunPod with the `winglian/axolotl-runpod:main-latest` image, and running the command `python -m axolotl.cli.train examples/mamba/config.yml` results in the following error and stacktrace.

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 85, in train
    model.generation_config.do_sample = True
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MambaLMHeadModel' object has no attribute 'generation_config'
```

### Steps to reproduce

To run locally, use `winglian/axolotl:main-latest` with the `docker-compose.yaml` file, and run `python -m axolotl.cli.train examples/mamba/config.yml`.

### Config yaml

base_model: state-spaces/mamba-2.8b
model_type: MambaLMHeadModel
tokenizer_type: AutoTokenizer
tokenizer_config: EleutherAI/gpt-neox-20b

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
dataset_prepared_path:
val_set_size: 0.0
output_dir: ./out

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: false

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 5e-5

train_on_inputs: false
group_by_length: true

bf16: auto
fp16:
tf32: true

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
tokens:
save_safetensors: False

### Possible solution

It looks like the `generation_config` never gets initialized, not sure which code path this is on though when using Mamba vs other models.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Let's wait for this to get merged upstream before attempting to fix this in axolotl. https://github.com/huggingface/transformers/pull/28094

**Comment by shi3z** [comment]
https://github.com/huggingface/transformers/pull/28094

It seems to be done

**Comment by scottfleming** [comment]
Bumping this, as I'm running into the same error with the old `state-spaces/mamba-130m` model. Probably the right thing to do is, now that there is a [mamba-130-hf](https://huggingface.co/state-spaces/mamba-130m-hf) model and the [mamba-130m](https://huggingface.co/state-spaces/mamba-130m) model on huggingface is gutted and presumably deprecated, update both the `mamba` [config](https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/mamba/config.yml) and any dependencies to use [mamba-130-hf](https://huggingface.co/state-spaces/mamba-130m-hf). 

I tried just changing the base model to `state-spaces/mamba-130m-hf` but got the following error:

```
[2024-04-15 15:04:58,711] [ERROR] [axolotl.load_model:607] [PID:15814] [RANK:0] MixerModel.__init__() got an unexpected keyword argument 'architectures'
Traceback (most recent call last):
  File "/home/sagemaker-user/axolotl/src/axolotl/utils/models.py", line 556, in load_model
    model = MambaLMHeadModel.from_pretrained(
  File "/home/sagemaker-user/axolotl/src/axolotl/models/mamba/modeling_mamba.py", line 124, in from_pretrained
    model = cls(**config, device=device, dtype=dtype, **kwargs)
  File "/home/sagemaker-user/axolotl/src/axolotl/models/mamba/modeling_mamba.py", line 41, in __init__
    self.backbone = MixerModel(
TypeError: MixerModel.__init__() got an unexpected keyword argument 'architectures'
```

Investigating now, but if this an obvious fix please lmk.

@winglian could you provide some context as to why the Mamba model needs special handling a la https://github.com/OpenAccess-AI-Collective/axolotl/tree/main/src/axolotl/models/mamba (I mean obviously a different model class, but now that [mamba-130-hf](https://huggingface.co/state-spaces/mamba-130m-hf) is integrated as a first-class huggingface model, do we still need this special handling or can we [just](https://github.com/OpenAccess-AI-Collective/axolotl/blob/132eb740f036eff0fa8b239ddaf0b7a359ed1732/src/axolotl/utils/models.py#L605) `from transformers import MambaConfig, MambaForCausalLM` like we do for eg [the Llama models](https://github.com/OpenAccess-AI-Collective/axolotl/blob/132eb740f036eff0fa8b239ddaf0b7a359ed1732/src/axolotl/utils/models.py#L583)?

**Comment by fakerybakery** [comment]
Hi, I'm still getting this issue while using both the HF and non-HF models

**Comment by fakerybakery** [comment]
I found that removing line 88 (`model.generation_config.do_sample = True`) seems to resolve the issue
