### ISSUE TITLE
Fail to merge LoRA (HFValidationError)

### ISSUE THREAD

**Issue by kaykyr** [axolotl-ai-cloud/axolotl#1391]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected merge

### Current behaviour

```
(ors) root@orion:/ors/libs/axolotl# python -m axolotl.cli.merge_lora /ors/configs/aura-11.8b.yml
[2024-03-11 11:19:44,989] [INFO] [datasets.<module>:58] [PID:3465] PyTorch version 2.2.0+cu121 available.
[2024-03-11 11:19:45,402] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
                                 dP            dP   dP 
                                 88            88   88 
      .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88 
      88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88 
      88.  .88  .d88b.  88.  .88 88 88.  .88   88   88 
      `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP 
                                                       
                                                       

[2024-03-11 11:19:45,866] [DEBUG] [axolotl.normalize_config:79] [PID:3465] [RANK:0] bf16 support detected, enabling for this configuration.
[2024-03-11 11:19:45,867] [INFO] [axolotl.normalize_config:178] [PID:3465] [RANK:0] GPU memory usage baseline: 0.000GB (+0.344GB misc)
[2024-03-11 11:19:45,867] [INFO] [axolotl.normalize_cfg_datasets:190] [PID:3465] [RANK:0] updating dataset teknium/OpenHermes-2.5 with `conversation: chatml` to match your chat_template
[2024-03-11 11:19:45,867] [INFO] [axolotl.common.cli.load_model_and_tokenizer:50] [PID:3465] [RANK:0] loading tokenizer... /ors/models/Aura-11.8b
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
[2024-03-11 11:19:46,091] [DEBUG] [axolotl.load_tokenizer:245] [PID:3465] [RANK:0] EOS: 2 / </s>
[2024-03-11 11:19:46,091] [DEBUG] [axolotl.load_tokenizer:246] [PID:3465] [RANK:0] BOS: 1 / <s>
[2024-03-11 11:19:46,091] [DEBUG] [axolotl.load_tokenizer:247] [PID:3465] [RANK:0] PAD: 2 / </s>
[2024-03-11 11:19:46,091] [DEBUG] [axolotl.load_tokenizer:248] [PID:3465] [RANK:0] UNK: 0 / <unk>
[2024-03-11 11:19:46,091] [INFO] [axolotl.common.cli.load_model_and_tokenizer:52] [PID:3465] [RANK:0] loading model and (optionally) peft_config...
[2024-03-11 11:19:46,092] [INFO] [axolotl.load_model:348] [PID:3465] [RANK:0] patching llama _prepare_4d_causal_attention_mask*
[2024-03-11 11:19:46,093] [INFO] [axolotl.load_model:371] [PID:3465] [RANK:0] patching _expand_mask
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.40it/s]
[2024-03-11 11:19:50,006] [INFO] [axolotl.load_model:660] [PID:3465] [RANK:0] GPU memory usage after model load: 10.807GB (+0.105GB cache, +0.723GB misc)
[2024-03-11 11:19:50,024] [INFO] [axolotl.load_model:710] [PID:3465] [RANK:0] converting modules to torch.bfloat16 for flash attention
[2024-03-11 11:19:50,027] [INFO] [axolotl.load_lora:825] [PID:3465] [RANK:0] found linear modules: ['gate_proj', 'q_proj', 'up_proj', 'o_proj', 'k_proj', 'down_proj', 'v_proj']
[2024-03-11 11:19:50,027] [DEBUG] [axolotl.load_lora:851] [PID:3465] [RANK:0] Loading pretrained PEFT - LoRA
Traceback (most recent call last):
  File "/root/anaconda3/envs/ors/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/ors/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ors/libs/axolotl/src/axolotl/cli/merge_lora.py", line 46, in <module>
    fire.Fire(do_cli)
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/ors/libs/axolotl/src/axolotl/cli/merge_lora.py", line 42, in do_cli
    do_merge_lora(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/ors/libs/axolotl/src/axolotl/cli/__init__.py", line 126, in do_merge_lora
    model, tokenizer = load_model_and_tokenizer(cfg=cfg, cli_args=cli_args)
  File "/ors/libs/axolotl/src/axolotl/common/cli.py", line 53, in load_model_and_tokenizer
    model, _ = load_model(cfg, tokenizer, inference=cli_args.inference)
  File "/ors/libs/axolotl/src/axolotl/utils/models.py", line 725, in load_model
    model, lora_config = load_adapter(model, cfg, cfg.adapter)
  File "/ors/libs/axolotl/src/axolotl/utils/models.py", line 764, in load_adapter
    return load_lora(model, cfg, inference=inference)
  File "/ors/libs/axolotl/src/axolotl/utils/models.py", line 856, in load_lora
    model = PeftModel.from_pretrained(
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/peft/peft_model.py", line 353, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/peft/peft_model.py", line 701, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 297, in load_peft_weights
    has_remote_safetensors_file = file_exists(
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/anaconda3/envs/ors/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/ors/workdir/qlora-out'. Use `repo_type` argument if needed.
```

### Steps to reproduce

I just finished the train, when I am trying to merge lora weights it fails.

### Config yaml

```yaml
base_model: /ors/models/Aura-11.8b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: teknium/OpenHermes-2.5
    type: sharegpt
chat_template: chatml
dataset_prepared_path:
val_set_size: 0.05
output_dir: /ors/workdir/qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
save_steps: 10
local_rank:
logging_steps: 1
save_safetensors: true
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by kaykyr** [comment]
I found why is this happening. I have checkpoints, so it's necessary to specify checkpoint path:

```
python -m axolotl.cli.merge_lora /ors/configs/aura-11.8b.yml --lora_model_dir="/ors/workdir/Aura-11.8b/checkpoint-400"
```

It will be helpful if axolotl could choose the last checkpoint in case of not specifying lora_model_dir

**Comment by maziyarpanahi** [comment]
I've been experiencing this issue in my recent LoRA fine-tunes. I didn't have this issue before in older versions. (I am on main branch now)

So when the LoRA finishes, we'll have something similar to this:
```
├── adapter_config.json
├── checkpoint-2390
│   ├── adapter_config.json
│   ├── adapter_model.safetensors
│   ├── optimizer.pt
│   ├── README.md
│   ├── rng_state_0.pth
│   ├── rng_state_1.pth
│   ├── rng_state_2.pth
│   ├── rng_state_3.pth
│   ├── scheduler.pt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   ├── tokenizer.model
│   ├── trainer_state.json
│   └── training_args.bin
├── config.json
├── generation_config.json
├── model-00001-of-00006.safetensors
├── model-00002-of-00006.safetensors
├── model-00003-of-00006.safetensors
├── model-00004-of-00006.safetensors
├── model-00005-of-00006.safetensors
├── model-00006-of-00006.safetensors
├── model.safetensors.index.json
├── README.md
├── runs
│   ├── Mar22_21-22-17_zen
│   │   └── events.out.tfevents.1711142543.zen.3804388.0
│   ├── Mar23_05-42-40_zen
│   │   └── events.out.tfevents.1711172568.zen.3915705.0
│   ├── Mar23_05-47-31_zen
│   │   └── events.out.tfevents.1711172868.zen.3918952.0
│   └── Mar23_06-21-46_zen
│       └── events.out.tfevents.1711175450.zen.3934203.0
├── special_tokens_map.json
├── tokenizer_config.json
└── tokenizer.model
```

I used to just point `lora_model_dir` to the root directory, but now I have to choose a checkpoint. Did something change in how we should use `lora_model_dir`? and if Yes, then what are all those `model-00001-0f...` plus the `adapter_model.safetensors` file generated in the root directory? (I cannot use it in PEFT, only checkpoints work)
