### ISSUE TITLE
Running `bigcode/starcoder2-3b` model using`examples/starcoder2/qlora.yml` config failed

### ISSUE THREAD

**Issue by insop** [axolotl-ai-cloud/axolotl#1398]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Running the code with this config, I saw the following error. I did a google and issue search, but did not find any hit

- examples/starcoder2/qlora.yml

*modules versions:*

- axolotl git hash: 8a82d2e0a443fb866b15d7bd71fffbd8171de44b  (`pip -e .`)
- transformers              4.38.2
- base docker: winglian/axolotl:main-py3.10-cu118-2.1.2

### Current behaviour

Error log

```
ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

# Full trace

Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 825, in __getitem__
    raise KeyError(key)
KeyError: 'starcoder2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Projects/Github/NLP/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/Projects/Github/NLP/axolotl/src/axolotl/cli/train.py", line 30, in do_cli
    parsed_cfg = load_cfg(config, **kwargs)
  File "/workspace/Projects/Github/NLP/axolotl/src/axolotl/cli/__init__.py", line 364, in load_cfg
    normalize_config(cfg)
  File "/workspace/Projects/Github/NLP/axolotl/src/axolotl/utils/config/__init__.py", line 119, in normalize_config
    model_config = load_model_config(cfg)
  File "/workspace/Projects/Github/NLP/axolotl/src/axolotl/utils/models.py", line 115, in load_model_config
    raise err
  File "/workspace/Projects/Github/NLP/axolotl/src/axolotl/utils/models.py", line 103, in load_model_config
    model_config = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1130, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or becau
se your version of Transformers is out of date.
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 825, in __getitem__
    raise KeyError(key)
KeyError: 'starcoder2'

```

### Steps to reproduce

```bash
accelerate launch -m axolotl.cli.train examples/starcoder2/qlora.yml
```

### Config yaml

```yaml
# snippet of `examples/starcoder2/qlora.yml`

base_model: bigcode/starcoder2-3b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
```

### Possible solution

I updated transformer `4.38.2`, but it still failed the same issue

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.13

### axolotl branch-commit

main/8a82d2e0a443fb866b15d7bd71fffbd8171de44b

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by insop** [comment]
Hi @ehartford ,

Any suggestion or input would be appreciated.

**Comment by NanoCode012** [comment]
Could you provide more stack trace? 

According to this, try upgrade transformers? https://github.com/huggingface/text-generation-inference/issues/1620#issuecomment-1982177243

**Comment by insop** [comment]
@NanoCode012 
Thank you very much for the link, previously I did update transformer only using pip.
So I did the follow way to update from the repos and **it works now**.

```
pip install git+https://github.com/huggingface/transformers.git
pip install git+https://github.com/huggingface/trl.git
pip install git+https://github.com/huggingface/datasets.git
pip install git+https://github.com/huggingface/accelerate.git
pip install git+https://github.com/huggingface/peft.git
```


I updated the trace in the main message.
