### ISSUE TITLE
AttributeError: 'torch.dtype' object has no attribute 'itemsize'

### ISSUE THREAD

**Issue by fakerybakery** [axolotl-ai-cloud/axolotl#1491]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Trained properly. (Note: other models trained properly without QLoRA)

### Current behaviour

When I use QLoRA on Mistral 7B w/ Flash Attention I'm getting `AttributeError: 'torch.dtype' object has no attribute 'itemsize'`. I tried this on a clean install (w/ a new Conda envrionment) but still got the error.

I tried without Flash Attention and still got the error.

### Steps to reproduce

Stack trace:
```
[************] [INFO] [axolotl.load_model:700] [PID:********] [RANK:0] converting PEFT model w/ prepare_model_for_kbit_training
[************] [INFO] [axolotl.load_model:709] [PID:********] [RANK:0] converting modules to torch.bfloat16 for flash attention
[************] [INFO] [axolotl.load_lora:853] [PID:********] [RANK:0] found linear modules: ['down_proj', 'q_proj', 'up_proj', 'o_proj', 'gate_proj', 'v_proj', 'k_proj']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/***********/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/***********/miniforge3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/miniforge3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/miniforge3/envs/axolotl/lib/python3.11/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/axolotl/src/axolotl/train.py", line 84, in train
    model, peft_config = load_model(cfg, tokenizer, inference=cli_args.inference)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/axolotl/src/axolotl/utils/models.py", line 724, in load_model
    model, lora_config = load_adapter(model, cfg, cfg.adapter)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/axolotl/src/axolotl/utils/models.py", line 768, in load_adapter
    return load_lora(model, cfg, inference=inference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/axolotl/src/axolotl/utils/models.py", line 905, in load_lora
    model.print_trainable_parameters()
  File "/home/***********/miniforge3/envs/axolotl/lib/python3.11/site-packages/peft/peft_model.py", line 531, in print_trainable_parameters
    trainable_params, all_param = self.get_nb_trainable_parameters()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***********/miniforge3/envs/axolotl/lib/python3.11/site-packages/peft/peft_model.py", line 511, in get_nb_trainable_parameters
    num_bytes = param.quant_storage.itemsize if hasattr(param, "quant_storage") else 1
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'torch.dtype' object has no attribute 'itemsize'
```

### Config yaml

```yaml
base_model: teknium/OpenHermes-2.5-Mistral-7B
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
    conversation: chatml
dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002
eval_sample_packing: false
train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by fakerybakery** [comment]
Note: if I use `torch==2.1.2` with Flash Attention, I get `ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory` but if I use it without Flash Attention it seems to work properly (but unfortunately uses a lot more VRAM, as expected).

**Comment by winglian** [comment]
I ran the exact YAML above using the main-latest docker image an A5000 and wasn't able to reproduce. I recommend using a docker image as those have the CUDA dependency issues all sorted.

**Comment by winglian** [comment]
I have a fix upstream in https://github.com/huggingface/peft/pull/1630

**Comment by fakerybakery** [comment]
Great, thanks! I’ll try again now that it’s merged.

**Comment by fakerybakery** [comment]
Random question- is there any reason why Axolotl installs torch 2.1 instead of 2.2?

**Comment by fakerybakery** [comment]
Hi, not sure it's an issue with peft since I ran
```
pip install -U git+https://github.com/huggingface/peft
```
and am still getting it.

The error originates from 
```
  File "/home/******/miniforge3/envs/axolotl/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1090, in num_parameters
    param.numel() * 2 * self.hf_quantizer.quantization_config.bnb_4bit_quant_storage.itemsize
```

which means it's an issue in `transformers` not `peft`? (line 1163 of `transformers/src/transformers/modeling_utils.py`)

**Comment by fakerybakery** [comment]
Hi, I was able to solve this issue by:
1. Uninstalling PyTorch
2. Installing PyTorch through Conda (`conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`)
3. Uninstalling flash-attn
4. Reinstalling the latest version of flash-attn
