### ISSUE TITLE
GaLore_AdamW_8bit_Layerwise issue: `AttributeError: 'Parameter' object has no attribute 'register_post_accumulate_grad_hook'`

### ISSUE THREAD

**Issue by bhavnicksm** [axolotl-ai-cloud/axolotl#1598]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I am trying to train the Meta LLama3 8B model with Axolotl on A6000 (48GiB), with a reduced sequence length of 2048. 

The `galore_adamw_8bit_layerwise` optimizer doesn't run and gives me the error in the title, while the `galore_adamw_8bit` optimiser works just fine, albeit with a much higher memory usage than mentioned in the paper.

### Current behaviour

This is the error that I get from running it. 
I keep most of the values the same as in the MetaLlama3 example.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bhavnick/workspaces/axolotl_exp/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bhavnick/workspaces/axolotl_exp/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/home/bhavnick/workspaces/axolotl_exp/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/home/bhavnick/workspaces/axolotl_exp/axolotl/src/axolotl/train.py", line 163, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/transformers/trainer.py", line 1837, in train
    return inner_training_loop(
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/transformers/trainer.py", line 975, in create_optimizer_and_scheduler
    self.create_optimizer()
  File "/home/bhavnick/workspaces/axolotl_exp/axolotl/src/axolotl/core/trainer_builder.py", line 248, in create_optimizer
    return super().create_optimizer()
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/transformers/trainer.py", line 1020, in create_optimizer
    optimizer_cls, optimizer_kwargs = Trainer.get_optimizer_cls_and_kwargs(self.args, opt_model)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/transformers/trainer.py", line 1341, in get_optimizer_cls_and_kwargs
    param.register_post_accumulate_grad_hook(optimizer_hook)
AttributeError: 'Parameter' object has no attribute 'register_post_accumulate_grad_hook'
Traceback (most recent call last):
  File "/home/bhavnick/workspaces/pyenv/axolotl2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/home/bhavnick/workspaces/pyenv/axolotl2/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/bhavnick/workspaces/pyenv/axolotl2/bin/python3', '-m', 'axolotl.cli.train', './pretrain-002.yml']' returned non-zero exit status 1.
```

### Steps to reproduce

1. Use the config provided below to run the training.

### Config yaml

```yaml
base_model:  meta-llama/Meta-Llama-3-8B

model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

max_steps: 200
pretraining_dataset:
    - path: /home/bhavnick/workspaces/axolotl_exp/data
      type: pretrain
dataset_prepared_path: 
val_set_size: 0.0
output_dir: ./model-out

sequence_len: 512
sample_packing: true

wandb_project: ct-axl-llama3-8b
wandb_entity:
wandb_watch:
wandb_name: 
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: galore_adamw_8bit_layerwise
lr_scheduler: cosine
learning_rate: 0.0002

optim_target_modules:
  - mlp
  - self_attn

optim_args:
  rank: 128
  update_proj_gap: 200
  scale: 0.25
  proj_type: std

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch:
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
  eos_token: <|end_of_text|>
  bos_token: <|begin_of_text|>
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

1427d5b

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Closing as stale.
