### ISSUE TITLE
Colab Notebook Example In The Repo Not Running

### ISSUE THREAD

**Issue by rajaboja** [axolotl-ai-cloud/axolotl#1784]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

[This](https://github.com/axolotl-ai-cloud/axolotl/blob/6a9cfec2227935393bcfc0fbe324ef6232c520ec/examples/colab-notebooks/colab-axolotl-example.ipynb) Colab Notebook should run successfully.

### Current behaviour

Running `!accelerate launch -m axolotl.cli.train /content/test_axolotl.yaml` throws below error.

```
The following values were not passed to `accelerate launch` and had defaults used instead:
`--num_processes` was set to a value of `1`
`--num_machines` was set to a value of `1`
`--mixed_precision` was set to a value of `'no'`
`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-07-24 10:11:18,987] [INFO] [datasets.<module>:58] [PID:4028] PyTorch version 2.1.2 available.
[2024-07-24 10:11:18,988] [INFO] [datasets.<module>:70] [PID:4028] Polars version 0.20.2 available.
[2024-07-24 10:11:18,989] [INFO] [datasets.<module>:105] [PID:4028] TensorFlow version 2.15.0 available.
[2024-07-24 10:11:18,990] [INFO] [datasets.<module>:118] [PID:4028] JAX version 0.4.26 available.
2024-07-24 10:11:19.672787: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-24 10:11:19.672837: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-24 10:11:19.674369: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-24 10:11:19.681931: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-24 10:11:20.671544: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/content/src/axolotl/src/axolotl/cli/__init__.py", line 31, in <module>
    from axolotl.train import TrainDatasetMeta
  File "/content/src/axolotl/src/axolotl/train.py", line 27, in <module>
    from axolotl.utils.trainer import setup_trainer
  File "/content/src/axolotl/src/axolotl/utils/trainer.py", line 17, in <module>
    from axolotl.core.trainer_builder import HFCausalTrainerBuilder, HFRLTrainerBuilder
  File "/content/src/axolotl/src/axolotl/core/trainer_builder.py", line 49, in <module>
    from axolotl.utils.callbacks import (
  File "/content/src/axolotl/src/axolotl/utils/callbacks/__init__.py", line 13, in <module>
    import evaluate
  File "/usr/local/lib/python3.10/dist-packages/evaluate/__init__.py", line 29, in <module>
    from .evaluation_suite import EvaluationSuite
  File "/usr/local/lib/python3.10/dist-packages/evaluate/evaluation_suite/__init__.py", line 10, in <module>
    from ..evaluator import evaluator
  File "/usr/local/lib/python3.10/dist-packages/evaluate/evaluator/__init__.py", line 17, in <module>
    from transformers.pipelines import SUPPORTED_TASKS as SUPPORTED_PIPELINE_TASKS
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py", line 26, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/usr/local/lib/python3.10/dist-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/usr/local/lib/python3.10/dist-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/usr/local/lib/python3.10/dist-packages/torch/_custom_ops.py", line 253, in inner
    custom_op = _find_custom_op(qualname, also_check_torch_library=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/_custom_op/impl.py", line 1076, in _find_custom_op
    overload = get_op(qualname)
  File "/usr/local/lib/python3.10/dist-packages/torch/_custom_op/impl.py", line 1062, in get_op
    error_not_found()
  File "/usr/local/lib/python3.10/dist-packages/torch/_custom_op/impl.py", line 1052, in error_not_found
    raise ValueError(
ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', '/content/test_axolotl.yaml']' returned non-zero exit status 1.
```

### Steps to reproduce

Run [this](https://github.com/axolotl-ai-cloud/axolotl/blob/6a9cfec2227935393bcfc0fbe324ef6232c520ec/examples/colab-notebooks/colab-axolotl-example.ipynb)  Notebook.

### Possible solution

Delete the below cell installing the dependencies.
```
!pip install torch=="2.1.2"
!pip install -e git+https://github.com/axolotl-ai-cloud/axolotl#egg=axolotl
!pip install flash-attn=="2.5.0"
!pip install deepspeed=="0.13.1"!pip install mlflow=="2.13.0"
```

Add the one below(borrowed from [here](https://github.com/mlabonne/llm-course/blob/0b8d503703d68ddfbf9a50e308d5deb2e72655fc/Fine_tune_LLMs_with_Axolotl.ipynb))
```
!git clone -q https://github.com/OpenAccess-AI-Collective/axolotl
%cd axolotl
!pip install -qqq packaging huggingface_hub --progress-bar off
!pip install -qqq -e '.[flash-attn,deepspeed]' --progress-bar off
```

Also potentially setting `flash_attention` to `false` in the config. As further during the training I faced the error, `RuntimeError: FlashAttention only supports Ampere GPUs or newer.`

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/6a9cfec

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mhenrichsen** [comment]
Thanks for reporting.

@Klingefjord do you want to take a look?

**Comment by srib** [comment]
Potentially relevant issue? https://github.com/pytorch/pytorch/issues/48932

**Comment by srib** [comment]
This line seems to be the issue:
```bash
!pip install torch=="2.1.2"
```
It makes the version of `torchvision` to be incompatible with `torch`. 

Step 1:
```python
import torch
# Check so there is a gpu available, a T4(free tier) is enough to run this notebook
assert (torch.cuda.is_available()==True)
print(torch.__version__)
import torchvision
print(torchvision.__version__)
```
Output:
```bash
2.3.1+cu121
0.18.1+cu121
```
Step 2:
```python
!pip install torch=="2.1.2"
```
Step 3:
```python
import torch
# Check so there is a gpu available, a T4(free tier) is enough to run this notebook
assert (torch.cuda.is_available()==True)
print(torch.__version__)
import torchvision
print(torchvision.__version__)
```
```bash
2.1.2+cu121
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-1-b9da872c6886>](https://localhost:8080/#) in <cell line: 5>()
      3 assert (torch.cuda.is_available()==True)
      4 print(torch.__version__)
----> 5 import torchvision
      6 print(torchvision.__version__)
      7 #

5 frames
[/usr/local/lib/python3.10/dist-packages/torch/_custom_op/impl.py](https://localhost:8080/#) in error_not_found()
   1050 def get_op(qualname):
   1051     def error_not_found():
-> 1052         raise ValueError(
   1053             f"Could not find the operator {qualname}. Please make sure you have "
   1054             f"already registered the operator and (if registered from C++) "

ValueError: Could not find the operator torchvision::nms. Please make sure you have already registered the operator and (if registered from C++) loaded it via torch.ops.load_library.
```
