### ISSUE TITLE
unexpected keyword argument 'device_map'

### ISSUE THREAD

**Issue by mmealman** [axolotl-ai-cloud/axolotl#184]
Getting the below when trying to merge or run inference on a LoRA:

```python
Traceback (most recent call last):
  File "/home/mmealman/src/axolotl/scripts/finetune.py", line 301, in <module>
    fire.Fire(train)
  File "/home/mmealman/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mmealman/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mmealman/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/mmealman/src/axolotl/scripts/finetune.py", line 216, in train
    model, peft_config = load_model(
  File "/home/mmealman/src/axolotl/src/axolotl/utils/models.py", line 301, in load_model
    model, lora_config = load_adapter(model, cfg, adapter)
  File "/home/mmealman/src/axolotl/src/axolotl/utils/models.py", line 347, in load_adapter
    return load_lora(model, cfg)
  File "/home/mmealman/src/axolotl/src/axolotl/utils/models.py", line 428, in load_lora
    model = PeftModel.from_pretrained(
  File "/home/mmealman/miniconda3/envs/axolotl/lib/python3.10/site-packages/peft/peft_model.py", line 180, in from_pretrained
    PeftConfig.from_pretrained(model_id, subfolder=kwargs.get("subfolder", None), **kwargs).peft_type
  File "/home/mmealman/miniconda3/envs/axolotl/lib/python3.10/site-packages/peft/utils/config.py", line 114, in from_pretrained
    config = cls(**kwargs)
TypeError: PeftConfig.__init__() got an unexpected keyword argument 'device_map'
```

I'm wondering if the issue is related to this commit: https://github.com/huggingface/peft/commit/fcff23f005fc7bfb816ad1f55360442c170cd5f5

**Comment by mmealman** [comment]
Commenting out line 431 in utils/models.py seems to fix for inference/merging.

```python
    if cfg.lora_model_dir:
        model = PeftModel.from_pretrained(
            model,
            cfg.lora_model_dir,
            #device_map=cfg.device_map,
            # torch_dtype=torch.float16,
        )
    else:
        model = get_peft_model(model, lora_config)
```
