### ISSUE TITLE
Resume training from lora checkpoint error

### ISSUE THREAD

**Issue by Emm9625** [axolotl-ai-cloud/axolotl#198]
Hey everyone, i'm having trouble resuming training from a lora checkpoint
latest git commit on branch main as of 
2023-06-12T22:32:22+0000
here is my yaml config
```
base_model: ehartford/WizardLM-7B-Uncensored
base_model_config: ehartford/WizardLM-7B-Uncensored
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
load_in_8bit: true
datasets:
  - path: QingyiSi/Alpaca-CoT
    data_files:
      - Chain-of-Thought/formatted_cot_data/aqua_train.json
      # - Chain-of-Thought/formatted_cot_data/creak_train.json
      - Chain-of-Thought/formatted_cot_data/ecqa_train.json
      # - Chain-of-Thought/formatted_cot_data/esnli_train.json
      # - Chain-of-Thought/formatted_cot_data/gsm8k_train.json
      # - Chain-of-Thought/formatted_cot_data/qasc_train.json
      - Chain-of-Thought/formatted_cot_data/qed_train.json
      - Chain-of-Thought/formatted_cot_data/sensemaking_train.json
      - Chain-of-Thought/formatted_cot_data/strategyqa_train.json
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.02
sequence_len: 2048
max_packed_sequence_len: 2048

## Lora
adapter: lora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
lora_model_dir:
lora_fan_in_fan_out: false

## WANDB

wandb_mode:
wandb_project: WLM7b-CoT-1
wandb_run_id: test-run
wandb_log_model: checkpoint

##Hyper Params
gradient_accumulation_steps: 1
gradient_checkpointing: true
micro_batch_size: 2
# batch_size: 1
num_epochs: 2
optimizer: adamw_bnb_8bit
torchdistx_path:
lr_scheduler: cosine
learning_rate: 0.00003
train_on_inputs: false
group_by_length: false
bf16: true
fp16: true
tf32: true
output_dir: /notebooks/runs/7b-Cot/run-3/
## Early Stopping/saving
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoints: true
local_rank:
logging_steps: 5
xformers_attention:
flash_attention:
gptq_groupsize:
gptq_model_v1:
warmup_steps: 20
eval_steps: 110
save_steps: 1
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```
Here is my error
```
NFO:root:loading tokenizer... ehartford/WizardLM-7B-Uncensored
INFO:root:Loading prepared packed dataset from disk at last_run_prepared/3e0fbd00b767305ce66a92c2a3e20d34...
INFO:root:Prepared packed dataset loaded from disk...
INFO:root:loading model and peft_config...
WARNING:accelerate.utils.modeling:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
INFO:root:converting PEFT model w/ prepare_model_for_kbit_training
INFO:root:Using Auto-resume functionality to start with checkpoint at /notebooks/runs/7b-Cot/run-3/checkpoint-2
Traceback (most recent call last):
  File "/notebooks/axolotl/scripts/finetune.py", line 329, in <module>
    fire.Fire(train)
  File "/storage/py39-axolotl/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/storage/py39-axolotl/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/storage/py39-axolotl/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/notebooks/axolotl/scripts/finetune.py", line 316, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/storage/py39-axolotl/lib/python3.9/site-packages/transformers/trainer.py", line 1634, in train
    self._load_from_checkpoint(resume_from_checkpoint)
  File "/storage/py39-axolotl/lib/python3.9/site-packages/transformers/trainer.py", line 2128, in _load_from_checkpoint
    raise ValueError(f"Can't find a valid checkpoint at {resume_from_checkpoint}")
ValueError: Can't find a valid checkpoint at /notebooks/runs/7b-Cot/run-3/checkpoint-2
Traceback (most recent call last):
  File "/storage/py39-axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/storage/py39-axolotl/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/storage/py39-axolotl/lib/python3.9/site-packages/accelerate/commands/launch.py", line 941, in launch_command
    simple_launcher(args)
  File "/storage/py39-axolotl/lib/python3.9/site-packages/accelerate/commands/launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/storage/py39-axolotl/bin/python', 'scripts/finetune.py', '../7b-CoT/wlm-cot-run-1.yml']' returned non-zero exit status 1.
```

**Comment by NanoCode012** [comment]
For more information:

It would seem like peft (likely) or transformers updated their save logic. it does not save `pytorch_model.bin` now. 

![image](https://github.com/OpenAccess-AI-Collective/axolotl/assets/9899957/c619178d-a1f2-4886-b31b-a22190382d7b)

As of now, I'm trying to track where the change was.

It also cheekily added a "README.md" every folder now.

**Comment by NanoCode012** [comment]
Hey @Emm9625 , there's a PR to transformers to fix this. More info here https://github.com/huggingface/peft/issues/574#issuecomment-1592633606

**Comment by NanoCode012** [comment]
Hey @Emm9625 , could you try reinstall from source? Upstream branch has merged the fix. If it does not work, maybe you can leave a comment there?
