### ISSUE TITLE
custom prompt format (custom dataset) doesn't work

### ISSUE THREAD

**Issue by mindcrunch4u** [axolotl-ai-cloud/axolotl#2030]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Expected `accelerate` to train the model using a custom dataset: [AI_Storyteller_Dataset](https://huggingface.co/datasets/jaydenccc/AI_Storyteller_Dataset)

### Current behaviour

`accelerate` throws errors.

```
Traceback (most recent call last):
  File "/dataset/test/condaenv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dataset/test/condaenv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/dataset/test/axolotl/src/axolotl/cli/train.py", line 58, in <module>
    fire.Fire(do_cli)
  File "/dataset/test/condaenv/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dataset/test/condaenv/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/dataset/test/condaenv/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/dataset/test/axolotl/src/axolotl/cli/train.py", line 29, in do_cli
    parsed_cfg = load_cfg(config, **kwargs)
  File "/dataset/test/axolotl/src/axolotl/cli/__init__.py", line 425, in load_cfg
    cfg = validate_config(
  File "/dataset/test/axolotl/src/axolotl/utils/config/__init__.py", line 242, in validate_config
    AxolotlConfigWCapabilities(
  File "/dataset/test/condaenv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/dataset/test/axolotl/src/axolotl/utils/config/models/input/v0_4_1/__init__.py", line 792, in deprecate_sharegpt_datasets
    if ds_cfg["type"].startswith("sharegpt"):
```

### Steps to reproduce

Step 1: Install Axolotl

```
conda create python=3.10  --prefix ./condaenv
conda conda activate condaenv

git clone https://github.com/axolotl-ai-cloud/axolotl
cd axolotl
pip3 install packaging ninja
pip3 install -e '.[flash-attn,deepspeed]'
```

Step 2: Create the `yaml` file provided below as `basic_train.yml`

Step 3: Start training

```
ccelerate launch -m axolotl.cli.train basic_train.yml
```

### Config yaml

```yaml
base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
batch_size: 4
bf16: auto
datasets:
- path: jaydenccc/AI_Storyteller_Dataset
  type:
    field_instruction: synopsis
    field_output: short_story
    field_system: system
    format: <|user|> {instruction} </s> <|assistant|>
    no_input_format: <|user|> {instruction} </s> <|assistant|>
    system_prompt: ''
learning_rate: 0.0002
logging_steps: 1
micro_batch_size: 4
model_type: LlamaForCausalLM
num_epochs: 2
optimizer: adamw_bnb_8bit
output_dir: ./models/TinyLlama_Storyteller
sequence_length: 1024
tf32: false
tokenizer_type: LlamaTokenizer
```

### Possible solution

I commented out the `type` check in `axolotl/src/axolotl/utils/config/models/input/v0_4_1/__init__.py`, function name `deprecate_sharegpt_datasets`. I commented out the snippet below:

```
            if ds_cfg["type"].startswith("sharegpt"):
                raise ValueError(
                    "`type: sharegpt.*` is deprecated. Please use `type: chat_template` instead."
                )
```

Because with my custom dataset, the value of `ds_cfg["type"]` is:

```
{'path': 'jaydenccc/AI_Storyteller_Dataset', 'type': {'field_instruction': 'synopsis', 'field_output': 'short_story', 'field_system': 'system', 'format': '<|user|> {instruction} </s> <|assistant|>', 'no_input_format': '<|user|> {instruction} </s> <|assistant|>', 'system_prompt': ''}}
```

But then `accelerate` throws another error:

```
Traceback (most recent call last):
  File "/dataset/test/condaenv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dataset/test/condaenv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/dataset/test/axolotl/src/axolotl/cli/train.py", line 58, in <module>
    fire.Fire(do_cli)
  File "/dataset/test/condaenv/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dataset/test/condaenv/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/dataset/test/condaenv/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/dataset/test/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/dataset/test/axolotl/src/axolotl/cli/train.py", line 45, in do_train
    dataset_meta = load_datasets(cfg=cfg, cli_args=cli_args)
  File "/dataset/test/axolotl/src/axolotl/cli/__init__.py", line 459, in load_datasets
    train_dataset, eval_dataset, total_num_steps, prompters = prepare_dataset(
  File "/dataset/test/axolotl/src/axolotl/utils/data/sft.py", line 64, in wrapper
    return func(*args, **kwargs)
  File "/dataset/test/axolotl/src/axolotl/utils/data/sft.py", line 100, in prepare_dataset
    train_dataset, eval_dataset, prompters = load_prepare_datasets(
  File "/dataset/test/axolotl/src/axolotl/utils/data/sft.py", line 532, in load_prepare_datasets
    dataset, prompters = load_tokenized_prepared_datasets(
  File "/dataset/test/axolotl/src/axolotl/utils/data/sft.py", line 426, in load_tokenized_prepared_datasets
    raise ValueError(
ValueError: data_files must be either a string or list of strings
Traceback (most recent call last):
  File "/dataset/test/condaenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/dataset/test/condaenv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/dataset/test/condaenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/dataset/test/condaenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/dataset/test/condaenv/bin/python', '-m', 'axolotl.cli.train', 'basic_train.yml']' returned non-zero exit status 1.
```

Debugging the function `load_tokenized_prepared_datasets` in `axolotl/src/axolotl/utils/data/sft.py` tells me that the value of `config_dataset.data_files` is `None`.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.15

### axolotl branch-commit

main/d356740

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, thanks for the quick bug report. I missed the condition for custom datasets. I'll make a quick PR for that.

For the second issue, it occurs at the end of our data check, so it usually means a config issue. Will check in detail at this after the PR.

**Comment by NanoCode012** [comment]
I made the PR for your first issue. Are you able to try run `python -m axolotl.cli.preprocess path/to/file.yaml --debug` to see if both problem still occurs?

I ran your dataset config locally for preprocess (not training) without issue.

**Comment by mindcrunch4u** [comment]
Thank you, axolotl no longer throws earlier errors. This issue is resolved.

**Comment by wanderingweights** [comment]
Can the latest docker on the hub be updated with this  fix please.

**Comment by NanoCode012** [comment]
Yes, we will merge the PR once the CI is done.

**Comment by NanoCode012** [comment]
I merged the linked PR. Please give some time for images to build and try it out.
