### ISSUE TITLE
`RuntimeError: CUDA error: unknown error` When attempting to fine-tune llama-3 models

### ISSUE THREAD

**Issue by cjfreeze** [axolotl-ai-cloud/axolotl#2071]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Training proceeds as expected when running command:
`accelerate launch -m axolotl.cli.train examples/llama-3/lora-8b.yml`
or
`accelerate launch -m axolotl.cli.train examples/llama-3/qlora-1b.yml`

### Current behaviour

Training fails at the very beginning with error message:
```bash
[2024-11-17 14:50:47,989] [INFO] [axolotl.utils.samplers.multipack.calc_min_len:197] [PID:725937] [RANK:0] gather_len_batches: [43]
  0%|                                                                                                       | 0/40 [00:00<?, ?it/s]You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/home/chris/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:316: UserWarning: MatMul8bitLt: inputs will be cast from torch.bfloat16 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chris/axolotl/src/axolotl/cli/train.py", line 58, in <module>
    fire.Fire(do_cli)
  File "/home/chris/.local/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/chris/.local/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/chris/.local/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/chris/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/home/chris/axolotl/src/axolotl/cli/train.py", line 47, in do_train
    model, tokenizer = train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/home/chris/axolotl/src/axolotl/train.py", line 192, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2122, in train
    return inner_training_loop(
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3572, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/home/chris/axolotl/src/axolotl/core/trainer_builder.py", line 686, in compute_loss
    return super().compute_loss(
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3625, in compute_loss
    outputs = model(**inputs)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/accelerate/utils/operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/chris/.local/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/peft/peft_model.py", line 1644, in forward
    return self.base_model(
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 197, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1214, in forward
    loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **loss_kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/loss/loss_utils.py", line 46, in ForCausalLMLoss
    loss = fixed_cross_entropy(shift_logits, shift_labels, num_items_in_batch, ignore_index, **kwargs)
  File "/home/chris/.local/lib/python3.10/site-packages/transformers/loss/loss_utils.py", line 26, in fixed_cross_entropy
    loss = nn.functional.cross_entropy(source, target, ignore_index=ignore_index, reduction=reduction)
  File "/home/chris/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 3479, in cross_entropy
    return torch._C._nn.cross_entropy_loss(
RuntimeError: CUDA error: unknown error
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  0%|                                                                                                       | 0/40 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/chris/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/chris/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/chris/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/chris/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', 'examples/llama-3/lora-8b.yml']' returned non-zero exit status 1.
```

### Steps to reproduce

Environment | Version/Model
--- | ---
WSL | 2
Ubuntu | 22.04
CUDA | 12.4
Pytorch | 2.5.1
GPU | GTX 4090
1. Clone latest axolotl and run setup
2. `python -m axolotl.cli.preprocess examples/llama-3/lora-8b.yml`
3. `accelerate launch -m axolotl.cli.train examples/llama-3/lora-8b.yml`

Error seems to happen regardless of combination of pytorch version, axolotl version, and cuda version.
Error does not happen when following a llama-2 lora example.

### Config yaml

```yaml
base_model: NousResearch/Meta-Llama-3-8B
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: mhenrichsen/alpaca_2k_test
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/lora-out

sequence_len: 4096
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_modules_to_save:
  - embed_tokens
  - lm_head

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
s2_attention:

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
   pad_token: <|end_of_text|>
```

### Possible solution

I haven't tried compiling pytorch from source yet with `TORCH_USE_CUDA_DSA`, but may have to? I would prefer if that were not the case.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [X] Windows

### Python Version

3.10.12

### axolotl branch-commit

main/0c8b1d82

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hey, I can't seem to replicate this with `examples/llama-3/qlora-1b.yml` with 4090 py311 torch251 cu124. The training runs fine.

The lora-8b though gave me OOM, instead of your CUDA issue. Reducing seq_len would allow me to run it fine.

Are you running it locally or via docker?

**Comment by cjfreeze** [comment]
> Hey, I can't seem to replicate this with `examples/llama-3/qlora-1b.yml` with 4090 py311 torch251 cu124. The training runs fine.
> 
> The lora-8b though gave me OOM, instead of your CUDA issue. Reducing seq_len would allow me to run it fine. 
> 
> Are you running it locally or via docker?

Locally, in a WSL environment. Given your experience, I suspect WSL might be at fault here. I will be retrying shortly on the exact same hardware but in a fresh ubuntu install to see what happens.

**Comment by bursteratom** [comment]
Hi @cjfreeze wondering how your retry is turning out?
