### ISSUE TITLE
I got this error MPT-7b

### ISSUE THREAD

**Issue by Minniesse** [axolotl-ai-cloud/axolotl#282]
I want to finetune mpt-7b and I got this error

INFO:root:Starting trainer...
  0%|                                                                                                                                                      | 0/19113 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/minnie/Desktop/axolotl/scripts/finetune.py", line 354, in <module>
    fire.Fire(train)
  File "/home/minnie/venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/minnie/venv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/minnie/venv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/minnie/Desktop/axolotl/scripts/finetune.py", line 339, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/minnie/venv/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/minnie/venv/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/minnie/venv/lib/python3.10/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/minnie/venv/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minnie/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/minnie/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-chat/c53dee01e05098f81cac11145f9bf45feedc5b2f/modeling_mpt.py", line 271, in forward
    logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
  File "/home/minnie/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Embedding.forward() takes 2 positional arguments but 3 were given

**Comment by ashercn97** [comment]
I got a similar error I think.

**Comment by NanoCode012** [comment]
I recall this error. When using non-foundry (in this case huggingface trainer) with mpt, you would need to fix their model code. To this date, unfortunately, I don't know who should handle this, whether to recommend using foundry instead or have a mpt patch.

**Comment by Minniesse** [comment]
Thank you very much !

**Comment by jsancs** [comment]
Any solution in this time to use it with the HF trainer?
