### ISSUE TITLE
Apple Silicon working Example

### ISSUE THREAD

**Issue by madhavajay** [axolotl-ai-cloud/axolotl#295]
Can you provide any example that works on Apple Silicon?

I ran into several problems, the first one is a bug in `transformers` which results in `device("cpu")` which then throws an Exception.
https://github.com/huggingface/transformers/pull/24907

However after fixing that and fiddling with different precision flags and disabling the `bitesandbytes` optimizer I always hit an error on the first backprop.

```
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

```

The same issue happens on a variety of the examples.

Full log:
[2023-07-19 17:03:16,960] [INFO] [axolotl.scripts.train:294] [PID:64587] Compiling torch model
[2023-07-19 17:03:17,037] [INFO] [axolotl.scripts.train:299] [PID:64587] Pre-saving adapter config to ./lora-alpaca-pythia
[2023-07-19 17:03:17,038] [INFO] [axolotl.scripts.train:315] [PID:64587] Starting trainer...
/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|                                                 | 0/38880 [00:00<?, ?it/s]You're using a GPTNeoXTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
{'loss': 1.9369, 'learning_rate': 1.0000000000000001e-07, 'epoch': 0.0}         
  0%|                                      | 1/38880 [00:01<19:00:23,  1.76s/it]Traceback (most recent call last):
  File "/Users/madhavajay/dev/axolotl/scripts/finetune.py", line 356, in <module>
    fire.Fire(train)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/madhavajay/dev/axolotl/scripts/finetune.py", line 341, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/transformers/trainer.py", line 1526, in train
    return inner_training_loop(
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/transformers/trainer.py", line 1796, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/transformers/trainer.py", line 2652, in training_step
    self.accelerator.backward(loss)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/accelerate/accelerator.py", line 1902, in backward
    loss.backward(**kwargs)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
  0%|                                      | 1/38880 [00:02<29:23:31,  2.72s/it]
Traceback (most recent call last):
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/madhavajay/.local/share/virtualenvs/axolotl-Fk-E_Akr/bin/python', 'scripts/finetune.py', 'examples/pythia/lora.yml']' returned non-zero exit status 1.

**Comment by NanoCode012** [comment]
Hello @madhavajay , I usually train on GPUs and not apple silicon like many here. So, it may take a while before someone comes here with an answer. I would recommend checking cloud providers like Colab or Kaggle who provides free GPU in the meantime.

**Comment by madhavajay** [comment]
@NanoCode012 I appreciate that. I figured since the code goes out of its way to support `mps` that someone ran it at some point and it worked?

**Comment by NanoCode012** [comment]
Sorry for late reply. I'm not sure on this part as well. It could just be legacy code.

**Comment by tmm1** [comment]
pytorch MPS is heavily wip, and without equivalents of CUDA optimizations like flash attention it is not really viable to use a mac with pytorch inference or training yet.

that said, it should run and i had some limited success in the past [with other frameworks](https://github.com/h2oai/h2o-llmstudio/pull/210/files)

you could try with latest pytorch-nightly and [these changes](https://github.com/OpenAccess-AI-Collective/axolotl/compare/main...tmm1:axolotl:mps), but you will likely continue to hit random bugs and even when you fix those the end result will be quite slow and crashy

**Comment by NanoCode012** [comment]
I will close this since it's been a while, and I would recommend linux platforms + nvidia gpus as of now.
