### ISSUE TITLE
[Bug] IndexError: list index out of range in falcon config

### ISSUE THREAD

**Issue by NanoCode012** [axolotl-ai-cloud/axolotl#314]
I received this while testing the falcon config.

Reproduce:

`accelerate launch scripts/finetune.py examples/falcon/config-7b.yml`

Fix:

```diff
datasets:
  - path: teknium/GPT4-LLM-Cleaned
    type: alpaca:chat
+    data_files:  alpaca_gpt4_data_unfiltered.json
```

There is some issue with the [unnatural_instructions_unfiltered.json](https://huggingface.co/datasets/teknium/GPT4-LLM-Cleaned/blob/main/unnatural_instructions_unfiltered.json) file that is causing the conflict.

**Comment by Calandiel** [comment]
Same thing with the Pythia configs

**Comment by winglian** [comment]
@NanoCode012 can you provide a stack trace for me please?

**Comment by NanoCode012** [comment]
@winglian . Issue was first reported in #229 

```bash
accelerate launch scripts/finetune.py examples/falcon/config-7b.yml
```

```bash
[2023-08-12 16:19:54,515] [INFO] [axolotl.load_tokenized_prepared_datasets:265] [PID:2981652] tokenizing, merging, and shuffling master dataset
Map (num_proc=48):  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 53749/54568 [00:03<00:00, 16567.68 examples/s]
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1347, in _write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/root/axolotl-test/src/axolotl/prompt_tokenizers.py", line 122, in tokenize_prompt
    tokenized_res_prompt = self._tokenize(
  File "/root/axolotl-test/src/axolotl/prompt_tokenizers.py", line 78, in _tokenize
    result["input_ids"][-1] != self.tokenizer.eos_token_id
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/axolotl-test/scripts/finetune.py", line 354, in <module>
    fire.Fire(train)
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/axolotl-test/scripts/finetune.py", line 227, in train
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/root/axolotl-test/src/axolotl/utils/data.py", line 402, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/root/axolotl-test/src/axolotl/utils/data.py", line 270, in load_tokenized_prepared_datasets
    d_iter = iter(d)
  File "/root/axolotl-test/src/axolotl/datasets.py", line 41, in __iter__
    self.dataset.map(
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3189, in map
    for rank, done, content in iflatmap_unordered(
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1387, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1387, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/root/mambaforge/envs/test/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
IndexError: list index out of range
```

Could it be that there is empty row in dataset?

**Comment by NanoCode012** [comment]
This is due to an empty output inside the dataset. We have reached out to the author for the fix.
