### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [axolotl-ai-cloud/axolotl#346]
Hello everyone.

I'm trying to train LoRA by using this [model](https://huggingface.co/TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ)

I've downloaded this model at directory and placed my training files. My config looks like this:

```yaml
base_model: /root/TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ
base_model_config: /root/TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

gptq: true
gptq_groupsize: 128 # group size
gptq_model_v1: false # v1 or v2

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: json
    data_files: /root/lines.jsonl
    type: completion
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: /root/my_lora

sequence_len: 4096
max_packed_sequence_len: 4096

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: true
flash_attention:

warmup_steps: 10
eval_steps: 20
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
  pad_token: "<pad>"

```

When I launched it with command

    accelerate launch scripts/finetune.py /root/lora.yml

It returned this error:

```
Traceback (most recent call last):
  File "/root/axolotl/scripts/finetune.py", line 358, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/axolotl/scripts/finetune.py", line 255, in train
    model, peft_config = load_model(
  File "/root/axolotl/src/axolotl/utils/models.py", line 300, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2509, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ.

Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'scripts/finetune.py', '/root/lora.yml']' returned non-zero exit status 1.
```
It tries to find `pytorch_model.bin, tf_model.h5, model.ckpt.index` files, while this model has safetensors. What I'm doing wrong? I thought that this project supports safetensors.

**Comment by missEldgard** [comment]
I have tried the same just now with the same error. When there is GPTQ support, maybe it is only for the export and not as an input model ?

**Comment by SuperMasterBlasterLaser** [comment]
@missEldgard Well. According to [this](https://github.com/OpenAccess-AI-Collective/axolotl#axolotl-supports) it should support gptq

**Comment by winglian** [comment]
@SuperMasterBlasterLaser try adding `is_llama_derived_model: true` to the config please and see if it gets any further.

**Comment by SuperMasterBlasterLaser** [comment]
@winglian Added `is_llama_derived_model: true` and it still throws this error:

```
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ.
```

I have installed axolotl with this command:

    pip3 install -e .[gptq]

**Comment by NanoCode012** [comment]
I think this is a transformers issue. Which version of transformers are you on? That model only saves as `safetensors` where loading it was only added later.

Edit: Make sure you install `safetensors`

**Comment by SuperMasterBlasterLaser** [comment]
@NanoCode012 I just cloned this repo and installed with command

    pip3 install -e .[gptq]

Which should pick default transformes that was written in `requirements.txt`

**Comment by NanoCode012** [comment]
Could you also install safetensors? @SuperMasterBlasterLaser

**Comment by SuperMasterBlasterLaser** [comment]
@NanoCode012 It is already installed. When I run:

    pip show safetensors

It returns to me:
```
Name: safetensors
Version: 0.3.2
Summary: Fast and Safe Tensor serialization
Home-page: https://github.com/huggingface/safetensors
```

While launching it still returns this error:

```
OSError: TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/axolotl/scripts/finetune.py", line 354, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/axolotl/scripts/finetune.py", line 258, in train
    model, peft_config = load_model(cfg, tokenizer)
  File "/root/axolotl/src/axolotl/utils/models.py", line 304, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 516, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    raise EnvironmentError(
OSError: TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'scripts/finetune.py', '/root/lora.yml']' returned non-zero exit status 1.
```

**Comment by NanoCode012** [comment]
@SuperMasterBlasterLaser , please set 

```
model_type: LlamaForCausalLM
```

One thing to note: make sure you checkout the right branch. `model_revision` code is not working with gptq right now. Making PR on this.

@winglian , it would seem that we cannot manually set `is_llama_derived_model` as it's overwritten in the code.

**Comment by SuperMasterBlasterLaser** [comment]
@NanoCode012 I quite don't understand. You mean that when I install as

    pip3 install -e .[gptq]

I need to set this?

    model_type: LlamaForCausalLM

Is it even possible to make LoRAs from GPTQ models?

**Comment by NanoCode012** [comment]
@SuperMasterBlasterLaser , sorry for my unclear instructions. I mean, could you please change your config for `model_type` to the following then try finetune?

We do a check that only llama model can do gptq.

**Comment by SuperMasterBlasterLaser** [comment]
@NanoCode012 

I will recheck as you suggested tomorrow, when I get into my PC.

**Comment by SuperMasterBlasterLaser** [comment]
@NanoCode012 

I've tried what you suggested.

I have installed axolotl like this:

    pip3 install -e .[gptq]
    pip3 install -U git+https://github.com/huggingface/peft.git

I made configs like this:

```yaml
base_model: TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ
base_model_config: TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true
```

It failed and returned this error:

```
Traceback (most recent call last):
  File "/root/axolotl/scripts/finetune.py", line 315, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/axolotl/scripts/finetune.py", line 212, in train
    model, peft_config = load_model(cfg, tokenizer)
  File "/root/axolotl/src/axolotl/utils/models.py", line 320, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 535, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2817, in from_pretrained
    raise EnvironmentError(
OSError: TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
```

It also returned these error messages:

```
size mismatch for model.layers.79.mlp.gate_proj.scales: copying a param with shape torch.Size([1, 28672]) from checkpoint, the shape in current model is torch.Size([64, 28672]).
size mismatch for model.layers.79.mlp.up_proj.qzeros: copying a param with shape torch.Size([1, 3584]) from checkpoint, the shape in current model is torch.Size([64, 3584]).
size mismatch for model.layers.79.mlp.up_proj.scales: copying a param with shape torch.Size([1, 28672]) from checkpoint, the shape in current model is torch.Size([64, 28672]).
size mismatch for model.layers.79.mlp.down_proj.qzeros: copying a param with shape torch.Size([1, 1024]) from checkpoint, the shape in current model is torch.Size([224, 1024]).
size mismatch for model.layers.79.mlp.down_proj.scales: copying a param with shape torch.Size([1, 8192]) from checkpoint, the shape in current model is torch.Size([224, 8192]).
```

**Comment by NanoCode012** [comment]
Please do not run this line: `pip3 install -U git+https://github.com/huggingface/peft.git`

**Comment by SuperMasterBlasterLaser** [comment]
@NanoCode012 

Ok. I've recreated container again. Had run only:

    pip3 install -e .[gptq]

Then launched training and it still returned:

```
no sessions
 is torch.Size([224, 8192]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/axolotl/scripts/finetune.py", line 315, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/axolotl/scripts/finetune.py", line 212, in train
    model, peft_config = load_model(cfg, tokenizer)
  File "/root/axolotl/src/axolotl/utils/models.py", line 320, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 535, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2817, in from_pretrained
    raise EnvironmentError(
OSError: TheBloke/airoboros-l2-70B-GPT4-2.0-GPTQ does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
```

**Comment by winglian** [comment]
now that the new GPTQ support has been added, this is probably no longer an issue
