### ISSUE TITLE
TypeError: Trainer._get_eval_sampler() missing 1 required positional argument: 'eval_dataset'

### ISSUE THREAD

**Issue by dongxiaolong** [axolotl-ai-cloud/axolotl#457]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

successfully eval dataset

### Current behaviour

[2023-08-22 09:58:47,953] [INFO] [axolotl.callbacks.on_step_end:94] [PID:43130] GPU memory usage while training: 7.925GB (+43.991GB cache, +2.995GB misc)
{'loss': 6.8022, 'learning_rate': 4e-05, 'epoch': 0.0}
{'loss': 7.8583, 'learning_rate': 6e-05, 'epoch': 0.0}
{'loss': 7.5605, 'learning_rate': 8e-05, 'epoch': 0.0}
{'loss': 8.1386, 'learning_rate': 0.0001, 'epoch': 0.0}
{'loss': 5.7006, 'learning_rate': 0.00012, 'epoch': 0.0}
{'loss': 5.5, 'learning_rate': 0.00014, 'epoch': 0.0}
{'loss': 6.3369, 'learning_rate': 0.00016, 'epoch': 0.0}
{'loss': 5.7842, 'learning_rate': 0.00018, 'epoch': 0.0}
{'loss': 6.794, 'learning_rate': 0.0002, 'epoch': 0.0}
  0%|                                                                                                      | 10/86721 [03:13<466:29:44, 19.37s/it]Traceback (most recent call last):
  File "/root/dxl/axolotl/scripts/finetune.py", line 315, in <module>
    fire.Fire(train)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/dxl/axolotl/scripts/finetune.py", line 300, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 2256, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 2968, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/root/dxl/axolotl/src/axolotl/utils/trainer.py", line 214, in get_eval_dataloader
    eval_sampler = self._get_eval_sampler(eval_dataset)
  File "/root/dxl/axolotl/src/axolotl/utils/trainer.py", line 187, in _get_eval_sampler
    return super()._get_eval_sampler(eval_dataset)
TypeError: Trainer._get_eval_sampler() missing 1 required positional argument: 'eval_dataset'

### Steps to reproduce

1.change llama2/qlora.yaml to

***
base_model: /root/autodl-tmp/models/vicuna-sharegpt_zh_platypus_puffin_main/
base_model_config: /root/autodl-tmp/models/vicuna-sharegpt_zh_platypus_puffin_main/
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /root/autodl-tmp/models/one_M-GPT4-Augmented.parquet
    type: alpaca_w_system.load_open_orca
    ds_type: parquet
dataset_prepared_path: /root/autodl-tmp/models/last_run_prepared
val_set_size: 0.02

output_dir: /root/autodl-tmp/models/vicuna-sharegpt_zh_platypus_puffin_orca_main

adapter: qlora
lora_model_dir:
lora_out_dir: /root/autodl-tmp/models/vicuna-sharegpt_zh_platypus_puffin_orca

sequence_len: 4096
sample_packing: true

lora_r: 32
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_mode: disabled
wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002
save_steps: 1000
save_total_limit: 2

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 10
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
  pad_token: "<unk>"

3. python scripts/finetune.py   examples/llama-2/qlora.yaml

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by dongxiaolong** [comment]
it’s already fixed in the latest version 
add eval_dataset in the trainer, 
```
File "axolotl/src/axolotl/utils/trainer.py", line 187, in _get_eval_sampler
'''
    return super()._get_eval_sampler()
```

```python
return super()._get_eval_sampler(eval_dataset)
```

ensure `eval_dataset` to Trainer._get_eval_sampler()` method.
