### ISSUE TITLE
UnboundLocalError: local variable 'tokens' referenced before assignment

### ISSUE THREAD

**Issue by radekosmulski** [axolotl-ai-cloud/axolotl#474]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I am able to train with qlora.

### Current behaviour

I use the official docker container (`winglian/axolotl:main-py3.10-cu118-2.0.1`)

Here is the `yml` file I use:

```
base_model: meta-llama/Llama-2-7b-hf
base_model_config: meta-llama/Llama-2-7b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.04
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

I get the following error:

```
Map (num_proc=24):  64%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                                             | 33416/52002 [00:02<00:01, 11257.98 examples/s]                                         [0/464]multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1347, in _write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/workspace/axolotl/src/axolotl/prompt_tokenizers.py", line 129, in tokenize_prompt
    tokenized_res_prompt = self._tokenize(
  File "/workspace/axolotl/src/axolotl/prompt_tokenizers.py", line 70, in _tokenize
    result = self.tokenizer(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2602, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2708, in _call_one
    return self.encode_plus(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2781, in encode_plus
    return self._encode_plus(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 656, in _encode_plus
    first_ids = get_input_ids(text)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 623, in get_input_ids
    tokens = self.tokenize(text, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/axolotl/scripts/finetune.py", line 324, in <module>
    fire.Fire(train)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/scripts/finetune.py", line 195, in train
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 57, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 460, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 239, in load_tokenized_prepared_datasets
    ds_wrapper = TokenizedPromptDataset(ds_strategy, ds)
  File "/workspace/axolotl/src/axolotl/datasets.py", line 36, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/workspace/axolotl/src/axolotl/datasets.py", line 41, in process
    return dataset.map(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3189, in map
    for rank, done, content in iflatmap_unordered(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1387, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1387, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
UnboundLocalError: local variable 'tokens' referenced before assignment
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/py3.10/bin/python', 'axolotl/scripts/finetune.py', 'axolotl/examples/llama-2/qlora.yml']' returned non-zero exit status 1.
```

### Steps to reproduce

Start a run in the official container with the above yml.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

the one in the official docker container

### axolotl branch-commit

whichever is in the official container

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jsancs** [comment]
Same error

**Comment by Napuh** [comment]
Same error with Llama2 and QLoRa outside of docker

**Comment by Alssndr0** [comment]
It seems an issue with the latest version of Transformers. This fixed it for me: 

```
pip install transformers==4.31.00 
```

**Comment by Napuh** [comment]
Yes. That worked. Thank you so much.
