### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tokenize_prompt' when using custom prompt

### ISSUE THREAD

**Issue by Napuh** [axolotl-ai-cloud/axolotl#497]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Trying to implement Alpaca Prompt Style but in spanish through the YAML config. When trying to setup a custom prompt in the YAML config file like this:

```yaml
datasets:
  - path: custom.json
    type:
      system_prompt: |
        Abajo está una instrucción que describe una tarea, en conjunto con una entrada que entrega más contexto. Escribe una respuesta que complete adecuadamente lo pedido.

      system_no_input_prompt: |
        Abajo está una instrucción que describe una tarea. Escribe una respuesta que complete adecuadamente lo pedido.

      no_input_format: |
        ###Instrucción:
        {instruction}
        ###Respuesta:

      format: |
        ###Instrucción:
        {instruction}
        ###Entrada:
        {input}
        ###Respuesta:
```

Finetuning script should execute and run as usual, using the specified prompt.

### Current behaviour

When executing the finetune script (`accelerate launch scripts/finetune.py custom_config.yaml`), it throws the following error:
 
```
[2023-08-28 08:27:14,045] [INFO] [axolotl.load_tokenized_prepared_datasets:128] [PID:2189] Loading raw datasets...
[2023-08-28 08:27:14,045] [INFO] [axolotl.load_tokenized_prepared_datasets:133] [PID:2189] No seed provided, using default seed of 42
/opt/conda/lib/python3.10/site-packages/datasets/load.py:2072: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=None' instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/axolotl/scripts/finetune.py", line 326, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/axolotl/scripts/finetune.py", line 197, in train
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/home/axolotl/src/axolotl/utils/data.py", line 58, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/axolotl/src/axolotl/utils/data.py", line 461, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/home/axolotl/src/axolotl/utils/data.py", line 228, in load_tokenized_prepared_datasets
    ds_wrapper = TokenizedPromptDataset(ds_strategy, ds)
  File "/home/axolotl/src/axolotl/datasets.py", line 36, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/home/axolotl/src/axolotl/datasets.py", line 42, in process
    self.prompt_tokenizer.tokenize_prompt,
AttributeError: 'NoneType' object has no attribute 'tokenize_prompt'
```

### Steps to reproduce

Change the dataset section in any YAML configuration file with the following fields:
- system_prompt
- system_no_input_prompt
- no_input_format
- format

Add a valid dataset (with `instruction`, `input` and `output`) in the YAML config file.

Then, execute the finetuning script.

### Possible solution

When removing `system_no_input_prompt` and `no_input_format` sections, the script won't throw an error.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Could you also add

```
ds_type: json
```

to that block?

Regarding your Possible Solution, could you try run it with `--debug --prepare_ds_only` to see if the output is as expected?

**Comment by Napuh** [comment]
`ds_type: json` doesn't make the error dissapear.

Executing with 'debug' does not provide much new information:

```
[2023-08-29 06:30:18,469] [INFO] [axolotl.normalize_config:72] [PID:1235] GPU memory usage baseline: 0.000GB (+0.344GB misc)
[2023-08-29 06:30:18,469] [INFO] [axolotl.scripts.train:191] [PID:1235] loading tokenizer... [model]
Downloading tokenizer.model: 100%|███████████████████████████████████████████████████| 500k/500k [00:00<00:00, 8.05MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████| 414/414 [00:00<00:00, 5.89MB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 725/725 [00:00<00:00, 10.6MB/s]
[2023-08-29 06:30:18,959] [DEBUG] [axolotl.load_tokenizer:70] [PID:1235] EOS: 2 / </s>
[2023-08-29 06:30:18,959] [DEBUG] [axolotl.load_tokenizer:71] [PID:1235] BOS: 1 / <s>
[2023-08-29 06:30:18,959] [DEBUG] [axolotl.load_tokenizer:72] [PID:1235] PAD: 2 / </s>
[2023-08-29 06:30:18,959] [DEBUG] [axolotl.load_tokenizer:73] [PID:1235] UNK: 0 / <unk>
[2023-08-29 06:30:18,959] [INFO] [axolotl.load_tokenized_prepared_datasets:127] [PID:1235] Unable to find prepared dataset in last_run_prepared/4681f9c4607f8e3f7d406ed5c55b4c6a
[2023-08-29 06:30:18,959] [INFO] [axolotl.load_tokenized_prepared_datasets:128] [PID:1235] Loading raw datasets...
[2023-08-29 06:30:18,959] [INFO] [axolotl.load_tokenized_prepared_datasets:133] [PID:1235] No seed provided, using default seed of 42
/opt/conda/lib/python3.10/site-packages/datasets/load.py:2072: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=None' instead.
  warnings.warn(
Downloading data files: 100%|██████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12052.60it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1543.73it/s]
Generating train split: 437 examples [00:00, 21505.97 examples/s]
Traceback (most recent call last):
  File "/home/axolotl/scripts/finetune.py", line 326, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/axolotl/scripts/finetune.py", line 197, in train
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/home/axolotl/src/axolotl/utils/data.py", line 58, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/axolotl/src/axolotl/utils/data.py", line 461, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/home/axolotl/src/axolotl/utils/data.py", line 228, in load_tokenized_prepared_datasets
    ds_wrapper = TokenizedPromptDataset(ds_strategy, ds)
  File "/home/axolotl/src/axolotl/datasets.py", line 36, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/home/axolotl/src/axolotl/datasets.py", line 42, in process
    self.prompt_tokenizer.tokenize_prompt,
AttributeError: 'NoneType' object has no attribute 'tokenize_prompt'
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'scripts/finetune.py', 'lora_config.yaml', '--debug', '--prepare_ds_only']' returned non-zero exit status 1
```

I've narrowed down the problem to be on the `system_no_input_prompt` section. I've included this because I was it on the prompters.py file, but seems that it does not work on the user specified format.

**Comment by NanoCode012** [comment]
Could you try remove those configs as you've done and apply `--debug --prepare_ds_only`? Are the outputs as expected?

**Comment by Napuh** [comment]
This is the output (i reduced the token outputs)

````
[2023-08-30 07:34:56,049] [INFO] [axolotl.normalize_config:72] [PID:2251] GPU memory usage baseline: 0.000GB (+0.362GB misc)[39m
[2023-08-30 07:34:56,051] [INFO] [axolotl.scripts.train:185] [PID:2251] loading tokenizer... meta-llama/Llama-2-7b-hf[39m
[2023-08-30 07:34:56,216] [DEBUG] [axolotl.load_tokenizer:75] [PID:2251] EOS: 2 / </s>[39m
[2023-08-30 07:34:56,216] [DEBUG] [axolotl.load_tokenizer:76] [PID:2251] BOS: 1 / <s>[39m
[2023-08-30 07:34:56,216] [DEBUG] [axolotl.load_tokenizer:77] [PID:2251] PAD: 2 / </s>[39m
[2023-08-30 07:34:56,216] [DEBUG] [axolotl.load_tokenizer:78] [PID:2251] UNK: 0 / <unk>[39m
[2023-08-30 07:34:56,216] [INFO] [axolotl.load_tokenized_prepared_datasets:123] [PID:2251] Loading prepared dataset from disk at last_run_prepared/99b4fe2df44ee843b61e1c7dfa995367...[39m
[2023-08-30 07:34:56,218] [INFO] [axolotl.load_tokenized_prepared_datasets:125] [PID:2251] Prepared dataset loaded from disk...[39m
[2023-08-30 07:34:56,951] [INFO] [axolotl.calculate_total_num_steps:458] [PID:2251] total_num_steps: 377[39m
[2023-08-30 07:34:56,951] [INFO] [axolotl.scripts.train:194] [PID:2251] check_dataset_labels...[39m
[2023-08-30 07:34:56,992] [INFO] [axolotl.check_example_labels:37] [PID:2251] <s>(-100, 1, 1) ... </s>(2, 1, 2)
[2023-08-30 07:34:56,992] [INFO] [axolotl.check_example_labels:38] [PID:2251] 


[39m
[2023-08-30 07:34:57,091] [INFO] [axolotl.check_example_labels:37] [PID:2251] <s>(-100, 1, 1) ... </s>(2, 1, 2)[39m
[2023-08-30 07:34:57,091] [INFO] [axolotl.check_example_labels:38] [PID:2251] 


[39m
[2023-08-30 07:34:57,161] [INFO] [axolotl.check_example_labels:37] [PID:2251] <s>(-100, 1, 1) ... </s>(2, 1, 2)[39m
[2023-08-30 07:34:57,161] [INFO] [axolotl.check_example_labels:38] [PID:2251] 


[39m
[2023-08-30 07:34:57,196] [INFO] [axolotl.check_example_labels:37] [PID:2251] <s>(-100, 1, 1) ... </s>(2, 1, 2)[39m
[2023-08-30 07:34:57,197] [INFO] [axolotl.check_example_labels:38] [PID:2251] 


[39m
[2023-08-30 07:34:57,258] [INFO] [axolotl.check_example_labels:37] [PID:2251] <s>(-100, 1, 1) ... </s>(2, 1, 2)[39m
[2023-08-30 07:34:57,258] [INFO] [axolotl.check_example_labels:38] [PID:2251] 


[39m
[2023-08-30 07:34:57,258] [INFO] [axolotl.scripts.train:203] [PID:2251] Finished preparing dataset. Exiting...[39m
```

**Comment by NanoCode012** [comment]
Sorry for not getting back to this. I believe this should be working as expected.
