### ISSUE TITLE
TypeError: varlen_fwd(): incompatible function arguments. 

### ISSUE THREAD

**Issue by dongxiaolong** [axolotl-ai-cloud/axolotl#514]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

qlora finetune code-llama

### Current behaviour

Traceback (most recent call last):
  File "/root/dxl/axolotl/scripts/finetune.py", line 361, in <module>
    fire.Fire(do_train)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/dxl/axolotl/scripts/finetune.py", line 357, in do_train
    train(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/root/dxl/axolotl/scripts/finetune.py", line 292, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 2682, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/dxl/axolotl/src/axolotl/utils/trainer.py", line 293, in compute_loss
    return super().compute_loss(model, inputs, return_outputs=return_outputs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 2707, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/utils/operations.py", line 545, in forward
    return model_forward(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/utils/operations.py", line 533, in call
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/peft/peft_model.py", line 931, in forward
    return self.base_model(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 820, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/dxl/axolotl/src/axolotl/monkeypatch/llama_attn_hijack_flash.py", line 482, in llama_model_forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/root/dxl/axolotl/src/axolotl/monkeypatch/llama_attn_hijack_flash.py", line 478, in custom_forward
    return module(*inputs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/dxl/axolotl/src/axolotl/monkeypatch/llama_attn_hijack_flash.py", line 572, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/dxl/axolotl/src/axolotl/monkeypatch/llama_attn_hijack_flash.py", line 171, in flashattn_forward
    output = flash_attn_varlen_qkvpacked_func(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 646, in flash_attn_varlen_qkvpacked_func
    return FlashAttnVarlenQKVPackedFunc.apply(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 209, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 66, in _flash_attn_varlen_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
TypeError: varlen_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: Optional[torch.Tensor], arg4: torch.Tensor, arg5: torch.Tensor, arg6: int, arg7: int, arg8: float, arg9: float, arg10: bool, arg11: bool, arg12: bool, arg13: Optional[torch.Generator]) -> List[torch.Tensor]

Invoked with: <repr raised Error>, <repr raised Error>, <repr raised Error>, None, <repr raised Error>, <repr raised Error>, <repr raised Error>, <repr raised Error>, 0.0, 0.08838834764831845, False, True, False, None
  0%|          | 0/12 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/llm_train/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/llm_train/bin/python', 'scripts/finetune.py', 'examples/code-llama/34b/qlora.yml']' returned non-zero exit status 1.

### Steps to reproduce

accelerate scrips/finetune.py example/code-llama/34B/qlora.yaml

### Possible solution

Now, we know the main cause of the error, but in order to fully understand the problem, we need to look at the context of the varlen_fwd() function. This can be found in the flash_attn/flash_attn_interface.py file.

Based on the error stack, the problem may be in the call to the _flash_attn_varlen_forward function, which is located on line 66 of the flash_attn/flash_attn_interface.py file.

In summary, the heart of the problem seems to be a mismatch between the parameters passed to the varlen_fwd() function and those expected by the function, especially since some of the parameters may be invalid or corrupted.

In order to fix this problem, you need to:

Check the code that calls varlen_fwd() to ensure that the correct arguments are passed.
Ensure that all arguments passed are valid and not corrupt.
If possible, review the documentation or source code for the varlen_fwd() function to ensure that you understand its parameter requirements correctly.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by dongxiaolong** [comment]
I think it's maybe CUDA out of memory, I will validate it soon.

**Comment by tmm1** [comment]
pip install -U flash-attn
