### ISSUE TITLE
Unable to run example fine tuning

### ISSUE THREAD

**Issue by nareshurs** [axolotl-ai-cloud/axolotl#522]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Model fine tune should run successfully using examples with below command.  

'accelerate launch scripts/finetune.py examples/openllama-3b/lora.yml'

I am running on Jupyter Notebook

### Current behaviour

Failing with below error

NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(4, 256, 32, 100) (torch.float16)
     key         : shape=(4, 256, 32, 100) (torch.float16)
     value       : shape=(4, 256, 32, 100) (torch.float16)
     attn_bias   : <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
     p           : 0.0
`decoderF` is not supported because:
    attn_bias type is <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
`flshattF@v2.0.8` is not supported because:
    query.shape[-1] % 8 != 0
`tritonflashattF` is not supported because:
    operator wasn't built - see `python -m xformers.info` for more info
    query.shape[-1] % 8 != 0
    key.shape[-1] % 8 != 0
    value.shape[-1] % 8 != 0
    triton is not available
`cutlassF` is not supported because:
    query.shape[-1] % 8 != 0
    value.shape[-1] % 8 != 0
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    dtype=torch.float16 (supported: {torch.float32})
    attn_bias type is <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
    unsupported embed per head: 100
  0%|                                                                                                                                               | 0/7251 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher

### Steps to reproduce

Run below commands

git clone https://github.com/OpenAccess-AI-Collective/axolotl
cd axolotl

pip3 install -e .[flash-attn]
pip3 install -U git+https://github.com/huggingface/peft.git

# finetune lora
accelerate launch scripts/finetune.py examples/openllama-3b/lora.yml

### Possible solution

No idea

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/1991946

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by nareshurs** [comment]
After further investigation I found 'Try to turn off xformers.' as a fix in documentation. I have updated my config yaml file 
from 'xformer_attention: true' to xformer_attention:  Issue is resolved now
