### ISSUE TITLE
AttributeError: 'PeftModelForCausalLM' object has no attribute 'save_checkpoint'

### ISSUE THREAD

**Issue by dongxiaolong** [axolotl-ai-cloud/axolotl#529]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

save checkpoint successfully

### Current behaviour

0%|          | 10/8226 [00:57<12:17:48,  5.39s/it]Traceback (most recent call last):
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/peft/peft_model.py", line 445, in getattr
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in getattr
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PeftModelForCausalLM' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 327, in getattr
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in getattr
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModel' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dxl/axolotl/scripts/finetune.py", line 278, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/dxl/axolotl/scripts/finetune.py", line 274, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/root/dxl/axolotl/src/axolotl/train.py", line 120, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 1927, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 2265, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/transformers/trainer.py", line 2326, in _save_checkpoint
    self.model_wrapped.save_checkpoint(output_dir)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/peft/peft_model.py", line 447, in getattr
    return getattr(self.base_model, name)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 329, in getattr
    return getattr(self.model, name)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in getattr
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'save_checkpoint'
  0%|          | 10/8226 [02:21<32:13:55, 14.12s/it]
Traceback (most recent call last):
  File "/root/miniconda3/envs/llm_train/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/llm_train/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/llm_train/bin/python', 'scripts/finetune.py', 'examples/my_own/qlora_codellama.yml']' returned non-zero exit status 1.

### Steps to reproduce

base_model: /root/autodl-fs/models/code-llama/text-generation-webui/models/Phind-CodeLlama-34B-v2/Phind-CodeLlama-34B-v2/
base_model_config: /root/autodl-fs/models/code-llama/text-generation-webui/models/Phind-CodeLlama-34B-v2/Phind-CodeLlama-34B-v2/
model_type: LlamaForCausalLM
tokenizer_type: CodeLlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /root/autodl-tmp/models/Open-Platypus
    type: alpaca
dataset_prepared_path: /root/autodl-tmp/models/last_run_prepared
val_set_size: 0.01
output_dir: /root/autodl-fs/models/code-llama-chat

adapter: qlora
lora_model_dir:
lora_out_dir: /root/autodl-fs/models/code-llama-chat-lora

sequence_len: 4096
sample_packing: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_mode: disabled
wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
@dongxiaolong can you confirm how you installed peft? from main? the last release version?

**Comment by dongxiaolong** [comment]
> @dongxiaolong can you confirm how you installed peft? from main? the last release version?

yes, I install the peft-0.5.0.dev0.

**Comment by dongxiaolong** [comment]
> @dongxiaolong can you confirm how you installed peft? from main? the last release version?

When I removed the entire environment and upgraded peft to 0.6.0.dev, I still get this error.

**Comment by dongxiaolong** [comment]
> @dongxiaolong can you confirm how you installed peft? from main? the last release version?

This was my mistake, I was using the wrong environment variable accelerate_use_deepspeed=true when I wasn't using deepspeed. Thanks for your help.
