### ISSUE TITLE
Getting error TypeError: openssl_md5() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by Rahmat711** [axolotl-ai-cloud/axolotl#535]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

the code should run as usual and process the fine tuninng

### Current behaviour

I am getting error 
[2023-09-07 15:16:20,539] [INFO] [axolotl.load_tokenized_prepared_datasets:125] [PID:16832] [RANK:0] Prepared dataset loaded from disk...
Traceback (most recent call last):
  File "scripts/finetune.py", line 278, in <module>
    fire.Fire(do_cli)
  File "/home/rahmat.khan/llama/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/rahmat.khan/llama/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/rahmat.khan/llama/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/finetune.py", line 271, in do_cli
    dataset_meta = load_datasets(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "scripts/finetune.py", line 234, in load_datasets
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/home/rahmat.khan/code_llma/axolotl/src/axolotl/utils/data.py", line 58, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/rahmat.khan/code_llma/axolotl/src/axolotl/utils/data.py", line 503, in load_prepare_datasets
    train_fingerprint = hashlib.md5(
TypeError: openssl_md5() takes at most 1 argument (2 given)
Traceback (most recent call last):
  File "/home/rahmat.khan/llama/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/rahmat.khan/llama/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/rahmat.khan/llama/lib/python3.8/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/home/rahmat.khan/llama/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/rahmat.khan/llama/bin/python', 'scripts/finetune.py', 'train_rk.yaml']' returned non-zero exit status 1.

### Steps to reproduce

this is my yaml file

base_model: TheBloke/CodeLlama-13B-Instruct-GPTQ
base_model_config: TheBloke/CodeLlama-13B-Instruct-GPTQ
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true
hub_model_id: athenaCodeLlama-13b

load_in_8bit: false
load_in_4bit: true
qptq: true
gptq_groupsize: 128
gptq_model_v1: false 
strict: false

datasets:
  - path: kaxap/pg-gpt4SQL-sql-instructions-1k
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.02
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: axolotl
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
eval_steps: 0.01
save_strategy: epoch
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.8.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
fixed by #533
