### ISSUE TITLE
'FullyShardedDataParallelPlugin' object has no attribute 'activation_checkpointing'

### ISSUE THREAD

**Issue by dongxiaolong** [axolotl-ai-cloud/axolotl#542]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

One potential solution for https://github.com/huggingface/transformers/issues/25988, we need to guard for things in Accelerate main better for items, especially items like fsdp and deepspeed

### Current behaviour

Traceback (most recent call last):
  File "/root/autodl-tmp/workspace/axolotl/scripts/finetune.py", line 278, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/axolotl/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/autodl-tmp/workspace/axolotl/scripts/finetune.py", line 274, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/root/autodl-tmp/workspace/axolotl/src/axolotl/train.py", line 77, in train
    trainer = setup_trainer(
  File "/root/autodl-tmp/workspace/axolotl/src/axolotl/utils/trainer.py", line 687, in setup_trainer
    trainer = trainer_cls(
  File "/root/autodl-tmp/workspace/axolotl/src/axolotl/utils/trainer.py", line 170, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/trainer.py", line 345, in __init__
    self.create_accelerator_and_postprocess()
  File "/root/miniconda3/envs/axolotl/lib/python3.10/site-packages/transformers/trainer.py", line 3914, in create_accelerator_and_postprocess
    "activation_checkpointing", fsdp_plugin.activation_checkpointing
AttributeError: 'FullyShardedDataParallelPlugin' object has no attribute 'activation_checkpointing'

### Steps to reproduce

enable fsdp with：
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer

### Possible solution

https://github.com/huggingface/transformers/pull/25991
mabey should update accelerate==0.23.0

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by dongxiaolong** [comment]
This was successfully executed when I upgraded the accelerate after.
