### ISSUE TITLE
Phi models not working

### ISSUE THREAD

**Issue by jsancs** [axolotl-ai-cloud/axolotl#598]
### Please check that this issue hasn't been reported before.

- [x] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Executing `accelerate launch -m axolotl.cli.train examples/phi/phi-ft.yml --deepspeed deepspeed/zero1.json` as said in the Phi models readme, should launch the finetune process.

### Current behaviour

Instead, it produces this error:

`RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'DeepSpeedSchedulerWrapper' from 'accelerate.utils' (/opt/conda/lib/python3.10/site-packages/accelerate/utils/__init__.py)`

### Steps to reproduce

Run `accelerate launch -m axolotl.cli.train examples/phi/phi-ft.yml --deepspeed deepspeed/zero1.json`

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by irbull** [comment]
Same thing with llama and open llama models. This was working last Thursday, but it seems that recent changes have broken something here.

Here is the full stack trace when trying to follow the quick start guide:

```
ImportError: cannot import name 'DeepSpeedSchedulerWrapper' from 'accelerate.utils' (/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/workspace/axolotl/src/axolotl/cli/__init__.py", line 21, in <module>
    from axolotl.train import TrainDatasetMeta
  File "/workspace/axolotl/src/axolotl/train.py", line 21, in <module>
    from axolotl.utils.trainer import setup_trainer
  File "/workspace/axolotl/src/axolotl/utils/trainer.py", line 26, in <module>
    from transformers import EarlyStoppingCallback, Trainer, TrainingArguments
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1215, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1227, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'DeepSpeedSchedulerWrapper' from 'accelerate.utils' (/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'axolotl.cli.train', 'examples/openllama-3b/lora.yml']' returned non-zero exit status 1.
```

**Comment by philpax** [comment]
This also appears to be the case for the QLoRA method:

```
$ python -m axolotl.cli.train examples/phi/phi-qlora.yml
...
  File ".env/lib/python3.11/site-packages/transformers/trainer.py", line 217, in <module>
    from accelerate.utils import DeepSpeedSchedulerWrapper
ImportError: cannot import name 'DeepSpeedSchedulerWrapper' from 'accelerate.utils' (.env/lib/python3.11/site-packages/accelerate/utils/__init__.py)
```

Using a venv with Arch and Git-installed versions of transformers and accelerate. Some kind of path issue?

**Comment by generalsvr** [comment]
Same here for code-llama lora (without deepspeed). Tried to downgrade accelerate, no luck

**Comment by winglian** [comment]
try reinstalling both accelerate and deepspeed

**Comment by irbull** [comment]
I don't know about reinstalling, but I started with a fresh install (RunPod, pytorch:2.0.1 and python 3.10).

I then installed everything fresh:
```
pip3 install packaging
pip3 install -e .[flash-attn]
pip3 install -U git+https://github.com/huggingface/peft.git
```
I would expect that this installed the correct versions of these dependencies. I then tried the example on the quickstart:
```
accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml
```

And this failed with the exception above about `DeepSpeedSchedulerWrapper`.

**Comment by philpax** [comment]
To clarify my previous failure, my install is also completely fresh; I installed the ML stack for the first time last night (fresh Arch install), and did all of the installation in a venv, and switched to Git versions of the HF dependencies when it failed. No luck - as far as I can tell, it's not a dependency freshness issue.

**Comment by winglian** [comment]
what if you try to train with `ACCELERATE_USE_DEEPSPEED=true accelerate launch -m ...`?

**Comment by winglian** [comment]
> I don't know about reinstalling, but I started with a fresh install (RunPod, pytorch:2.0.1 and python 3.10).
> 
> I then installed everything fresh:

Are you using the axolotl runpod image? if so, you shouldn't need to install those (but you will probably need to update deepspeed)

**Comment by philpax** [comment]
> what if you try to train with `ACCELERATE_USE_DEEPSPEED=true accelerate launch -m ...`?

```
(.env) [philpax@valkyrie axolotl]$ git log --pretty=oneline -n 1
674c57692d8f9712314c5238681d1b532af57142 (HEAD -> main, origin/main, origin/HEAD) more sane defaults for openllama 3b used for quickstarts (#602)

(.env) [philpax@valkyrie axolotl]$ ACCELERATE_USE_DEEPSPEED=true accelerate launch -m axolotl.cli.train examples/phi/phi-qlora.yml
Traceback (most recent call last):
  File ".env/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1225, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".env/lib/python3.11/site-packages/transformers/trainer.py", line 217, in <module>
    from accelerate.utils import DeepSpeedSchedulerWrapper
ImportError: cannot import name 'DeepSpeedSchedulerWrapper' from 'accelerate.utils' (.env/lib/python3.11/site-packages/accelerate/utils/__init__.py)
```

**Comment by winglian** [comment]
> I don't know about reinstalling, but I started with a fresh install (RunPod, pytorch:2.0.1 and python 3.10).
> 
> I then installed everything fresh:
> 
> ```
> pip3 install packaging
> pip3 install -e .[flash-attn]
> pip3 install -U git+https://github.com/huggingface/peft.git
> ```
> 
> I would expect that this installed the correct versions of these dependencies. I then tried the example on the quickstart:
> 
> ```
> accelerate launch -m axolotl.cli.train examples/openllama-3b/lora.yml
> ```
> 
> And this failed with the exception above about `DeepSpeedSchedulerWrapper`.

Did you `pip install deepspeed` ? I didn't see mention of that.

**Comment by irbull** [comment]
> Did you `pip install deepspeed` ? I didn't see mention of that.

Nope. This seems to be it. This wasn't mentioned in the quick start guide for the README. I'll create a PR to add it.. Thanks!

**Comment by irbull** [comment]
I've created a PR for this. I'm not sure if this should be set in the requirements file. In fact, I'm not sure why we have some manual installs and a requirements.txt? I have limited experience with python, so I'm sure there is a good reason.

**Comment by philpax** [comment]
> Did you `pip install deepspeed` ? I didn't see mention of that.

...yep, installing deepspeed fixed it. +1 to putting it in README/requirements.

**Comment by Napuh** [comment]
> I've created a PR for this. I'm not sure if this should be set in the requirements file. In fact, I'm not sure why we have some manual installs and a requirements.txt? I have limited experience with python, so I'm sure there is a good reason.

Documentation does not mention `requirements.txt` file but it's a good idea to keep that file updated too. I think `deepspeed` should be added to the setup file too, because that's the file in charge of managing dependencies when doing `pip install .`

**Comment by irbull** [comment]
Thanks. I've updated the PR to include `deepspeed` in the `requirements.txt`. I'm not sure if it should be tied to a specific version or not.

**Comment by winglian** [comment]
Thanks all! Deepspeed isn’t typically a blocking requirement to use
axolotl, so isn’t included in the requirements file. I’ll work with the
owner of the PR to get that updated (probably as an extra for setup.Py)

**Comment by hamero** [comment]
Hi,
I'm having a different error when launching phi-ft
`accelerate launch -m axolotl.cli.train examples/phi/phi-ft.yml --deepspeed deepspeed/zero1.json`
using latest main `ec0958f4f846236ac2703dd644f6dac4365f64b4`

```
...
[2023-09-20 16:59:30,484] [INFO] [axolotl.train.train:57] [PID:1734] [RANK:0] loading model and (optionally) peft_config...
Downloading pytorch_model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2.84G/2.84G [00:32<00:00, 86.9MB/s]
Downloading (…)neration_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 69.0/69.0 [00:00<00:00, 514kB/s]
[2023-09-20 17:00:17,824] [INFO] [axolotl.train.train:106] [PID:1734] [RANK:0] Starting trainer...
[2023-09-20 17:00:17,824] [INFO] [axolotl.train.train:108] [PID:1734] [RANK:0] hang tight... sorting dataset for group_by_length
[2023-09-20 17:00:18,063] [INFO] [axolotl.utils.dataloader._len_est:264] [PID:1734] [RANK:0] packing_efficiency_estimate: 0.87 total_num_tokens per device: 9098774
[2023-09-20 17:00:18,063] [INFO] [axolotl.utils.dataloader._len_est:264] [PID:1734] [RANK:0] packing_efficiency_estimate: 0.87 total_num_tokens per device: 9098774
[2023-09-20 17:00:18,075] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
  0%|                                                                                                                                | 0/20216 [00:00<?, ?it/s][2023-09-20 17:00:21,342] [INFO] [axolotl.utils.dataloader._len_est:264] [PID:1734] [RANK:0] packing_efficiency_estimate: 0.87 total_num_tokens per device: 9098774
[2023-09-20 17:00:21,342] [INFO] [axolotl.utils.dataloader.generate_batches:181] [PID:1734] [RANK:0] generating packed batches
[2023-09-20 17:00:21,352] [INFO] [axolotl.utils.dataloader.generate_batches:187] [PID:1734] [RANK:0] 2a22008b3531e8c84067ceb4563bef7e8666e7b6b73d5e70c036e5d0694ee5a4
[2023-09-20 17:00:21,368] [INFO] [axolotl.utils.dataloader._len_est:264] [PID:1734] [RANK:0] packing_efficiency_estimate: 0.87 total_num_tokens per device: 9098774
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 36, in <module>
    fire.Fire(do_cli)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 32, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 116, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1589, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1969, in _inner_training_loop
    self.optimizer.step()
AttributeError: 'DummyOptim' object has no attribute 'step'
  0%|                                                                                                                                | 0/20216 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'axolotl.cli.train', 'examples/phi/phi-ft.yml', '--deepspeed', 'deepspeed/zero1.json']' returned non-zero exit status 1.
```
Any ideas?

**Comment by DJJones66** [comment]
> Hi, I'm having a different error when launching phi-ft `accelerate launch -m axolotl.cli.train examples/phi/phi-ft.yml --deepspeed deepspeed/zero1.json` using latest main `ec0958f4f846236ac2703dd644f6dac4365f64b4`



 Same exact issue as well, this is after installing deepspeed to solve the original issue

**Comment by hamero** [comment]
fwiw, just dropping the `--deepspeed deepspeed/zero1.json` option seems to allow the training to kick-off successfully

**Comment by DJJones66** [comment]
> fwiw, just dropping the `--deepspeed deepspeed/zero1.json` option seems to allow the training to kick-off successfully

It started fine for me as well, an hour into the training at this time so cannot really report any results.

**Comment by DJJones66** [comment]
Just a heads up, it did complete the training as expected.  Since the test data was used to train, the answers were no different than before training.  I will create a mini dataset to explore this further tomorrow.
