### ISSUE TITLE
KeyError: 'text' When Finetuning On Completion Dataset

### ISSUE THREAD

**Issue by skamano** [axolotl-ai-cloud/axolotl#618]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

`accelerate launch scripts/finetune.py config.yml` should start training normally. I have this dataset in `config.yml`:

```
datasets:
  - path: atom-in-the-universe/fanfics-10k-50k
    type: completion
    field: text
```

This config is otherwise identical to `examples/llama-2/qlora.yml`.

### Current behaviour

Dataset downloads successfully but fails when generating the train split. The dataset has 19.8k rows total, so it looks like axolotl is trying to process entries beyond this total:
```
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:25<00:00, 25.35s/it]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.44it/s]
Generating train split: 19847 examples [00:14, 1409.60 examples/s]
Map (num_proc=32):   0%|                                                                             | 0/19847 [00:00<?, ? examples/s]
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/dist-packages/datasets/utils/py_utils.py", line 1347, in _write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3450, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3353, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/workspace/axolotl/src/axolotl/prompt_tokenizers.py", line 249, in tokenize_prompt
    full_prompt = self._build_full_prompt(prompt["text"], None, None)
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 270, in __getitem__
    value = self.data[key]
KeyError: 'text'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/axolotl/scripts/finetune.py", line 364, in <module>
    fire.Fire(do_train)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/scripts/finetune.py", line 360, in do_train
    train(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/workspace/axolotl/scripts/finetune.py", line 194, in train
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 58, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 470, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/workspace/axolotl/src/axolotl/utils/data.py", line 330, in load_tokenized_prepared_datasets
    ds_wrapper = TokenizedPromptDataset(ds_strategy, ds)
  File "/workspace/axolotl/src/axolotl/datasets.py", line 36, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/workspace/axolotl/src/axolotl/datasets.py", line 41, in process
    return dataset.map(
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 3189, in map
    for rank, done, content in iflatmap_unordered(
  File "/usr/local/lib/python3.10/dist-packages/datasets/utils/py_utils.py", line 1387, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/usr/local/lib/python3.10/dist-packages/datasets/utils/py_utils.py", line 1387, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/pool.py", line 774, in get
    raise self._value
KeyError: 'text'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'scripts/finetune.py', 'lq-llama2-v1.yml']' returned non-zero exit status 1.
```

### Steps to reproduce

1. Replace the dataset in `examples/llama-2/qlora.yml` with the config below:
 ```
datasets:
  - path: atom-in-the-universe/fanfics-10k-50k
    type: completion
    field: text
```

2.  Run `accelerate launch scripts/finetune.py examples/llama-2/qlora.yml`

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.9

### axolotl branch-commit

main/faecff9

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
<img width="1093" alt="Screenshot_2023-09-21_at_11_50_59_AM" src="https://github.com/OpenAccess-AI-Collective/axolotl/assets/381258/b6cd8171-61fc-45cd-abab-114bfabe6d48">

you should be inspecting your dataset to identify the correct field. in this case your dataset use `TEXT`, not `text`.

**Comment by skamano** [comment]
I specified TEXT but still having the same issue :/

**Comment by skamano** [comment]
Figured it out, I was actually using an old commit which was causing the issue.
