### ISSUE TITLE
Can't install flash-attn

### ISSUE THREAD

**Issue by suvanshchawla** [axolotl-ai-cloud/axolotl#641]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Trying to run the command

`pip install -e "./axolotl[flash-attn]"`

and based on the documentation it should get installed

### Current behaviour

I am getting an error while trying to install axolotl[flash-attn]

Current specification of the machine I am trying to run it on

Ryzen 5 5600H, 6 core 12 logical cores
Ram: 16 GB
GPU: RTX 3070 8GB
CUDA: 11.7
Pytorch version : 2.0.1+cu117
Microsoft Visual C++ 2015 x64 and x86 (14.36.32532) with Windows 10SDK and MSVC installed

Command Run: `pip install -e "./axolotl[flash-attn]"`

I am following [OpenPipe's guide for fine tuning Llama](https://github.com/OpenPipe/OpenPipe/tree/main/examples/classify-recipes)

Error:

```      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "C:\Users\suvan\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\suvan\AppData\Local\Temp\pip-install-podpxhha\flash-attn_bae07d3c8e0b4795bc366ba5d7202a6e\setup.py", line 287, in <module>
          setup(
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\suvan\Downloads\classify-recipes\venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> flash-attn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.```


### Steps to reproduce

Running the command

`pip install -e "./axolotl[flash-attn]"`

### Possible solution

_No response_

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Python Version

3.11.2

### axolotl branch-commit

main/d887ad8

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Can you try installing flash-attn on its own? `pip install flash-attn`
We can try to help you triage your flash-attn install, but you may need help from https://github.com/Dao-AILab/flash-attention/issues

**Comment by jaredquekjz** [comment]
Same issue here when using pip install -e "./axolotl[flash-attn]". Everything will work till the compilation of wheel for flash-attn - when things will hang indefinitely.:

"Building wheels for collected packages: rouge-score, flash-attn, transformers, accelerate, deepspeed, fire, optimum, peft, pathtools, lit, wavedrom
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24932 sha256=dd8ba92a009eba761c19ef89d49283b55104368f76977e299b258201b0ccc66d
  Stored in directory: /home/ubuntu/.cache/pip/wheels/5f/dd/89/461065a73be61a532ff8599a28e9beef17985c9e9c31e541b4
  Building wheel for flash-attn (setup.py) ... "   Do we remove flash from requirements.txt and install separately? Installation on my local system works well about a week back.

**Comment by jaredquekjz** [comment]
Got a different kind of problem on Ubuntu server when installing axolotl using pip/conda at the command: pip3 install -e '.[flash-attn,deepspeed]'. Also involving flash-attn. Last week these steps work well on my local system.

"""Collecting flash-attn>=2.2.1 (from axolotl==0.3.0)
  Using cached flash_attn-2.3.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xu9tlvdx/flash-attn_154cdd10fd5a4ac49809c36d8386fa5f/setup.py", line 18, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
""" I did see torch being collected earlier? Do I remove flash-attn or install torch first (don't make sense?) before pip3 install -e '.[flash-attn,deepspeed]'?

**Comment by NanoCode012** [comment]
Hey! I would recommend trying in WSL instead. Windows alone can be quite a headache to setup.

**Comment by NanoCode012** [comment]
@jaredquekjz , please have torch installed first.

**Comment by NanoCode012** [comment]
Hello, may I ask if you solved this?
