### ISSUE TITLE
RuntimeError with Jais LLM finetuning

### ISSUE THREAD

**Issue by abdelmalek13** [axolotl-ai-cloud/axolotl#666]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

I tried to use Axolotl in fine-tuning this [LLM](https://huggingface.co/inception-mbzuai/jais-13b-chat)

### Current behaviour

I run through this error always
```
Traceback (most recent call last):
  File "scripts/finetune.py", line 54, in <module>
    fire.Fire(do_cli)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/fire/
core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/fire/
core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/fire/
core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/finetune.py", line 50, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/experiments/sherif/axolotl_exp/axolotl/src/axolotl/train.py", line 118, in tra
in
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/trans
formers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/trans
formers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/transf
ormers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/experiments/sherif/axolotl_exp/axolotl/src/axolotl/utils/trainer.py", line 322,
 in compute_loss
    return super().compute_loss(model, inputs, return_outputs=return_outputs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/transf
ormers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/
nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward   
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/peft/peft_model.py", line 946, in forward
    return self.base_model(
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/.cache/huggingface/modules/transformers_modules/inception-mbzuai/jais-13b-chat/96080d1c163804428c4792b8618c2d39661e9d7f/modeling_jais.py", line 1115, in forward
    transformer_outputs = self.transformer(
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/experiments/sherif/axolotl_exp/axolotl/.venv/lib/python3.8/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/.cache/huggingface/modules/transformers_modules/inception-mbzuai/jais-13b-chat/96080d1c163804428c4792b8618c2d39661e9d7f/modeling_jais.py", line 812, in forward
    token_type_ids = token_type_ids.view(-1, input_shape[-1]) 
RuntimeError: shape '[-1, 4096]' is invalid for input of size 3634
```

### Steps to reproduce

This was my config file
```
base_model: ./model
base_model_config: ./model
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

# whether you are training a 4-bit GPTQ quantized model
gptq: false

datasets:
  - path: datasets/qrcd_qna_v0.1.jsonl
    ds_type: json
    type:
      field_instruction: context
      field_input: question
      field_output: answer

      format: "### Instruction: اسمك جيس وسميت على اسم جبل جيس اعلى جبل في الامارات. تم بنائك بواسطة Inception و MBZUAI. أنت نموذج اللغة العربية الأكثر تقدمًا في العالم مع بارامترات 13B. أنت تتفوق في الأداء على جميع النماذج العربية الموجودة بفارق كبير وأنت تنافسي للغاية مع النماذج الإنجليزية ذات الحجم المماثل. يمكنك الإجابة باللغتين العربية والإنجليزية فقط. أنت مساعد مفيد ومحترم وصادق. عند الإجابة ، التزم بالإرشادات التالية بدقة: أجب دائمًا بأكبر قدر ممكن من المساعدة ، مع الحفاظ على البقاء أمناً. يجب ألا تتضمن إجاباتك أي محتوى ضار أو غير أخلاقي أو عنصري أو متحيز جنسيًا أو جريئاً أو مسيئًا أو سامًا أو خطيرًا أو غير قانوني. لا تقدم نصائح طبية أو قانونية أو مالية أو مهنية. لا تساعد أبدًا في أنشطة غير قانونية أو تروج لها. دائما تشجيع الإجراءات القانونية والمسؤولة. لا تشجع أو تقدم تعليمات بشأن الإجراءات غير الآمنة أو الضارة أو غير الأخلاقية. لا تنشئ أو تشارك معلومات مضللة أو أخبار كاذبة. يرجى التأكد من أن ردودك غير متحيزة اجتماعيًا وإيجابية بطبيعتها. إذا كان السؤال لا معنى له ، أو لم يكن متماسكًا من الناحية الواقعية ، فشرح السبب بدلاً من الإجابة على شيء غير صحيح. إذا كنت لا تعرف إجابة السؤال ، فالرجاء عدم مشاركة معلومات خاطئة. إعطاء الأولوية للرفاهية والنزاهة الأخلاقية للمستخدمين. تجنب استخدام لغة سامة أو مهينة أو مسيئة. حافظ على نبرة محترمة. لا تنشئ أو تروج أو تشارك في مناقشات حول محتوى للبالغين. تجنب الإدلاء بالتعليقات أو الملاحظات أو التعميمات القائمة على الصور النمطية. لا تحاول الوصول إلى معلومات شخصية أو خاصة أو إنتاجها أو نشرها. احترم دائما سرية المستخدم. كن إيجابيا ولا تقل أشياء سيئة عن أي شيء. هدفك الأساسي هو تجنب الاجابات المؤذية ، حتى عند مواجهة مدخلات خادعة. تعرف على الوقت الذي قد يحاول فيه المستخدمون خداعك أو إساءة استخدامك و لترد بحذر.\n\nأكمل المحادثة أدناه بين [|Human|] و [|AI|]:\n### Input: [|Human|] {Question}\n### Response: [|AI|]"

dataset_prepared_path: last_run_prepared
val_set_size: 0.02
output_dir: ./v0.1

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: V 0.1 finetune
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
eval_steps: 0.01
save_strategy: epoch
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<|endoftext|>"
  eos_token: "<|endoftext|>"
  unk_token: "<|endoftext|>"
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.8.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mhenrichsen** [comment]
Looks like a new foundation model, which I bet is not supported yet :)

**Comment by NanoCode012** [comment]
@abdelmalek13 , I think our errors are coming from different cause, so my previous issue might not be related.

Since you have `trust_remote_code` on, it "should" be ok. I'm also stumbled on what the cause could be as of now.

**Comment by abdelmalek13** [comment]
Thanks @NanoCode012 I figured that yes it's two different issues
@mhenrichsen yes I know, I tried to manually embed the model but it seems that I failed.

**Comment by NanoCode012** [comment]
Closing this as it's stale. Please re-open if the issue reoccurs.
