### ISSUE TITLE
runpod accelerate launch -m axolotl.cli.train examples/mistral/config.yml --deepspeed deepspeed/zero2.json error

### ISSUE THREAD

**Issue by ghost** [axolotl-ai-cloud/axolotl#682]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

According to the README:
If you run into CUDA OOM, use deepspeed with config zero2.json:
```shell
accelerate launch -m axolotl.cli.train examples/mistral/config.yml --deepspeed deepspeed/zero2.json
```
Should use deepspeed to lower vram usage.

### Current behaviour

Here is my output when I run the command, adapted with my config.yml path, from the readme in a runpod container with 96GB of VRAM:

```shell
!accelerate launch -m axolotl.cli.train config.yml --deepspeed deepspeed/zero2.json

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `2`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/bitsandbytes-0.41.1-py3.10.egg/bitsandbytes/cuda_setup/main.py:106: UserWarning: 

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=118
================================================================================


  warn((f'\n\n{"="*80}\n'
/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/bitsandbytes-0.41.1-py3.10.egg/bitsandbytes/cuda_setup/main.py:106: UserWarning: 

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=118
================================================================================


  warn((f'\n\n{"="*80}\n'
                              dP            dP   dP 
                              88            88   88 
   .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88 
   88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88 
   88.  .88  .d88b.  88.  .88 88 88.  .88   88   88 
   `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP 
                                                    
                                                    

[2023-10-05 19:41:31,119] [WARNING] [axolotl.validate_config:163] [PID:3646] [RANK:0] eval_batch_size != micro_batch_size. This can lead to VRAM instability.
[2023-10-05 19:41:31,126] [WARNING] [axolotl.validate_config:163] [PID:3647] [RANK:1] eval_batch_size != micro_batch_size. This can lead to VRAM instability.
[2023-10-05 19:41:31,241] [INFO] [axolotl.normalize_config:122] [PID:3646] [RANK:0] GPU memory usage baseline: 0.000GB (+0.455GB misc)
[2023-10-05 19:41:31,241] [WARNING] [axolotl.scripts.check_user_token:261] [PID:3646] [RANK:0] Error verifying HuggingFace token. Remember to log in using `huggingface-cli login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
[2023-10-05 19:41:31,249] [INFO] [axolotl.normalize_config:122] [PID:3647] [RANK:1] GPU memory usage baseline: 0.000GB (+0.455GB misc)
[2023-10-05 19:41:31,249] [WARNING] [axolotl.scripts.check_user_token:261] [PID:3647] [RANK:1] Error verifying HuggingFace token. Remember to log in using `huggingface-cli login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
[2023-10-05 19:41:31,418] [DEBUG] [axolotl.load_tokenizer:75] [PID:3646] [RANK:0] EOS: 2 / </s>
[2023-10-05 19:41:31,418] [DEBUG] [axolotl.load_tokenizer:76] [PID:3646] [RANK:0] BOS: 1 / <s>
[2023-10-05 19:41:31,419] [DEBUG] [axolotl.load_tokenizer:77] [PID:3646] [RANK:0] PAD: 2 / </s>
[2023-10-05 19:41:31,419] [DEBUG] [axolotl.load_tokenizer:78] [PID:3646] [RANK:0] UNK: 0 / <unk>
[2023-10-05 19:41:31,473] [DEBUG] [axolotl.load_tokenizer:75] [PID:3647] [RANK:1] EOS: 2 / </s>
[2023-10-05 19:41:31,473] [DEBUG] [axolotl.load_tokenizer:76] [PID:3647] [RANK:1] BOS: 1 / <s>
[2023-10-05 19:41:31,473] [DEBUG] [axolotl.load_tokenizer:77] [PID:3647] [RANK:1] PAD: 2 / </s>
[2023-10-05 19:41:31,473] [DEBUG] [axolotl.load_tokenizer:78] [PID:3647] [RANK:1] UNK: 0 / <unk>
[2023-10-05 19:41:31,723] [INFO] [axolotl.load_tokenized_prepared_datasets:130] [PID:3646] [RANK:0] Unable to find prepared dataset in last_run_prepared/79fe5144e8e385dc65045e15b51b2838
[2023-10-05 19:41:31,723] [INFO] [axolotl.load_tokenized_prepared_datasets:131] [PID:3646] [RANK:0] Loading raw datasets...
[2023-10-05 19:41:31,723] [INFO] [axolotl.load_tokenized_prepared_datasets:136] [PID:3646] [RANK:0] No seed provided, using default seed of 42
Map (num_proc=64): 100%|███████████| 2000/2000 [00:01<00:00, 1677.16 examples/s]
[2023-10-05 19:41:36,515] [INFO] [axolotl.load_tokenized_prepared_datasets:354] [PID:3646] [RANK:0] merging datasets
[2023-10-05 19:41:38,973] [INFO] [axolotl.load_tokenized_prepared_datasets:130] [PID:3647] [RANK:1] Unable to find prepared dataset in last_run_prepared/79fe5144e8e385dc65045e15b51b2838
[2023-10-05 19:41:38,974] [INFO] [axolotl.load_tokenized_prepared_datasets:131] [PID:3647] [RANK:1] Loading raw datasets...
[2023-10-05 19:41:38,974] [INFO] [axolotl.load_tokenized_prepared_datasets:136] [PID:3647] [RANK:1] No seed provided, using default seed of 42
Map (num_proc=64): 100%|███████████| 2000/2000 [00:01<00:00, 1425.44 examples/s]
[2023-10-05 19:41:46,305] [INFO] [axolotl.load_tokenized_prepared_datasets:354] [PID:3647] [RANK:1] merging datasets
Filter (num_proc=64): 100%|████████| 1980/1980 [00:00<00:00, 2691.62 examples/s]
Filter (num_proc=20): 100%|██████████████| 20/20 [00:00<00:00, 48.95 examples/s]
[2023-10-05 19:41:52,758] [INFO] [axolotl.calculate_total_num_steps:526] [PID:3646] [RANK:0] total_num_steps: 372
[2023-10-05 19:41:52,772] [INFO] [axolotl.train.train:48] [PID:3646] [RANK:0] loading tokenizer... mistralai/Mistral-7B-v0.1
[2023-10-05 19:41:52,963] [DEBUG] [axolotl.load_tokenizer:75] [PID:3646] [RANK:0] EOS: 2 / </s>
[2023-10-05 19:41:52,964] [DEBUG] [axolotl.load_tokenizer:76] [PID:3646] [RANK:0] BOS: 1 / <s>
[2023-10-05 19:41:52,964] [DEBUG] [axolotl.load_tokenizer:77] [PID:3646] [RANK:0] PAD: 2 / </s>
[2023-10-05 19:41:52,964] [DEBUG] [axolotl.load_tokenizer:78] [PID:3646] [RANK:0] UNK: 0 / <unk>
[2023-10-05 19:41:53,267] [INFO] [axolotl.train.train:56] [PID:3646] [RANK:0] loading model and (optionally) peft_config...
Filter (num_proc=64): 100%|████████| 1980/1980 [00:00<00:00, 2360.42 examples/s]
Filter (num_proc=20): 100%|██████████████| 20/20 [00:00<00:00, 58.73 examples/s]
[2023-10-05 19:41:59,075] [INFO] [axolotl.calculate_total_num_steps:526] [PID:3647] [RANK:1] total_num_steps: 372
[2023-10-05 19:41:59,087] [INFO] [axolotl.train.train:48] [PID:3647] [RANK:1] loading tokenizer... mistralai/Mistral-7B-v0.1
[2023-10-05 19:41:59,278] [DEBUG] [axolotl.load_tokenizer:75] [PID:3647] [RANK:1] EOS: 2 / </s>
[2023-10-05 19:41:59,278] [DEBUG] [axolotl.load_tokenizer:76] [PID:3647] [RANK:1] BOS: 1 / <s>
[2023-10-05 19:41:59,278] [DEBUG] [axolotl.load_tokenizer:77] [PID:3647] [RANK:1] PAD: 2 / </s>
[2023-10-05 19:41:59,278] [DEBUG] [axolotl.load_tokenizer:78] [PID:3647] [RANK:1] UNK: 0 / <unk>
[2023-10-05 19:41:59,575] [INFO] [axolotl.train.train:56] [PID:3647] [RANK:1] loading model and (optionally) peft_config...
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:18<00:00,  9.06s/it]
[2023-10-05 19:42:14,140] [INFO] [axolotl.load_model:364] [PID:3646] [RANK:0] GPU memory usage after model load: 13.989GB (+0.251GB cache, +1.359GB misc)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/root/miniconda3/envs/py3.10/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 76, in train
    trainer = setup_trainer(
  File "/workspace/axolotl/src/axolotl/utils/trainer.py", line 667, in setup_trainer
    training_args = AxolotlTrainingArguments(  # pylint: disable=unexpected-keyword-arg
  File "<string>", line 128, in __init__
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/training_args.py", line 1693, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 88, in __init__
    super().__init__(config_file_or_dict)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 78, in __init__
    super().__init__(config_file_or_dict)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: deepspeed/zero2.json
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:14<00:00,  7.35s/it]
[2023-10-05 19:42:16,626] [INFO] [axolotl.load_model:364] [PID:3647] [RANK:1] GPU memory usage after model load: 13.989GB (+0.251GB cache, +1.359GB misc)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/root/miniconda3/envs/py3.10/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 76, in train
    trainer = setup_trainer(
  File "/workspace/axolotl/src/axolotl/utils/trainer.py", line 667, in setup_trainer
    training_args = AxolotlTrainingArguments(  # pylint: disable=unexpected-keyword-arg
  File "<string>", line 128, in __init__
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/training_args.py", line 1693, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 88, in __init__
    super().__init__(config_file_or_dict)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 78, in __init__
    super().__init__(config_file_or_dict)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: deepspeed/zero2.json
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3646) of binary: /root/miniconda3/envs/py3.10/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
axolotl.cli.train FAILED
```

### Steps to reproduce

1. Run the axolotl runpod container.
2. Edit the mistral config.yml with my dataset
3. Changed alpaca_chat.py in axolotl, and axolotl-update dir from lowercase "question" to uppercase "QUESTION" same with answer.
4. Paste my edited config.yml in /workspace
5. Run shell command provided.

### Config yaml

base_model: mistralai/Mistral-7B-v0.1
base_model_config: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: cvinker/lit_test
    type: alpaca_chat.load_qa
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./out

sequence_len: 8192
sample_packing:
pad_to_sequence_len:

wandb_project: axolotl_1
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
eval_table_size: 5
eval_table_max_new_tokens: 128
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Possible solution

Appears to be related to not knowing the location of the deepspeed config, and some padding complaints.

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by teknium1** [comment]
You should put the path to the deepspeed config in your deepspeed: field

**Comment by winglian** [comment]
@cvinker can you verify that from the directory that you are running the command, that deepspeed/zero2.json is a valid path?

**Comment by NanoCode012** [comment]
Hello, is this problem still occurring?

**Comment by generalsvr** [comment]
I have the same problem using zero2. Zero 1 works

**Comment by NanoCode012** [comment]
Just a note to future readers, the directory has been renamed to `deepspeed_configs`. Will be closing as its stale unless can be reproduced.
