### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'supports_batched'

### ISSUE THREAD

**Issue by thistleknot** [axolotl-ai-cloud/axolotl#753]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

dolly 15k prompt
{"instruction": "When did Virgin Australia start operating?", "input": "Virgin Australia, the trading name of Virgin Australia Airlines Pty Ltd, is an Australian-based airline. It is the largest airline by fleet size to use the Virgin brand. It commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route. It suddenly found itself as a major airline in Australia's domestic market after the collapse of Ansett Australia in September 2001. The airline has since grown to directly serve 32 cities in Australia, from hubs in Brisbane, Melbourne and Sydney.", "output": "Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route.", "category": "closed_qa"}

yaml config for it
datasets:
  - path: /home/user/TrainLLMv3/responses/databricks-dolly-15k/databricks-dolly-15k.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output
      field_category: category

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 

### Current behaviour

Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 8905.10it/s]
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1360.90it/s]
Generating train split: 15011 examples [00:00, 270376.56 examples/s]
Traceback (most recent call last):
  File "/home/user/axolotl/scripts/finetune.py", line 54, in <module>
    fire.Fire(do_cli)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/axolotl/scripts/finetune.py", line 47, in do_cli
    dataset_meta = load_datasets(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/home/user/axolotl/src/axolotl/cli/__init__.py", line 224, in load_datasets
    train_dataset, eval_dataset, total_num_steps = prepare_dataset(cfg, tokenizer)
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 60, in prepare_dataset
    train_dataset, eval_dataset = load_prepare_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 484, in load_prepare_datasets
    dataset = load_tokenized_prepared_datasets(
  File "/home/user/axolotl/src/axolotl/utils/data.py", line 269, in load_tokenized_prepared_datasets
    ds_wrapper = TokenizedPromptDataset(ds_strategy, ds)
  File "/home/user/axolotl/src/axolotl/datasets.py", line 36, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/home/user/axolotl/src/axolotl/datasets.py", line 42, in process
    if self.prompt_tokenizer.supports_batched:
AttributeError: 'NoneType' object has no attribute 'supports_batched'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/miniconda3/envs/textgen/bin/python', 'scripts/finetune.py', 'examples/openllama-3b/qlora.yml']' returned non-zero exit status 1.

### Steps to reproduce

setup yaml file and dl dataset (I changed the names to what you see in the yaml

### Config yaml

base_model: openlm-research/open_llama_3b_v2
base_model_config: openlm-research/open_llama_3b_v2
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
load_in_8bit: false
load_in_4bit: true
strict: false
push_dataset_to_hub:
datasets:
  - path: /home/user/TrainLLMv3/responses/databricks-dolly-15k/databricks-dolly-15k.jsonl
    type:
      system_prompt: ""
      system_format: ""
      field_system:
      field_instruction: instruction
      field_input: input
      field_output: output
      field_category: category

      format: |-
        ### Instruction: {instruction}
        ### Context: {input}
        ### Answer: 
      no_input_format: |-
        ### Instruction: {instruction}
        ### Answer: 
dataset_prepared_path:
val_set_size: 0.01
adapter: qlora
lora_model_dir:
sequence_len: 1024
sample_packing: true
lora_r: 8
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:
wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:
output_dir: ./qlora-out
gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 4
optimizer: paged_adamw_8bit
torchdistx_path:
lr_scheduler: cosine
learning_rate: 0.0002
train_on_inputs: false
group_by_length: false
bf16: false
fp16: true
tf32: false
gradient_checkpointing: true
early_stopping_patience: 
resume_from_checkpoint: true
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: false
gptq_groupsize:
gptq_model_v1:
warmup_steps: 20
eval_steps: 0.05
save_steps:
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.9

### axolotl branch-commit

2d60ba3a6ea4def14e6ab974299322a0bf90d5bb

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by thistleknot** [comment]
I figured it out
For some reason it didn't like 'Category'.  I removed pieces of the json using .del('id') and got myself to a working training session.  Will be done in 24 hours!

Thank you for this awesome framework!  I was able to load up 4 datasets for training easy peasy lemon squeezy!
