### ISSUE TITLE
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

### ISSUE THREAD

**Issue by luijait** [axolotl-ai-cloud/axolotl#783]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Don't get Error 

### Current behaviour

[2023-10-24 20:49:17,310] [WARNING] [axolotl.validate_config:154] [PID:387575] [RANK:0] `pad_to_sequence_len: true` is recommended when using sample_packing
[2023-10-24 20:49:17,310] [WARNING] [axolotl.validate_config:169] [PID:387575] [RANK:0] eval_batch_size != micro_batch_size. This can lead to VRAM instability.
[2023-10-24 20:49:17,321] [INFO] [axolotl.normalize_config:128] [PID:387575] [RANK:0] GPU memory usage baseline: 0.000GB (+20.445GB misc)
[2023-10-24 20:49:17,329] [WARNING] [axolotl.scripts.check_user_token:262] [PID:387575] [RANK:0] Error verifying HuggingFace token. Remember to log in using `huggingface-cli login` and get your access token from https://huggingface.co/settings/tokens if you want to use gated models or datasets.
[2023-10-24 20:49:17,568] [DEBUG] [axolotl.load_tokenizer:75] [PID:387575] [RANK:0] EOS: 2 / </s>
[2023-10-24 20:49:17,568] [DEBUG] [axolotl.load_tokenizer:76] [PID:387575] [RANK:0] BOS: 1 / <s>
[2023-10-24 20:49:17,568] [DEBUG] [axolotl.load_tokenizer:77] [PID:387575] [RANK:0] PAD: 2 / </s>
[2023-10-24 20:49:17,568] [DEBUG] [axolotl.load_tokenizer:78] [PID:387575] [RANK:0] UNK: 0 / <unk>
[2023-10-24 20:49:17,884] [INFO] [axolotl.load_tokenized_prepared_datasets:130] [PID:387575] [RANK:0] Unable to find prepared dataset in last_run_prepared/c88227b063eadec7c9e177abe0609967
[2023-10-24 20:49:17,891] [INFO] [axolotl.load_tokenized_prepared_datasets:131] [PID:387575] [RANK:0] Loading raw datasets...
[2023-10-24 20:49:17,891] [INFO] [axolotl.load_tokenized_prepared_datasets:136] [PID:387575] [RANK:0] No seed provided, using default seed of 42
Map (num_proc=2): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2058/2058 [07:10<00:00,  4.78 examples/s]
[2023-10-24 20:56:29,735] [INFO] [axolotl.load_tokenized_prepared_datasets:354] [PID:387575] [RANK:0] merging datasets
[2023-10-24 20:56:29,750] [INFO] [axolotl.load_tokenized_prepared_datasets:361] [PID:387575] [RANK:0] Saving merged prepared dataset to disk... last_run_prepared/c88227b063eadec7c9e177abe0609967
Saving the dataset (1/1 shards): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7637/7637 [00:03<00:00, 2206.85 examples/s]
Filter (num_proc=2): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7560/7560 [01:09<00:00, 108.66 examples/s]
Filter (num_proc=2): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 104.16 examples/s]
Map (num_proc=2): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7560/7560 [00:15<00:00, 484.44 examples/s]
Map (num_proc=2): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 212.24 examples/s]
[2023-10-24 20:57:59,841] [INFO] [axolotl.calculate_total_num_steps:156] [PID:387575] [RANK:0] calculating total_num_tokens
[2023-10-24 20:58:00,398] [INFO] [axolotl.calculate_total_num_steps:163] [PID:387575] [RANK:0] total_num_tokens: 26501926
[2023-10-24 20:58:00,805] [INFO] [axolotl.calculate_total_num_steps:173] [PID:387575] [RANK:0] `total_supervised_tokens: 26501926`
[2023-10-24 20:58:01,052] [INFO] [axolotl.utils.dataloader.generate_batches:181] [PID:387575] [RANK:0] generating packed batches
[2023-10-24 20:58:01,079] [INFO] [axolotl.utils.dataloader.generate_batches:187] [PID:387575] [RANK:0] 7669b8c424ffb06c5d96084ae05d1890f5a2533cbe071d4da27cae9bf0430279
[2023-10-24 20:58:09,922] [INFO] [axolotl.utils.dataloader.len_w_stats:295] [PID:387575] [RANK:0] packing_efficiency_estimate: 1.0 actual packing efficiency: 0.8898633994421331
[2023-10-24 20:58:09,922] [INFO] [axolotl.utils.dataloader._len_est:264] [PID:387575] [RANK:0] packing_efficiency_estimate: 1.0 total_num_tokens per device: 26501926
[2023-10-24 20:58:09,923] [INFO] [axolotl.calculate_total_num_steps:222] [PID:387575] [RANK:0] data_loader_len: 6404
[2023-10-24 20:58:09,923] [INFO] [axolotl.calc_sample_packing_eff_est:228] [PID:387575] [RANK:0] sample_packing_eff_est across ranks: [0.8898633994421331]
[2023-10-24 20:58:09,923] [INFO] [axolotl.calculate_total_num_steps:239] [PID:387575] [RANK:0] sample_packing_eff_est: 0.89
[2023-10-24 20:58:09,923] [INFO] [axolotl.calculate_total_num_steps:244] [PID:387575] [RANK:0] total_num_steps: 19212
[2023-10-24 20:58:09,935] [INFO] [axolotl.train.train:46] [PID:387575] [RANK:0] loading tokenizer... /home/user/ExLllamaV2/models/phind
[2023-10-24 20:58:10,099] [DEBUG] [axolotl.load_tokenizer:75] [PID:387575] [RANK:0] EOS: 2 / </s>
[2023-10-24 20:58:10,099] [DEBUG] [axolotl.load_tokenizer:76] [PID:387575] [RANK:0] BOS: 1 / <s>
[2023-10-24 20:58:10,099] [DEBUG] [axolotl.load_tokenizer:77] [PID:387575] [RANK:0] PAD: 2 / </s>
[2023-10-24 20:58:10,099] [DEBUG] [axolotl.load_tokenizer:78] [PID:387575] [RANK:0] UNK: 0 / <unk>
[2023-10-24 20:58:10,265] [INFO] [axolotl.train.train:54] [PID:387575] [RANK:0] loading model and (optionally) peft_config...
[2023-10-24 20:58:10,433] [INFO] [axolotl.load_model:145] [PID:387575] [RANK:0] patching with flash attention for sample packing
[2023-10-24 20:58:10,434] [INFO] [axolotl.load_model:218] [PID:387575] [RANK:0] patching _expand_mask
[2023-10-24 20:58:10,441] [ERROR] [axolotl.load_model:377] [PID:387575] [RANK:0] Exception raised attempting to load model, retrying with AutoModelForCausalLM
[2023-10-24 20:58:10,442] [ERROR] [axolotl.load_model:380] [PID:387575] [RANK:0] 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'
Traceback (most recent call last):
  File "/home/user/ExLllamaV2/axolotl/src/axolotl/utils/models.py", line 268, in load_model
    model = LlamaForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2688, in from_pretrained
    loading_attr_dict = quantization_config.get_loading_attributes()
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'
Traceback (most recent call last):
  File "/home/user/ExLllamaV2/axolotl/src/axolotl/utils/models.py", line 268, in load_model
    model = LlamaForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2688, in from_pretrained
    loading_attr_dict = quantization_config.get_loading_attributes()
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/ExLllamaV2/axolotl/src/axolotl/cli/train.py", line 51, in <module>
    fire.Fire(do_cli)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/ExLllamaV2/axolotl/src/axolotl/cli/train.py", line 47, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/home/user/ExLllamaV2/axolotl/src/axolotl/train.py", line 55, in train
    model, peft_config = load_model(cfg, tokenizer, inference=cli_args.inference)
  File "/home/user/ExLllamaV2/axolotl/src/axolotl/utils/models.py", line 381, in load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2688, in from_pretrained
    loading_attr_dict = quantization_config.get_loading_attributes()
AttributeError: 'BitsAndBytesConfig' object has no attribute 'get_loading_attributes'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', 'examples/code-llama/34b/qlora.yml']' returned non-zero exit status 1.

### Steps to reproduce

CUDA_VISIBLE_DEVICES=0 accelerate launch -m axolotl.cli.train examples/code-llama/34b/qlora.yml

### Config yaml

base_model: /home/user/phind-codellama-34b-v2
base_model_config: /home/user/phind-codellama-34b-v2
model_type: LlamaForCausalLM
tokenizer_type: CodeLlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /home/user/ml.jsonl
    type: completion
dataset_prepared_path:
val_set_size: 0.01
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:
lora_out_dir: /home/user/qlora

sequence_len: 4096
sample_packing: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_mode: disabled
wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.2

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Are you using a GPTQ model? It's not clear from your yaml file if it is since you're pointing to a local path. if so, you'll want to try one of the GPTQ configs. https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/llama-2/gptq-lora.yml

**Comment by luijait** [comment]
thanks! but I get this error 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/axolotl/src/axolotl/cli/train.py", line 51, in <module>
    fire.Fire(do_cli)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/axolotl/src/axolotl/cli/train.py", line 28, in do_cli
    parsed_cfg = load_cfg(config, **kwargs)
  File "/home/user/axolotl/src/axolotl/cli/__init__.py", line 210, in load_cfg
    validate_config(cfg)
  File "/home/user/axolotl/src/axolotl/utils/config.py", line 193, in validate_config
    raise ValueError("Can't load qlora if gptq")
ValueError: Can't load qlora if gptq

**Comment by luijait** [comment]
> Are you using a GPTQ model? It's not clear from your yaml file if it is since you're pointing to a local path. if so, you'll want to try one of the GPTQ configs. https://github.com/OpenAccess-AI-Collective/axolotl/blob/main/examples/llama-2/gptq-lora.yml

Thanks!!!
