### ISSUE TITLE
Training script crashes at the end of training (saving checkpoints work)

### ISSUE THREAD

**Issue by l3utterfly** [axolotl-ai-cloud/axolotl#788]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Complete training without crashing

### Current behaviour

When the training is complete, the script crashes with the following error:

```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 357394) of binary: /home/wgc/miniconda3/envs/axolotl/bin/python
Traceback (most recent call last):
  File "/home/wgc/miniconda3/envs/axolotl/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/wgc/miniconda3/envs/axolotl/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/wgc/miniconda3/envs/axolotl/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/home/wgc/miniconda3/envs/axolotl/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/wgc/miniconda3/envs/axolotl/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/wgc/miniconda3/envs/axolotl/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wgc/miniconda3/envs/axolotl/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=======================================================
axolotl.cli.train FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
```

Interestingly, saving checkpoints during training all works. Only crashes at the very end.

### Steps to reproduce

1. Download library and setup
2. Start training with any data
3. Wait for training to complete

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Are you using FSDP? `exitcode: -9` is already documented in the README as an system RAM OOM.

**Comment by l3utterfly** [comment]
I'm not using FSDP. I'm using the default config taken from `examples/mistral`, it has `fsdp` unset.

Could there be a bug in the code somewhere that's using unnecessary RAM? I have 256GB of CPU RAM, my dataset is 1GB, and I'm training a 7B model. It's hard to fathom in any world where I will run out of RAM.

@winglian
