### ISSUE TITLE
phi results in errors about modules for llama

### ISSUE THREAD

**Issue by thistleknot** [axolotl-ai-cloud/axolotl#805]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

can run finetune with phi qlora.yaml

### Current behaviour

```
(textgen) [root@pve-m7330 axolotl]# accelerate launch scripts/finetune.py examples/phi/phi-qlora-mine.yml --lora_model_dir="./qlora-out/"
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
                              dP            dP   dP
                              88            88   88
   .d8888b. dP.  .dP .d8888b. 88 .d8888b. d8888P 88
   88'  `88  `8bd8'  88'  `88 88 88'  `88   88   88
   88.  .88  .d88b.  88.  .88 88 88.  .88   88   88
   `88888P8 dP'  `dP `88888P' dP `88888P'   dP   dP



[2023-10-30 18:31:43,520] [WARNING] [axolotl.scripts.finetune.do_cli:26] [PID:737150] [RANK:0] scripts/finetune.py will be replaced with calling axolotl.cli.train
[2023-10-30 18:31:43,524] [WARNING] [axolotl.validate_config:163] [PID:737150] [RANK:0] eval_batch_size != micro_batch_size. This can lead to VRAM instability.
[2023-10-30 18:31:43,524] [WARNING] [axolotl.validate_config:209] [PID:737150] [RANK:0] `trust_remote_code` is set to true. Please make sure that you reviewed the remote code/model.
[2023-10-30 18:31:43,894] [INFO] [axolotl.normalize_config:122] [PID:737150] [RANK:0] GPU memory usage baseline: 0.000GB (+0.111GB misc)
[2023-10-30 18:31:44,277] [DEBUG] [axolotl.load_tokenizer:75] [PID:737150] [RANK:0] EOS: 50256 / <|endoftext|>
[2023-10-30 18:31:44,277] [DEBUG] [axolotl.load_tokenizer:76] [PID:737150] [RANK:0] BOS: 50256 / <|endoftext|>
[2023-10-30 18:31:44,277] [DEBUG] [axolotl.load_tokenizer:77] [PID:737150] [RANK:0] PAD: None / None
[2023-10-30 18:31:44,277] [DEBUG] [axolotl.load_tokenizer:78] [PID:737150] [RANK:0] UNK: 50256 / <|endoftext|>
[2023-10-30 18:31:44,277] [INFO] [axolotl.load_tokenized_prepared_datasets:130] [PID:737150] [RANK:0] Unable to find prepared dataset in last_run_prepared/77430bc3a24c46923a24c2ca63bb7adc
[2023-10-30 18:31:44,277] [INFO] [axolotl.load_tokenized_prepared_datasets:131] [PID:737150] [RANK:0] Loading raw datasets...
[2023-10-30 18:31:44,277] [INFO] [axolotl.load_tokenized_prepared_datasets:136] [PID:737150] [RANK:0] No seed provided, using default seed of 42
[2023-10-30 18:31:44,752] [INFO] [axolotl.load_tokenized_prepared_datasets:354] [PID:737150] [RANK:0] merging datasets
[2023-10-30 18:31:44,754] [INFO] [axolotl.load_tokenized_prepared_datasets:361] [PID:737150] [RANK:0] Saving merged prepared dataset to disk... last_run_prepared/77430bc3a24c46923a24c2ca63bb7adc
Saving the dataset (1/1 shards): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15011/15011 [00:00<00:00, 291069.67 examples/s]
[2023-10-30 18:31:44,967] [INFO] [axolotl.calculate_total_num_steps:529] [PID:737150] [RANK:0] total_num_steps: 56208
[2023-10-30 18:31:44,972] [INFO] [axolotl.train.train:49] [PID:737150] [RANK:0] loading tokenizer... microsoft/phi-1_5
[2023-10-30 18:31:45,141] [DEBUG] [axolotl.load_tokenizer:75] [PID:737150] [RANK:0] EOS: 50256 / <|endoftext|>
[2023-10-30 18:31:45,141] [DEBUG] [axolotl.load_tokenizer:76] [PID:737150] [RANK:0] BOS: 50256 / <|endoftext|>
[2023-10-30 18:31:45,141] [DEBUG] [axolotl.load_tokenizer:77] [PID:737150] [RANK:0] PAD: None / None
[2023-10-30 18:31:45,141] [DEBUG] [axolotl.load_tokenizer:78] [PID:737150] [RANK:0] UNK: 50256 / <|endoftext|>
[2023-10-30 18:31:45,142] [INFO] [axolotl.train.train:57] [PID:737150] [RANK:0] loading model and (optionally) peft_config...
[2023-10-30 18:31:48,045] [INFO] [axolotl.load_model:396] [PID:737150] [RANK:0] GPU memory usage after model load: 0.972GB (+0.012GB cache, +0.224GB misc)
[2023-10-30 18:31:48,045] [INFO] [axolotl.load_model:413] [PID:737150] [RANK:0] converting PEFT model w/ prepare_model_for_kbit_training
[2023-10-30 18:31:48,052] [INFO] [axolotl.load_model:424] [PID:737150] [RANK:0] converting modules to torch.float16 for flash attention
[2023-10-30 18:31:48,053] [INFO] [axolotl.load_lora:533] [PID:737150] [RANK:0] found linear modules: ['fc1', 'linear', 'out_proj', 'fc2', 'Wqkv']
[2023-10-30 18:31:48,053] [DEBUG] [axolotl.load_lora:548] [PID:737150] [RANK:0] Loading pretained PEFT - LoRA
Traceback (most recent call last):
  File "/home/user/axolotl/scripts/finetune.py", line 54, in <module>
    fire.Fire(do_cli)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/axolotl/scripts/finetune.py", line 50, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/home/user/axolotl/src/axolotl/train.py", line 58, in train
    model, peft_config = load_model(cfg, tokenizer, inference=cli_args.inference)
  File "/home/user/axolotl/src/axolotl/utils/models.py", line 432, in load_model
    model, lora_config = load_adapter(model, cfg, cfg.adapter)
  File "/home/user/axolotl/src/axolotl/utils/models.py", line 474, in load_adapter
    return load_lora(model, cfg, inference=inference)
  File "/home/user/axolotl/src/axolotl/utils/models.py", line 549, in load_lora
    model = PeftModel.from_pretrained(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 293, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 925, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 117, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 234, in inject_adapter
    raise ValueError(
ValueError: Target modules ['v_proj', 'down_proj', 'q_proj', 'up_proj', 'o_proj', 'gate_proj', 'k_proj'] not found in the base model. Please check the target modules and try again.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/textgen/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/miniconda3/envs/textgen/bin/python', 'scripts/finetune.py', 'examples/phi/phi-qlora-mine.yml', '--lora_model_dir=./qlora-out/']' returned non-zero exit status 1.
(textgen) [root@pve-m7330 axolotl]# accelerate launch scripts/finetune.py examples/phi/phi-qlora-mine.yml --lora_model_dir="./qlora-out/"

```

### Steps to reproduce

accelerate launch scripts/finetune.py examples/phi/phi-qlora-mine.yml --lora_model_dir="./qlora-out/"

### Config yaml

base_model: microsoft/phi-1_5
base_model_config: microsoft/phi-1_5
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
is_llama_derived_model: false
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /home/user/datasets/mine/dolly_15k.jsonl
    type: alpaca
dataset_prepared_path:
val_set_size: 0.05
output_dir: ./phi-sft-out

sequence_len: 1024
sample_packing: false  # not CURRENTLY compatible with LoRAs
pad_to_sequence_len:

adapter: qlora
lora_model_dir:
lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 4
optimizer: adamw_torch
adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0
lr_scheduler: cosine
learning_rate: 0.000003

train_on_inputs: false
group_by_length: true
bf16: false
fp16: true
tf32: false

gradient_checkpointing:
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention:

warmup_steps: 100
eval_steps: 0.05
save_steps:
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
resize_token_embeddings_to_32x: true
special_tokens:
  bos_token: "<|endoftext|>"
  eos_token: "<|endoftext|>"
  unk_token: "<|endoftext|>"
  pad_token: "<|endoftext|>"

### Possible solution

remove the calls being made for these qlora's?

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/a126b03

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by NanoCode012** [comment]
Hello, can you remove `--lora_model_dir="./qlora-out/"` from your calls? It is only when you want to load existing lora. The trained lora will be saved to `--output_dir`.

I've also did a qlora phi with the one in examples which worked for me. Can you check that it works for you?

```bash
accelerate launch -m axolotl.cli.train examples/phi/phi-qlora.yml --bf16=False --fp16=True --tf32=False
```

**Comment by thistleknot** [comment]
Doh! I'm sure that was it

**Comment by NanoCode012** [comment]
Closing it as it seems to be solved.
