### ISSUE TITLE
Training crashes when using eval table and training with sample_packing

### ISSUE THREAD

**Issue by mxbi** [axolotl-ai-cloud/axolotl#808]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

To use `eval_table:
```yaml
eval_table_size: 4
eval_table_max_new_tokens: 128
```
one is told to set:
```yaml
sample_packing: true
eval_sample_packing: false
```
Which allows sample packing to be used in training, but not during testing.

### Current behaviour

Instead, I get the following stacktrace:

```
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 118, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1999, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 2328, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 3062, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/workspace/axolotl/src/axolotl/core/trainer_builder.py", line 201, in get_eval_dataloader
    MultipackDistributedDataloader(
  File "/workspace/axolotl/src/axolotl/utils/dataloader.py", line 161, in __init__
    dataset.data.column("position_ids")
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/table.py", line 390, in column
    return self.table.column(*args, **kwargs)
  File "pyarrow/table.pxi", line 1611, in pyarrow.lib._Tabular.column
  File "pyarrow/table.pxi", line 1547, in pyarrow.lib._Tabular._ensure_integer_index
KeyError: 'Field "position_ids" does not exist in schema'
```

If I set `sample_packing: false` (disabling it for training also), or if I set `eval_table_size: 0` (disabling the eval table), then this works fine.

### Steps to reproduce

Take `examples/mistral/qlora.yaml`, and set:
```
eval_sample_packing: false
eval_table_size: 4
```

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10.13

### axolotl branch-commit

10388a8daf593ca1e762c668b30feab373c6c42a (latest main)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by TheBloke** [comment]
I'm getting this as well, except in my case, I can't fix it by setting `eval_table_size: 0`.  According to the docs that's the default, so I think setting that wasn't changing anything for me.

Here's my current config, which will fail on the first eval step with the error shown in the OP:
```yaml
base_model: mistralai/Mistral-7B-v0.1
base_model_config: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /path/to/custom-dataset.json
    type: custom-prompt-strategy

dataset_prepared_path: ./last_run_prepared
val_set_size: 0.01
output_dir: /workspace/output-model

sequence_len: 4096
sample_packing: true
eval_sample_packing: false
eval_table_size: 0
pad_to_sequence_len: true
total_supervised_tokens: 5617006

wandb_project: project-name
wandb_entity: thebloke
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 6
num_epochs: 4
optimizer: adamw_torch
adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0
lr_scheduler: cosine
learning_rate: 0.000006

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
auto_resume_from_checkpoint: true
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 50
eval_steps: 0.1
save_steps:
debug:
deepspeed: /workspace/axolotl/deepspeed/zero2.json
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "█"
  unk_token: "<unk>"
```

For now I've had to disable eval completely so I can get the training done.

Here's the exact error I received:
```
[2023-11-08 10:22:59,892] [INFO] [axolotl.utils.samplers.multipack._len_est:178] [PID:35578] [RANK:0] packing_efficiency_estimate: 0.97 total_num_tokens per device: 1161627
{'loss': 1.2304, 'learning_rate': 0.0, 'epoch': 0.03}
  1%|██▍                                                                                                                                                                                                                                                                                                                                                     | 1/140 [00:34<1:20:39, 34.82s/it]Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 124, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1984, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 2328, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 3062, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/workspace/axolotl/src/axolotl/core/trainer_builder.py", line 226, in get_eval_dataloader
    eval_sampler = self._get_eval_sampler(eval_dataset)
  File "/workspace/axolotl/src/axolotl/core/trainer_builder.py", line 178, in _get_eval_sampler
    eval_dataset.data.column("position_ids")
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/table.py", line 390, in column
    return self.table.column(*args, **kwargs)
  File "pyarrow/table.pxi", line 1624, in pyarrow.lib._Tabular.column
  File "pyarrow/table.pxi", line 1560, in pyarrow.lib._Tabular._ensure_integer_index
KeyError: 'Field "position_ids" does not exist in schema'
```

The above error was with `eval_sample_packing: false`.  I first tried with that set to True, which gave this different error at the same point:

```
[2023-11-08 10:19:50,901] [INFO] [axolotl.utils.samplers.multipack._len_est:178] [PID:28284] [RANK:7] packing_efficiency_estimate: 0.97 total_num_tokens per device: 15686
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 124, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1984, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 2328, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 3066, in evaluate
    output = eval_loop(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 3214, in evaluation_loop
    if has_length(dataloader):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/trainer_utils.py", line 623, in has_length
    return len(dataset) is not None
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 486, in __len__
    return len(self._index_sampler)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/data_loader.py", line 133, in __len__
    if len(self.batch_sampler) % self.num_processes == 0:
ValueError: __len__() should return >= 0
```

**Comment by winglian** [comment]
We have since added validation to prevent this.
