### ISSUE TITLE
KeyError: 'instruction' when fine-tuning with Axolotl

### ISSUE THREAD

**Issue by rafael-wampfler** [axolotl-ai-cloud/axolotl#879]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The fine-tuning of meta-llama/Llama-2-13b-chat-hf should run normally.

### Current behaviour

I'm getting an KeyError: 'Instruction', see the following log:

```
[2023-11-18 23:53:53,979] [DEBUG] [axolotl.load_tokenizer:102] [PID:2470] [RANK:0] PAD: 2 / </s>
[2023-11-18 23:53:53,979] [DEBUG] [axolotl.load_tokenizer:103] [PID:2470] [RANK:0] UNK: 0 / <unk>
[2023-11-18 23:53:53,979] [INFO] [axolotl.load_tokenized_prepared_datasets:153] [PID:2470] [RANK:0] No seed provided, using default seed of 42
Map (num_proc=64):   0%|                                                                                                                                                                              | 0/3747 [00:00<?, ? examples/s]
    for i, result in enumerate(func(**kwargs)):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3450, in _map_single
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/axolotl/axolotl/scripts/finetune.py", line 52, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/axolotl/scripts/finetune.py", line 47, in do_cli
    dataset_meta = load_datasets(cfg=parsed_cfg, cli_args=parsed_cli_args)
  File "/workspace/axolotl/axolotl/src/axolotl/cli/__init__.py", line 312, in load_datasets
    train_dataset, eval_dataset, total_num_steps, prompters = prepare_dataset(
  File "/workspace/axolotl/axolotl/src/axolotl/utils/data.py", line 63, in prepare_dataset
    train_dataset, eval_dataset, prompters = load_prepare_datasets(
  File "/workspace/axolotl/axolotl/src/axolotl/utils/data.py", line 511, in load_prepare_datasets
    dataset, prompters = load_tokenized_prepared_datasets(
  File "/workspace/axolotl/axolotl/src/axolotl/utils/data.py", line 351, in load_tokenized_prepared_datasets
    dataset_wrapper, dataset_prompter = get_dataset_wrapper(
  File "/workspace/axolotl/axolotl/src/axolotl/utils/data.py", line 599, in get_dataset_wrapper
    ds_wrapper = TokenizedPromptDataset(
  File "/workspace/axolotl/axolotl/src/axolotl/datasets.py", line 38, in __init__
    super().__init__(self.process(dataset).data, **kwargs)
  File "/workspace/axolotl/axolotl/src/axolotl/datasets.py", line 51, in process
    return dataset.map(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3189, in map
    for rank, done, content in iflatmap_unordered(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1394, in iflatmap_unordered
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1394, in <listcomp>
    [async_result.get(timeout=0.05) for async_result in async_results]
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/multiprocess/pool.py", line 774, in get
    raise self._value
KeyError: 'instruction'
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/py3.10/bin/python3', 'scripts/finetune.py', 'Axolotl2/llama-einstein.yml']' returned non-zero exit status 1.
```

### Steps to reproduce

I'm using a RunPod with a 48 GB GPU with the container image winglian/axolotl-runpod:main-py3.10-cu118-2.0.1. 

I executed the following code:

```
git clone https://github.com/OpenAccess-AI-Collective/axolotl
cd axolotl

pip3 install -e .[flash-attn]
pip3 install -U git+https://github.com/huggingface/peft.git
accelerate launch scripts/finetune.py myconfig.yaml
```

### Config yaml

```
base_model: meta-llama/Llama-2-13b-chat-hf
base_model_config: meta-llama/Llama-2-13b-chat-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: myusername/einstein-llama
    type: alpaca
    field: text
dataset_prepared_path: last_run_prepared
hub_model_id: myusername/einstein-llama
val_set_size: 0.01
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: "llama-einstein"
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model: "checkpoint"

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0.05
eval_table_size:
save_steps:
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
```

### Possible solution

It looks like the `instruction` key is missing in the data. I have structured my data as follows:

```
{"text": "### Human: This is a question### Chatbot: This is a reply### Human: What the hell are you talking about?"}
{"text": "### Human: Who's coming tonight?### Chatbot: No one, it's literally Monday."}
```

Metadata on Huggingface are as follows:

```
dataset_info:
  features:
    - name: text
      dtype: string
  splits:
    - name: train
      num_bytes: 14406788
      num_examples: 3747
    - name: test
      num_bytes: 1853149
      num_examples: 478
  download_size: 8008959
  dataset_size: 16259937
configs:
  - config_name: default
    data_files:
      - split: train
        path: data/train-*
      - split: test
        path: data/test-*
```

So I'm using `completion`. I have indicated this in the config file with `field: text`.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.10

### axolotl branch-commit

main/575a082

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by winglian** [comment]
Alpaca requires two fields, one for instruction and one for the output/model response. You have two options, convert your dataset or use the completion type.
