### ISSUE TITLE
Deepspeed import error on clone_tensors_for_torch_save

### ISSUE THREAD

**Issue by theobjectivedad** [axolotl-ai-cloud/axolotl#994]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/OpenAccess-AI-Collective/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

Checkpoint is saved without error.

### Current behaviour

The following exception gets raise during a checkpoint save, as far as I can tell finetuning looks OK up to the checkpoint save:

```text
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 87, in _run_code
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 129, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1540, in train
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 129, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1540, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1917, in _inner_training_loop
    return inner_training_loop(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1917, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2277, in _maybe_log_save_evaluate
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2277, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2353, in _save_checkpoint
Traceback (most recent call last):
      File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2353, in _save_checkpoint
    self.save_model(staging_output_dir, _internal_call=True)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2832, in save_model
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 38, in <module>
    fire.Fire(do_cli)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/axolotl/src/axolotl/cli/train.py", line 34, in do_cli
    train(cfg=parsed_cfg, cli_args=parsed_cli_args, dataset_meta=dataset_meta)
  File "/workspace/axolotl/src/axolotl/train.py", line 129, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
    self.save_model(staging_output_dir, _internal_call=True)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2832, in save_model
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1540, in train
    return inner_training_loop(
    state_dict = self.accelerator.get_state_dict(self.deepspeed)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 3096, in get_state_dict
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1917, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2277, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2353, in _save_checkpoint
    self.save_model(staging_output_dir, _internal_call=True)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 2832, in save_model
    state_dict = self.accelerator.get_state_dict(self.deepspeed)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 3096, in get_state_dict
    from deepspeed.checkpoint.utils import clone_tensors_for_torch_save
ImportError: cannot import name 'clone_tensors_for_torch_save' from 'deepspeed.checkpoint.utils' (/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/checkpoint/utils.py)
    from deepspeed.checkpoint.utils import clone_tensors_for_torch_save
state_dict = self.accelerator.get_state_dict(self.deepspeed)
ImportError  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 3096, in get_state_dict
: cannot import name 'clone_tensors_for_torch_save' from 'deepspeed.checkpoint.utils' (/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/checkpoint/utils.py)
    from deepspeed.checkpoint.utils import clone_tensors_for_torch_save
ImportError: cannot import name 'clone_tensors_for_torch_save' from 'deepspeed.checkpoint.utils' (/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/deepspeed/checkpoint/utils.py)
```

### Steps to reproduce

I am building and running the axolotl container locally. I'm using 3x A6000s on 1 host and have been able to reproduce with both zero1 and zero2.

## Launch commands

Build axolotl image:

```shell
cd $(AXOLOTL_SRC)/docker
docker build . -t axolotl-local:latest
```

Makefile target to launch trainer:

```make
.PHONY: train
train:
	docker run -it --rm \
		--gpus='"device=0,1,2"' \
		--shm-size=1g \
                 --ulimit memlock=-1 \
		--volume=$(CURDIR):/project \
		--volume=/models:/models \
		--volume=/data:/data \
		--volume=/work:/work \
		--env-file=$(CURDIR)/config/secrets.env \
		--env-file=$(CURDIR)/config/train.env \
		--env=HF_DATASETS_CACHE=/project/tmp/.cache \
		--workdir=/project \
		axolotl-local:latest \
		/project/bin/train.sh /project/config/axolotl_dolphin-2.5-mixtral-8x7b-qlora.yaml
```

Launch script that gets run within the Makefile. I needed to do this since deepspeed extensions are built w/ pytorch+cuda 11.8 but somehow pytorch w/ cuda 11.7 is getting build into the container. I know this is a hack and may be the root cause of my issue, however I can't use deepspeed without the pip install in this script:

```bash
#!/bin/bash
python3 -m pip install --find-links /project/wheels -U torch==2.0.1+cu118 deepspeed-kernels
accelerate launch \
	-m axolotl.cli.train \
	"$1"
```

Finally to run the trainer I just do a:

```shell
make train
```

### Config yaml

```yaml
base_model: /models/dolphin-2.5-mixtral-8x7b
model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer
trust_remote_code: true

# gptq: true
# gptq_disable_exllama: false

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
dataset_prepared_path: /project/tmp/last_run_prepared
val_set_size: 0.0
output_dir: /project/output

## You can optionally freeze the entire model and unfreeze a subset of parameters
unfrozen_parameters:
#  - lm_head.*
#  - model.embed_tokens.*
#  - model.layers.2[0-9]+.block_sparse_moe.gate.*
#  - model.layers.2[0-9]+.block_sparse_moe.experts.*
#  - model.layers.3[0-9]+.block_sparse_moe.gate.*
#  - model.layers.3[0-9]+.block_sparse_moe.experts.*

adapter: qlora
lora_model_dir:

sequence_len: 16384


sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.0
lora_target_linear:
lora_fan_in_fan_out:
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - w1
  - w2
  - w3

# Eric had this set, need to see what it does
# lora_modules_to_save:
#   - embed_tokens
#   - lm_head

wandb_project: eleanor
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 100
eval_steps:
# evals_per_epoch: 4
# eval_table_size:
# eval_table_max_new_tokens: 128

save_steps: 0.01
save_total_limit: 2

debug:
deepspeed: /workspace/axolotl/deepspeed/zero2.json
weight_decay: 0.05
fsdp:
fsdp_config:

special_tokens:
  eos_token: "<|im_end|>"
tokens:
  - "<|im_start|>"

seed: 43
```

### Possible solution

As I mentioned above, this may be happening because I needed to reinstall pytorch with CUDA 11.8 in the axolotl container.

My build of the axolotl container, somehow pytorch is getting reinstalled w/ another CUDA version:

```shell
root@d338a5f730a7:/workspace/axolotl# python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.1+cu117'
```

Base container has CUDA 11.8:

```shell
docker run -it --rm winglian/axolotl-base:main-base
root@86c872380164:/workspace# python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.0+cu118'
```

For fun, looking at the latest axolotl image as of 2023-12-21 21:43:16 CST it appears that the correct CUDA version is installed.

```shell
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.0.1+cu118'
```

I'll try my trainer again with ``winglian/axolotl:dev-latest`` to see if the issue persists. If everything looks OK I can take a look at what is going wrong when I build locally.

### Which Operating Systems are you using?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.9.16

### axolotl branch-commit

main/62ba1609b6ca37ca5f344894ced0d45bcfb2a9d4

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by theobjectivedad** [comment]
Good news, the process is saving properly now with ``winglian/axolotl:dev-latest`` ... I'll monitor overnight.

Also, now I see in [main.yml](https://github.com/OpenAccess-AI-Collective/axolotl/blob/62ba1609b6ca37ca5f344894ced0d45bcfb2a9d4/.github/workflows/main.yml#L53) that the ``BASE_TAG`` argument is getting set dynamically.

@winglian let me know if you would like me to remove the default BASE_TAG value from the [Dockerfile](https://github.com/OpenAccess-AI-Collective/axolotl/blob/62ba1609b6ca37ca5f344894ced0d45bcfb2a9d4/docker/Dockerfile#L1) so it can fail closer to where the actual problem is (for folks build their own docker container).

**Comment by winglian** [comment]
We recently made some fixes to how the images are getting built that should prevent the incorrect versions of torch/cuda from getting installed. it is the correct behavior to dynamically build the tag from the matrix of version dependencies. be careful with `dev` tagged branches. those rarely get updated and I think the most recent dev ones were only built for Hamel to do some testing.

**Comment by winglian** [comment]
as for the bad imports, this is likely due to an issue with accelerate expecting a particular version of deepspeed to have that particular import available. I'd suggest updating deepspeed if appropriate.

**Comment by theobjectivedad** [comment]
Marking resolved.
